/**
 * Word文档处理引擎
 * 提供Word文档的读取、写入、编辑和转换功能
 * 支持 .docx 格式
 */

const fs = require('fs').promises;
const path = require('path');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, UnderlineType } = require('docx');
const mammoth = require('mammoth');
const { marked } = require('marked');

class WordEngine {
  constructor() {
    this.supportedFormats = ['.docx', '.doc'];
  }

  /**
   * 读取Word文档
   * @param {string} filePath - 文件路径
   * @returns {Promise<Object>} 文档内容
   */
  async readWord(filePath) {
    try {
      console.log('[WordEngine] 读取Word文档:', filePath);

      // 使用mammoth将Word转换为HTML
      const result = await mammoth.convertToHtml({ path: filePath });
      const html = result.value;
      const messages = result.messages;

      // 同时提取纯文本
      const textResult = await mammoth.extractRawText({ path: filePath });
      const text = textResult.value;

      // 解析HTML为结构化内容
      const content = this.parseHtmlToContent(html);

      return {
        success: true,
        html,
        text,
        content,
        messages,
        metadata: await this.extractMetadata(filePath),
      };
    } catch (error) {
      console.error('[WordEngine] 读取Word失败:', error);
      throw error;
    }
  }

  /**
   * 写入Word文档
   * @param {string} filePath - 文件路径
   * @param {Object} content - 文档内容
   */
  async writeWord(filePath, content) {
    try {
      console.log('[WordEngine] 写入Word文档:', filePath);

      const { title, paragraphs = [], styles = {} } = content;

      // 创建文档对象
      const sections = [];
      const children = [];

      // 添加标题
      if (title) {
        children.push(
          new Paragraph({
            text: title,
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: {
              after: 400,
            },
          })
        );
      }

      // 添加段落
      for (const para of paragraphs) {
        children.push(this.createParagraph(para));
      }

      sections.push({
        properties: {},
        children,
      });

      const doc = new Document({
        creator: 'ChainlessChain',
        title: title || 'Untitled',
        description: 'Generated by ChainlessChain',
        sections,
      });

      // 生成文档并保存
      const buffer = await Packer.toBuffer(doc);
      await fs.writeFile(filePath, buffer);

      return {
        success: true,
        filePath,
      };
    } catch (error) {
      console.error('[WordEngine] 写入Word失败:', error);
      throw error;
    }
  }

  /**
   * 创建段落对象
   */
  createParagraph(paraData) {
    const { text, style = {}, heading, alignment, spacing } = paraData;

    const textRuns = [];

    if (typeof text === 'string') {
      textRuns.push(
        new TextRun({
          text,
          bold: style.bold || false,
          italics: style.italic || false,
          underline: style.underline ? { type: UnderlineType.SINGLE } : undefined,
          size: style.fontSize ? style.fontSize * 2 : undefined, // Word使用半磅
          font: style.fontFamily || 'Arial',
          color: style.color,
        })
      );
    } else if (Array.isArray(text)) {
      // 支持富文本runs
      for (const run of text) {
        textRuns.push(
          new TextRun({
            text: run.text || '',
            bold: run.bold || false,
            italics: run.italic || false,
            underline: run.underline ? { type: UnderlineType.SINGLE } : undefined,
            size: run.fontSize ? run.fontSize * 2 : undefined,
            font: run.fontFamily,
            color: run.color,
          })
        );
      }
    }

    return new Paragraph({
      children: textRuns,
      heading: this.getHeadingLevel(heading),
      alignment: this.getAlignment(alignment),
      spacing: spacing || { after: 200 },
    });
  }

  /**
   * 获取标题级别
   */
  getHeadingLevel(level) {
    const levels = {
      1: HeadingLevel.HEADING_1,
      2: HeadingLevel.HEADING_2,
      3: HeadingLevel.HEADING_3,
      4: HeadingLevel.HEADING_4,
      5: HeadingLevel.HEADING_5,
      6: HeadingLevel.HEADING_6,
    };
    return levels[level];
  }

  /**
   * 获取对齐方式
   */
  getAlignment(align) {
    const alignments = {
      left: AlignmentType.LEFT,
      center: AlignmentType.CENTER,
      right: AlignmentType.RIGHT,
      justify: AlignmentType.JUSTIFIED,
    };
    return alignments[align] || AlignmentType.LEFT;
  }

  /**
   * 解析HTML为结构化内容
   */
  parseHtmlToContent(html) {
    // 简单的HTML解析，提取段落和格式
    const paragraphs = [];

    // 按行分割
    const lines = html.split('</p>');

    for (const line of lines) {
      if (!line.trim()) continue;

      // 提取文本和基本格式
      const text = line
        .replace(/<[^>]+>/g, '')
        .trim();

      if (text) {
        const para = {
          text,
          style: {},
        };

        // 检测粗体
        if (line.includes('<strong>') || line.includes('<b>')) {
          para.style.bold = true;
        }

        // 检测斜体
        if (line.includes('<em>') || line.includes('<i>')) {
          para.style.italic = true;
        }

        // 检测标题
        const headingMatch = line.match(/<h(\d)>/);
        if (headingMatch) {
          para.heading = parseInt(headingMatch[1]);
        }

        paragraphs.push(para);
      }
    }

    return { paragraphs };
  }

  /**
   * 提取元数据
   */
  async extractMetadata(filePath) {
    try {
      const stats = await fs.stat(filePath);
      return {
        fileName: path.basename(filePath),
        size: stats.size,
        created: stats.birthtime,
        modified: stats.mtime,
      };
    } catch (error) {
      return {};
    }
  }

  /**
   * Markdown转Word
   */
  async markdownToWord(markdownText, outputPath, options = {}) {
    try {
      console.log('[WordEngine] Markdown转Word');

      // 解析Markdown
      const html = marked(markdownText);
      const content = this.parseHtmlToContent(html);

      // 添加选项
      if (options.title) {
        content.title = options.title;
      }

      // 生成Word文档
      return await this.writeWord(outputPath, content);
    } catch (error) {
      console.error('[WordEngine] Markdown转Word失败:', error);
      throw error;
    }
  }

  /**
   * Word转Markdown
   */
  async wordToMarkdown(filePath) {
    try {
      console.log('[WordEngine] Word转Markdown');

      const result = await this.readWord(filePath);

      // 简单的Markdown转换
      let markdown = '';

      for (const para of result.content.paragraphs) {
        let line = para.text;

        // 处理标题
        if (para.heading) {
          line = '#'.repeat(para.heading) + ' ' + line;
        }

        // 处理粗体
        if (para.style.bold) {
          line = '**' + line + '**';
        }

        // 处理斜体
        if (para.style.italic) {
          line = '*' + line + '*';
        }

        markdown += line + '\n\n';
      }

      return {
        success: true,
        markdown,
      };
    } catch (error) {
      console.error('[WordEngine] Word转Markdown失败:', error);
      throw error;
    }
  }

  /**
   * Word转PDF
   * 注意: 需要LibreOffice或其他转换工具
   */
  async wordToPDF(filePath, outputPath) {
    try {
      console.log('[WordEngine] Word转PDF');

      // 这里需要外部工具，如LibreOffice
      // 暂时返回未实现的错误
      throw new Error('Word转PDF需要安装LibreOffice或其他转换工具');
    } catch (error) {
      console.error('[WordEngine] Word转PDF失败:', error);
      throw error;
    }
  }

  /**
   * HTML转Word
   */
  async htmlToWord(html, outputPath, options = {}) {
    try {
      console.log('[WordEngine] HTML转Word');

      const content = this.parseHtmlToContent(html);

      if (options.title) {
        content.title = options.title;
      }

      return await this.writeWord(outputPath, content);
    } catch (error) {
      console.error('[WordEngine] HTML转Word失败:', error);
      throw error;
    }
  }

  /**
   * 创建Word模板
   */
  async createTemplate(templateType, outputPath, data = {}) {
    try {
      console.log('[WordEngine] 创建Word模板:', templateType);

      const templates = {
        report: this.createReportTemplate,
        letter: this.createLetterTemplate,
        resume: this.createResumeTemplate,
      };

      const createFn = templates[templateType];
      if (!createFn) {
        throw new Error(`未知的模板类型: ${templateType}`);
      }

      const content = createFn.call(this, data);
      return await this.writeWord(outputPath, content);
    } catch (error) {
      console.error('[WordEngine] 创建模板失败:', error);
      throw error;
    }
  }

  /**
   * 创建报告模板
   */
  createReportTemplate(data) {
    const { title = '工作报告', author = '作者', date = new Date().toLocaleDateString() } = data;

    return {
      title,
      paragraphs: [
        { text: `作者: ${author}`, alignment: 'right' },
        { text: `日期: ${date}`, alignment: 'right', spacing: { after: 400 } },
        { text: '摘要', heading: 1 },
        { text: '在此输入报告摘要...', spacing: { after: 400 } },
        { text: '背景', heading: 1 },
        { text: '在此输入背景信息...', spacing: { after: 400 } },
        { text: '主要内容', heading: 1 },
        { text: '在此输入主要内容...', spacing: { after: 400 } },
        { text: '结论', heading: 1 },
        { text: '在此输入结论...', spacing: { after: 400 } },
      ],
    };
  }

  /**
   * 创建信件模板
   */
  createLetterTemplate(data) {
    const { recipient = '收件人', sender = '发件人', date = new Date().toLocaleDateString() } = data;

    return {
      paragraphs: [
        { text: date, alignment: 'right', spacing: { after: 200 } },
        { text: `尊敬的 ${recipient}:`, spacing: { after: 200 } },
        { text: '在此输入信件正文...', spacing: { after: 200 } },
        { text: '此致', spacing: { after: 100 } },
        { text: '敬礼', spacing: { after: 200 } },
        { text: sender, alignment: 'right', spacing: { after: 100 } },
        { text: date, alignment: 'right' },
      ],
    };
  }

  /**
   * 创建简历模板
   */
  createResumeTemplate(data) {
    const { name = '姓名', phone = '电话', email = '邮箱' } = data;

    return {
      title: name,
      paragraphs: [
        { text: `电话: ${phone} | 邮箱: ${email}`, alignment: 'center', spacing: { after: 400 } },
        { text: '教育背景', heading: 1 },
        { text: '在此输入教育背景...', spacing: { after: 400 } },
        { text: '工作经历', heading: 1 },
        { text: '在此输入工作经历...', spacing: { after: 400 } },
        { text: '项目经验', heading: 1 },
        { text: '在此输入项目经验...', spacing: { after: 400 } },
        { text: '技能特长', heading: 1 },
        { text: '在此输入技能特长...', spacing: { after: 400 } },
      ],
    };
  }
}

module.exports = new WordEngine();
