-- 头条-明文库 全部明文库 schema（仅结构，CREATE 语句，无数据）
-- 提取 2026-06-17

-- ===== 13@bd_tea_agent.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE event(_id integer primary key autoincrement,local_time_ms integer,tea_event_index integer,nt integer,user_id integer,uid integer,session_id varchar,user_unique_id varchar,ab_sdk_version varchar,user_type integer,user_is_login integer,user_is_auth integer,_app_id varchar,priority integer,forward integer,_local_event_id varchar,monitor_id integer,event_stained integer,category varchar,tag varchar,value integer,ext_value integer,params varchar,label varchar);
CREATE TABLE event_misc(_id integer primary key autoincrement,local_time_ms integer,tea_event_index integer,nt integer,user_id integer,uid integer,session_id varchar,user_unique_id varchar,ab_sdk_version varchar,user_type integer,user_is_login integer,user_is_auth integer,_app_id varchar,priority integer,forward integer,_local_event_id varchar,monitor_id integer,event_stained integer,params varchar,log_type varchar);
CREATE TABLE eventv3(_id integer primary key autoincrement,local_time_ms integer,tea_event_index integer,nt integer,user_id integer,uid integer,session_id varchar,user_unique_id varchar,ab_sdk_version varchar,user_type integer,user_is_login integer,user_is_auth integer,_app_id varchar,priority integer,forward integer,_local_event_id varchar,monitor_id integer,event_stained integer,event varchar,params varchar,is_bav integer,disable_personalization varchar,page_info varchar);
CREATE TABLE forward_eventv3(_id integer primary key autoincrement,local_time_ms integer,tea_event_index integer,nt integer,user_id integer,uid integer,session_id varchar,user_unique_id varchar,ab_sdk_version varchar,user_type integer,user_is_login integer,user_is_auth integer,_app_id varchar,priority integer,forward integer,_local_event_id varchar,monitor_id integer,event_stained integer,event varchar,params varchar,is_bav integer,disable_personalization varchar,page_info varchar);
CREATE TABLE launch(_id integer primary key autoincrement,local_time_ms integer,tea_event_index integer,nt integer,user_id integer,uid integer,session_id varchar,user_unique_id varchar,ab_sdk_version varchar,user_type integer,user_is_login integer,user_is_auth integer,_app_id varchar,priority integer,forward integer,_local_event_id varchar,monitor_id integer,event_stained integer,ver_name varchar,ver_code integer,last_session varchar,is_background integer,flat_params varchar);
CREATE TABLE pack(_id integer primary key autoincrement,local_time_ms integer,_data blob,session_id varchar,_fail integer,event_count varchar,key varchar,iv varchar,data_json text,_app_id varchar,encode_type integer,encode_headers varchar,priority integer,forward integer,e_ids varchar,isolate_key varchar,isolate_key_value varchar,_launch_count integer,_terminate_count integer,_event_v1_count integer,_event_v3_count integer,_event_misc_count integer,_impression_count integer,sentry_stained_ids varchar);
CREATE TABLE page(_id integer primary key autoincrement,local_time_ms integer,tea_event_index integer,nt integer,user_id integer,uid integer,session_id varchar,user_unique_id varchar,ab_sdk_version varchar,user_type integer,user_is_login integer,user_is_auth integer,_app_id varchar,priority integer,forward integer,_local_event_id varchar,monitor_id integer,event_stained integer,page_key varchar,refer_page_key varchar,duration integer,is_back integer,last_session varchar,flat_params varchar);

-- ===== 13_feature_engineering.db =====
CREATE TABLE AppLog_frequency_control (id           INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp    INTEGER     NOT NULL DEFAULT (strftime('%s','now')), timestamp_ms INTEGER     DEFAULT 0, event_name   TEXT        NOT NULL, params       TEXT);
CREATE TABLE AppLog_live_video_prefetch (id           INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp    INTEGER     NOT NULL DEFAULT (strftime('%s','now')), timestamp_ms INTEGER     DEFAULT 0, event_name   TEXT        NOT NULL, params       TEXT);
CREATE TABLE AppLog_multi_instance (id           INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp    INTEGER     NOT NULL DEFAULT (strftime('%s','now')), timestamp_ms INTEGER     DEFAULT 0, event_name   TEXT        NOT NULL, params       TEXT);
CREATE TABLE AppLog_tomato_wind_vane_refresh (id           INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp    INTEGER     NOT NULL DEFAULT (strftime('%s','now')), timestamp_ms INTEGER     DEFAULT 0, event_name   TEXT        NOT NULL, params       TEXT, room_id TEXT, click_area TEXT, ecom_entrance_form TEXT, carrier_source TEXT, author_id TEXT);
CREATE TABLE AppLog_video_preload (id           INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp    INTEGER     NOT NULL DEFAULT (strftime('%s','now')), timestamp_ms INTEGER     DEFAULT 0, event_name   TEXT        NOT NULL, params       TEXT);
CREATE TABLE AppLog_video_tab (id           INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp    INTEGER     NOT NULL DEFAULT (strftime('%s','now')), timestamp_ms INTEGER     DEFAULT 0, event_name   TEXT        NOT NULL, params       TEXT);
CREATE TABLE AppLog_video_tab_preload (id           INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp    INTEGER     NOT NULL DEFAULT (strftime('%s','now')), timestamp_ms INTEGER     DEFAULT 0, event_name   TEXT        NOT NULL, params       TEXT);
CREATE TABLE DatabaseCache_douyin_rec_features (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_gip_client_metrics (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_gip_real_time_feature (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_gip_real_time_feature_v2 (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_har_android_new (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_live_detect (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_live_video_prefetch (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_pitaya_foundation_fix (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_rec_real_feature (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_small_video_ui_enhance (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_smart_select_snackbar (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_toutiao_cloud_feature_handler (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_toutiao_feed_ad_rerank (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_toutiao_ohr_android (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_video_preload (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_video_preload_detail (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_video_special_card (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_video_tab (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE DatabaseCache_video_tab_preload (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER              DEFAULT 0,owner            TEXT        NOT NULL,business         TEXT        NOT NULL,version          TEXT        NOT NULL,model_name       TEXT,model_version    TEXT,input_data       TEXT,predict          INTEGER,label            INTEGER,permission       INTEGER     NOT NULL DEFAULT 0,tag              TEXT,arg0             TEXT,arg1             TEXT,arg2             TEXT,arg3             TEXT,arg4             TEXT,arg5             TEXT,arg6             TEXT,arg7             TEXT,arg8             TEXT,arg9             TEXT);
CREATE TABLE FEInternalAppLogConfigTable (id              INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,business_name   TEXT        NOT NULL,package_version TEXT        NOT NULL,table_name      TEXT        NOT NULL,config_md5      TEXT        NOT NULL);
CREATE TABLE FEInternalAppSessionTable (id                 INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp          INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms       INTEGER     DEFAULT 0,session            TEXT        NOT NULL,event_name         TEXT        NOT NULL,is_launch          INTEGER,enter_timestamp    INTEGER,enter_timestamp_ms INTEGER,duration           INTEGER);
CREATE TABLE FEInternalDatabaseCacheConfigTable (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,business         TEXT        NOT NULL UNIQUE,table_name       TEXT        NOT NULL UNIQUE,feature_config   TEXT);
CREATE TABLE FEInternalFeatureMigrationTable (id              INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,kv_store_down   INTEGER,db_store_down   INTEGER);
CREATE TABLE FEInternalFeatureSchemaConfigTable (business_name   TEXT        NOT NULL PRIMARY KEY,table_name      TEXT        NOT NULL);
CREATE TABLE FEInternalFeatureStoreKVTable (group_name      TEXT        DEFAULT "",feature_name    TEXT        NOT NULL,feature_type    INTEGER     NOT NULL,value_type      INTEGER     NOT NULL,detail_index    INTEGER     NOT NULL,numic_value     REAL        NOT NULL,string_value    TEXT        NOT NULL,ext1            TEXT        ,ext2            TEXT        ,ext3            TEXT        ,ext4            TEXT        ,ext5            TEXT        ,timestamp       INTEGER     NOT NULL DEFAULT (strftime('%s','now')),UNIQUE(feature_name, feature_type, value_type, detail_index) ON CONFLICT REPLACE);
CREATE TABLE FEInternalFeatureStoreSeqTable (group_name      TEXT        DEFAULT "",feature_name    TEXT        NOT NULL,feature_type    INTEGER     NOT NULL,value_type      INTEGER     NOT NULL,detail_index    INTEGER     NOT NULL,numic_value     REAL        NOT NULL,string_value    TEXT        NOT NULL,ext1            TEXT        ,ext2            TEXT        ,ext3            TEXT        ,ext4            TEXT        ,ext5            TEXT        ,timestamp       INTEGER     NOT NULL DEFAULT (strftime('%s','now')),UNIQUE(feature_name, feature_type, value_type, detail_index) ON CONFLICT REPLACE);
CREATE TABLE FEInternalFeatureStoreSessionTable (group_name      TEXT        DEFAULT "",feature_name    TEXT        NOT NULL,sub_feature_name    TEXT    NOT NULL,feature_type    INTEGER     NOT NULL,value_type      INTEGER     NOT NULL,session_index   INTEGER     NOT NULL,detail_index    INTEGER     NOT NULL,numic_value     REAL        NOT NULL,string_value    TEXT        NOT NULL,ext1            TEXT        ,ext2            TEXT        ,ext3            TEXT        ,ext4            TEXT        ,ext5            TEXT        ,timestamp       INTEGER     NOT NULL DEFAULT (strftime('%s','now')),UNIQUE(group_name, feature_name, sub_feature_name, feature_type, value_type, session_index, detail_index) ON CONFLICT REPLACE);
CREATE TABLE FEInternalKVCacheConfigTable (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,business         TEXT        NOT NULL UNIQUE,table_name       TEXT        NOT NULL UNIQUE);
CREATE TABLE FEInternalUserActivityTable (id                  INTEGER         NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp           INTEGER         NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms        INTEGER         DEFAULT 0,start_timestamp_ms  INTEGER         NOT NULL,end_timestamp_ms    INTEGER         NOT NULL,open_app_count      INTEGER         NOT NULL,launch_hour_0 INTEGER NOT NULL,launch_hour_1 INTEGER NOT NULL,launch_hour_2 INTEGER NOT NULL,launch_hour_3 INTEGER NOT NULL,launch_hour_4 INTEGER NOT NULL,launch_hour_5 INTEGER NOT NULL,launch_hour_6 INTEGER NOT NULL,launch_hour_7 INTEGER NOT NULL,launch_hour_8 INTEGER NOT NULL,launch_hour_9 INTEGER NOT NULL,launch_hour_10 INTEGER NOT NULL,launch_hour_11 INTEGER NOT NULL,launch_hour_12 INTEGER NOT NULL,launch_hour_13 INTEGER NOT NULL,launch_hour_14 INTEGER NOT NULL,launch_hour_15 INTEGER NOT NULL,launch_hour_16 INTEGER NOT NULL,launch_hour_17 INTEGER NOT NULL,launch_hour_18 INTEGER NOT NULL,launch_hour_19 INTEGER NOT NULL,launch_hour_20 INTEGER NOT NULL,launch_hour_21 INTEGER NOT NULL,launch_hour_22 INTEGER NOT NULL,launch_hour_23 INTEGER NOT NULL,total_duration INTEGER NOT NULL);
CREATE TABLE FEInternalVersionTable (id               INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,timestamp        INTEGER     NOT NULL DEFAULT (strftime('%s','now')),timestamp_ms     INTEGER     DEFAULT 0,database_version INTEGER     NOT NULL);
CREATE TABLE FeatureSchema_douyin_rec_features (id integer primary key, event_name text not null, filter text integer null, insert_time integer not null, timestamp_ms integer not null, duration_string text, author_open_id_string text, timestamp_ms_string text, group_id_integer integer, group_id_string text, music_id_string text, host_enter_from_string text, item_duration_string text, aweme_type_string text);
CREATE TABLE FeatureSchema_gip_client_metrics (id integer primary key, event_name text not null, filter text integer null, insert_time integer not null, timestamp_ms integer not null, category_name_string text, log_extra_string text, value_integer integer);
CREATE TABLE FeatureSchema_gip_real_time_feature_v2 (id integer primary key, event_name text not null, filter text integer null, insert_time integer not null, timestamp_ms integer not null, IESLiveEffectAdTrackExtraServiceKey_string text, is_ec_live_integer integer, room_id_string text, refer_string text, commodity_id_string text, value_integer integer, creative_id_string text, anchor_id_string text, duration_integer integer, group_id_integer integer, log_pb_string text, stay_time_integer integer, log_extra_string text, product_id_string text, content_type_string text, value_string text, group_id_string text, category_string text, article_type_string text);
CREATE TABLE FeatureSchema_rec_real_feature (id integer primary key, event_name text not null, filter text integer null, insert_time integer not null, timestamp_ms integer not null);
CREATE TABLE FeatureSchema_smart_select_snackbar (id integer primary key, event_name text not null, filter text integer null, insert_time integer not null, timestamp_ms integer not null, user_type_integer integer, bubble_type_string text);
CREATE TABLE FeatureSchema_toutiao_feed_ad_rerank (id integer primary key, event_name text not null, filter text integer null, insert_time integer not null, timestamp_ms integer not null, value_integer integer, ad_extra_data_string text, log_extra_string text);
CREATE TABLE FeatureSchema_video_special_card (id integer primary key, event_name text not null, filter text integer null, insert_time integer not null, timestamp_ms integer not null, max_percent_float real, enter_from_string text, list_entrance_string text, card_type_string text, duration_integer integer);
CREATE TABLE KeyValueCache_item_feature_set (key                    TEXT        NOT NULL,value                  TEXT        NOT NULL,modification_time      integer,last_access_time       integer,primary key(key));
CREATE TABLE KeyValueCache_live_video_prefetch (key                    TEXT        NOT NULL,value                  TEXT        NOT NULL,modification_time      integer,last_access_time       integer,primary key(key));
CREATE TABLE KeyValueCache_smart_select_snackbar (key                    TEXT        NOT NULL,value                  TEXT        NOT NULL,modification_time      integer,last_access_time       integer,primary key(key));
CREATE TABLE KeyValueCache_toutiao_feed_ad_rerank (key                    TEXT        NOT NULL,value                  TEXT        NOT NULL,modification_time      integer,last_access_time       integer,primary key(key));
CREATE TABLE KeyValueCache_video_preload (key                    TEXT        NOT NULL,value                  TEXT        NOT NULL,modification_time      integer,last_access_time       integer,primary key(key));
CREATE TABLE KeyValueCache_video_preload_detail (key                    TEXT        NOT NULL,value                  TEXT        NOT NULL,modification_time      integer,last_access_time       integer,primary key(key));
CREATE TABLE KeyValueCache_video_tab (key                    TEXT        NOT NULL,value                  TEXT        NOT NULL,modification_time      integer,last_access_time       integer,primary key(key));
CREATE TABLE KeyValueCache_video_tab_preload (key                    TEXT        NOT NULL,value                  TEXT        NOT NULL,modification_time      integer,last_access_time       integer,primary key(key));
CREATE INDEX AppLog_frequency_control_42299_Index_V2 ON AppLog_frequency_control (event_name, timestamp_ms);
CREATE INDEX AppLog_live_video_prefetch_30782_Index_V2 ON AppLog_live_video_prefetch (event_name, timestamp_ms);
CREATE INDEX AppLog_multi_instance_3207_Index_V2 ON AppLog_multi_instance (event_name, timestamp_ms);
CREATE INDEX AppLog_tomato_wind_vane_refresh_27990_Index_V2 ON AppLog_tomato_wind_vane_refresh (event_name, timestamp_ms);
CREATE INDEX AppLog_video_preload_34407_Index_V2 ON AppLog_video_preload (event_name, timestamp_ms);
CREATE INDEX AppLog_video_tab_34374_Index_V2 ON AppLog_video_tab (event_name, timestamp_ms);
CREATE INDEX AppLog_video_tab_preload_34262_Index_V2 ON AppLog_video_tab_preload (event_name, timestamp_ms);
CREATE INDEX DatabaseCache_douyin_rec_features_Index ON DatabaseCache_douyin_rec_features (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_gip_client_metrics_Index ON DatabaseCache_gip_client_metrics (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_gip_real_time_feature_Index ON DatabaseCache_gip_real_time_feature (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_gip_real_time_feature_v2_Index ON DatabaseCache_gip_real_time_feature_v2 (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_har_android_new_Index ON DatabaseCache_har_android_new (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_live_detect_Index ON DatabaseCache_live_detect (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_live_video_prefetch_Index ON DatabaseCache_live_video_prefetch (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_pitaya_foundation_fix_Index ON DatabaseCache_pitaya_foundation_fix (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_rec_real_feature_Index ON DatabaseCache_rec_real_feature (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_small_video_ui_enhance_Index ON DatabaseCache_small_video_ui_enhance (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_smart_select_snackbar_Index ON DatabaseCache_smart_select_snackbar (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_toutiao_cloud_feature_handler_Index ON DatabaseCache_toutiao_cloud_feature_handler (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_toutiao_feed_ad_rerank_Index ON DatabaseCache_toutiao_feed_ad_rerank (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_toutiao_ohr_android_Index ON DatabaseCache_toutiao_ohr_android (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_video_preload_Index ON DatabaseCache_video_preload (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_video_preload_detail_Index ON DatabaseCache_video_preload_detail (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_video_special_card_Index ON DatabaseCache_video_special_card (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_video_tab_Index ON DatabaseCache_video_tab (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX DatabaseCache_video_tab_preload_Index ON DatabaseCache_video_tab_preload (label, tag, arg0, arg1, arg2, permission, timestamp);
CREATE INDEX FeatureSchema_douyin_rec_features_index ON FeatureSchema_douyin_rec_features (event_name, filter, timestamp_ms);
CREATE INDEX FeatureSchema_gip_client_metrics_index ON FeatureSchema_gip_client_metrics (event_name, filter, timestamp_ms);
CREATE INDEX FeatureSchema_gip_real_time_feature_v2_index ON FeatureSchema_gip_real_time_feature_v2 (event_name, filter, timestamp_ms);
CREATE INDEX FeatureSchema_rec_real_feature_index ON FeatureSchema_rec_real_feature (event_name, filter, timestamp_ms);
CREATE INDEX FeatureSchema_smart_select_snackbar_index ON FeatureSchema_smart_select_snackbar (event_name, filter, timestamp_ms);
CREATE INDEX FeatureSchema_toutiao_feed_ad_rerank_index ON FeatureSchema_toutiao_feed_ad_rerank (event_name, filter, timestamp_ms);
CREATE INDEX FeatureSchema_video_special_card_index ON FeatureSchema_video_special_card (event_name, filter, timestamp_ms);
CREATE INDEX applogConfigIndex ON FEInternalAppLogConfigTable (business_name, package_version, table_name);

-- ===== 92585279158_im.db =====
CREATE TABLE attchment (uuid TEXT NOT NULL,local_uri TEXT,remote_uri TEXT,size BIGINT,type TEXT,hash TEXT,position INTEGER,status INTEGER,ext TEXT,display_type TEXT,mime_type TEXT,upload_uri TEXT);
CREATE TABLE conversation_core (conversation_id TEXT PRIMARY KEY,info_version BIGINT,name TEXT,desc TEXT,icon TEXT,notice TEXT,owner_id INTEGER DEFAULT -1,sec_owner TEXT,silent INTEGER DEFAULT 0,silent_normal_only INTEGER DEFAULT 0,mode INTEGER DEFAULT -1,ext TEXT);
CREATE TABLE conversation_kv(conv_id TEXT,key TEXT,value TEXT,primary key(conv_id,key));
CREATE TABLE conversation_list (conversation_id TEXT PRIMARY KEY,short_id BIGINT,type INTEGER,last_msg_index BIGINT,updated_time INTEGER,unread_count INTEGER,read_index BIGINT,inbox INTEGER,min_index BIGINT,drafted_time INTEGER,ticket TEXT,draft_content TEXT,local_info TEXT,is_member INTEGER,has_more INTEGER,member_count INTEGER,status INTEGER,participant TEXT,last_msg_order_index BIGINT,stranger INTEGER default 0,sort_order INTEGER,min_index_v2 BIGINT,max_index_v2 BIGINT,read_index_v2 BIGINT,badge_count INTEGER,read_badge_count INTEGER,is_in_box INTEGER DEFAULT 0,unread_count_wl INTEGER DEFAULT 0);
CREATE TABLE conversation_setting (conversation_id TEXT PRIMARY KEY,info_version BIGINT,stick_top INTEGER,mute INTEGER,ext TEXT,favor INTEGER,set_top_time BIGINT,set_favorite_time BIGINT,push_status INTEGER DEFAULT 1);
CREATE TABLE conversation_tag(conv_id TEXT,tag_id INTEGER,tag_type INTEGER);
CREATE TABLE mention(uuid TEXT PRIMARY KEY,conversation_id TEXT NOT NULL,ids_str TEXT,sender_id BIGINT,created_time INTEGER);
CREATE TABLE message_kv(uuid TEXT,key TEXT,value TEXT,primary key(uuid,key));
CREATE TABLE msg(msg_uuid TEXT PRIMARY KEY,msg_server_id BIGINT,conversation_id TEXT NOT NULL,conversation_short_id BIGINT,conversation_type INTEGER,type INTEGER,index_in_conversation BIGINT,order_index BIGINT,status INTEGER,net_status INTEGER,version INTEGER,deleted INTEGER,created_time INTEGER,sender BIGINT,content TEXT,ext TEXT,local_info TEXT,read_status INTEGER,sec_sender TEXT,property_list TEXT,index_in_conversation_v2 BIGINT default -1,table_flag BIGINT default 0);
CREATE TABLE msg_property_new(msg_uuid TEXT,conversation_id TEXT NOT NULL,key TEXT,idempotent_id TEXT,sender INTEGER,sender_sec TEXT,create_time INTEGER,value TEXT,deleted INTEGER,version INTEGER,status INTEGER,PRIMARY KEY(msg_uuid,key,idempotent_id));
CREATE TABLE participant(user_id INTEGER NOT NULL,sort_order INTEGER,role INTEGER,conversation_id TEXT,alias TEXT,sec_uid TEXT,silent INTEGER,silent_time INTEGER,ext TEXT);
CREATE TABLE participant_read(user_id INTEGER NOT NULL,conversation_id TEXT,min_index INTEGER,read_index INTEGER,read_order INTEGER);
CREATE INDEX CONVERSATION_INDEX ON msg(conversation_id,index_in_conversation);
CREATE INDEX MEMBER_CONVERSATION_INDEX on participant(conversation_id);
CREATE INDEX MSG_UUID_INDEX ON msg(msg_uuid);
CREATE INDEX UID_INDEX ON msg(msg_server_id);
CREATE INDEX USER_ID_INDEX on participant(user_id);
CREATE INDEX attchment_index on attchment(uuid);
CREATE INDEX conv_tag_id_index ON conversation_tag( conv_id, tag_id );
CREATE INDEX id_index on conversation_kv(conv_id);
CREATE INDEX msg_ky_id_index on message_kv(uuid);
CREATE INDEX msg_ky_key_index on message_kv(key);

-- ===== TemplateTagRelation.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE template_db (
     _id INTEGER PRIMARY KEY,
     template_id TEXT,
     template_tag TEXT,
     template_key TEXT,
     template_expire_time INTEGER NOT NULL,
     template_request_key TEXT );

-- ===== ad_res_preload.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE preload_record (res_id INTEGER PRIMARY KEY,expired_time INTEGER NOT NULL DEFAULT 0,res_url VARCHAR );

-- ===== alive_monitor.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE process_start_info ( _id INTEGER PRIMARY KEY AUTOINCREMENT, data_json TEXT, end_time INTEGER );

-- ===== bd_sync_sdk_v4.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
CREATE TABLE `t_business` (`id` INTEGER NOT NULL, `consume_type` INTEGER, `bucket` INTEGER, PRIMARY KEY(`id`));
CREATE TABLE `t_history_synclog` (`sync_id` TEXT NOT NULL, `did` TEXT, `uid` TEXT, `sync_cursor` INTEGER NOT NULL, `data` BLOB, `md5` TEXT, `business` INTEGER NOT NULL, `consume_type` INTEGER, `data_type` INTEGER, `publish_ts` INTEGER NOT NULL, `receive_ts` INTEGER NOT NULL, `bucket` INTEGER, `req_id` TEXT, `topic_type` INTEGER, `packet_status` INTEGER, `expire_ts` INTEGER NOT NULL, `packet_ctrl` INTEGER NOT NULL, `extra` TEXT, PRIMARY KEY(`sync_id`, `sync_cursor`));
CREATE TABLE `t_report_synclog` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `sync_id` TEXT, `business` INTEGER NOT NULL, `did` TEXT, `uid` TEXT, `bucket` INTEGER, `cursor` INTEGER NOT NULL, `data` BLOB, `md5` TEXT, `msg_id` TEXT);
CREATE TABLE `t_snapshot` (`sync_id` TEXT NOT NULL, `business` INTEGER NOT NULL, `uid` TEXT, `did` TEXT, `cursor` INTEGER NOT NULL, `data` BLOB, `notified` INTEGER NOT NULL, `bucket` INTEGER, `data_type` INTEGER, `publish_ts` INTEGER NOT NULL, `receive_ts` INTEGER NOT NULL, `consume_type` INTEGER, `patch_cnt` INTEGER NOT NULL, PRIMARY KEY(`sync_id`, `business`));
CREATE TABLE `t_sync_cursor` (`sync_id` TEXT NOT NULL, `did` TEXT, `uid` TEXT, `topic_type` INTEGER, `bucket` INTEGER, `recv_cursor` INTEGER NOT NULL, `report_cursor` INTEGER NOT NULL, PRIMARY KEY(`sync_id`));
CREATE TABLE `t_synclog` (`sync_id` TEXT NOT NULL, `did` TEXT, `uid` TEXT, `sync_cursor` INTEGER NOT NULL, `data` BLOB, `md5` TEXT, `business` INTEGER NOT NULL, `consume_type` INTEGER, `data_type` INTEGER, `publish_ts` INTEGER NOT NULL, `receive_ts` INTEGER NOT NULL, `bucket` INTEGER, `req_id` TEXT, `topic_type` INTEGER NOT NULL, `packet_status` INTEGER NOT NULL, `expire_ts` INTEGER NOT NULL, `packet_ctrl` INTEGER NOT NULL, `extra` TEXT, PRIMARY KEY(`sync_id`, `sync_cursor`));

-- ===== downloader.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE downloader( _id INTEGER PRIMARY KEY, url TEXT, savePath TEXT, tempPath TEXT, name TEXT, chunkCount INTEGER, status INTEGER, curBytes INTEGER, totalBytes INTEGER, eTag TEXT, onlyWifi INTEGER, force INTEGER, retryCount INTEGER, extra TEXT, mimeType TEXT, title TEXT, notificationEnable INTEGER, notificationVisibility INTEGER, isFirstDownload INTEGER, isFirstSuccess INTEGER, needHttpsToHttpRetry INTEGER, downloadTime INTEGER, packageName TEXT, md5 TEXT, retryDelay INTEGER, curRetryTime INTEGER, retryDelayStatus INTEGER, defaultHttpServiceBackUp INTEGER, chunkRunnableReuse INTEGER, retryDelayTimeArray TEXT, chunkDowngradeRetry INTEGER, backUpUrlsStr TEXT, backUpUrlRetryCount INTEGER, realDownloadTime INTEGER, retryScheduleMinutes INTEGER, independentProcess INTEGER, auxiliaryJsonobjectString TEXT, iconUrl TEXT, appVersionCode INTEGER, taskId TEXT, downloadStartTimeStamp INTEGER, downloadFinishTimeStamp INTEGER, installedTimeStamp INTEGER, hasDoInstallation INTEGER, cacheLifeTimeMax INTEGER, pcdnUrlsStr TEXT, cdnUrlsStr TEXT, backCurBytes INTEGER, realBackDownloadTime INTEGER, monitorScene TEXT);
CREATE TABLE segments( _id INTEGER PRIMARY KEY,info TEXT );

-- ===== fangqing.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE videomodel(vid TEXT PRIMARY KEY,videomodel TEXT,time INTEGER);

-- ===== global_component.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE `component_record` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `uid` INTEGER NOT NULL, `component_id` TEXT NOT NULL, `component_type` TEXT NOT NULL, `state` INTEGER NOT NULL, `timestamp` INTEGER NOT NULL, `scene` TEXT NOT NULL, `extra` TEXT, `report_status` INTEGER NOT NULL);
CREATE TABLE `resource_registry` (`id` TEXT NOT NULL, `biz_id` TEXT NOT NULL, `name` TEXT NOT NULL, `type` TEXT NOT NULL, `is_server_record` INTEGER NOT NULL, `tags` TEXT NOT NULL, `strategies` TEXT NOT NULL, `trigger` TEXT NOT NULL, `scene` TEXT NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE `resource_strategy` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `type` TEXT NOT NULL, `target_range` TEXT NOT NULL, `white_range` TEXT NOT NULL, `data` TEXT NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
CREATE INDEX `biz_id_index` ON `resource_registry` (`biz_id`);

-- ===== impression_kmp.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE impression_entity (impression_id TEXT,impression_type INTEGER,time INTEGER,duration INTEGER,max_duration INTEGER,extra TEXT,key_name TEXT,list_type INTEGER,group_extra TEXT, PRIMARY KEY(impression_id, key_name, list_type));

-- ===== learning.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE play_stat (auto_id INTEGER PRIMARY KEY AUTOINCREMENT,item_id VARCHAR,start_duration INTEGER NOT NULL DEFAULT 0,end_duration INTEGER NOT NULL DEFAULT 0,start_time INTEGER NOT NULL DEFAULT 0,end_time INTEGER NOT NULL DEFAULT 0,play_scene_type INTEGER NOT NULL DEFAULT 0 );

-- ===== mc_ua.db =====
CREATE TABLE __sd(id INTEGER primary key autoincrement, __ii TEXT unique, __e TEXT, __f TEXT, __g TEXT);
CREATE TABLE android_metadata (locale TEXT);

-- ===== news_article.db =====
CREATE TABLE `action_net_request` (`key` TEXT NOT NULL, `type` INTEGER NOT NULL, `time` INTEGER NOT NULL, `url` TEXT NOT NULL, `request_method` INTEGER NOT NULL, `entity_data` TEXT, `extra_data` TEXT, `retry_count` INTEGER NOT NULL, PRIMARY KEY(`key`, `type`, `time`));
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE `article` (`ad_id` INTEGER NOT NULL, `share_info` TEXT, `ext_json` TEXT, `max_behot_time` INTEGER NOT NULL, `image_list` TEXT NOT NULL, `large_image_json` TEXT NOT NULL, `middle_image_json` TEXT NOT NULL, `article_source` INTEGER NOT NULL, `in_offline_pool` INTEGER NOT NULL, `offline_pool_client_show` INTEGER NOT NULL, `offline_pool_server_impression_upload` INTEGER NOT NULL, `offline_pool_download_status` INTEGER NOT NULL, `key` TEXT NOT NULL, `tag` TEXT, `behot_time` INTEGER NOT NULL, `share_url` TEXT, `comment_count` INTEGER NOT NULL, `digg_count` INTEGER NOT NULL, `bury_count` INTEGER NOT NULL, `repin_count` INTEGER NOT NULL, `like_count` INTEGER NOT NULL, `is_user_digg` INTEGER NOT NULL, `is_user_bury` INTEGER NOT NULL, `is_user_repin` INTEGER NOT NULL, `is_user_like` INTEGER NOT NULL, `user_repin_time` INTEGER NOT NULL, `stats_timestamp` INTEGER NOT NULL, `read_timestamp` INTEGER NOT NULL, `is_user_dislike` INTEGER NOT NULL, `is_ban_comment` INTEGER NOT NULL, `share_count` INTEGER NOT NULL, `group_id` INTEGER NOT NULL, `item_id` INTEGER NOT NULL, `aggr_type` INTEGER NOT NULL, PRIMARY KEY(`group_id`, `item_id`, `ad_id`));
CREATE TABLE `article_detail` (`group_id` INTEGER NOT NULL, `item_id` INTEGER NOT NULL, `aggr_type` INTEGER NOT NULL, `content` TEXT, `timestamp` INTEGER NOT NULL, `expire_seconds` INTEGER NOT NULL, `cache_token` TEXT, `image_detail_json` TEXT, `thumb_image_json` TEXT, `ext_json` TEXT, `serial_data_json` TEXT, `webp_thumb_image_json` TEXT, `webp_image_detail_json` TEXT, `title_image_json` TEXT, `trans_to_native` INTEGER NOT NULL, `article_version` INTEGER NOT NULL, `cell_index` INTEGER NOT NULL, `content_hash` TEXT, PRIMARY KEY(`group_id`, `item_id`));
CREATE TABLE `audio_percent_record` (`user_Id` INTEGER NOT NULL, `group_id` INTEGER NOT NULL, `book_id` INTEGER NOT NULL, `percent` REAL NOT NULL, `position` INTEGER NOT NULL, PRIMARY KEY(`group_id`, `user_Id`));
CREATE TABLE `category_refresh_record` (`category` TEXT NOT NULL, `last_refresh_time` INTEGER NOT NULL, `last_load_more_time` INTEGER NOT NULL, `top_time` INTEGER NOT NULL, `bottom_time` INTEGER NOT NULL, `new_last_refresh_time` INTEGER NOT NULL, `new_last_refresh_count` INTEGER NOT NULL, `last_refresh_count` INTEGER NOT NULL, `last_response_extra` TEXT NOT NULL, `top_order_id` INTEGER NOT NULL, `bottom_order_id` INTEGER NOT NULL, PRIMARY KEY(`category`));
CREATE TABLE `cell_ref` (`category` TEXT NOT NULL, `cell_type` INTEGER NOT NULL, `cell_data` TEXT NOT NULL, `cursor` INTEGER NOT NULL, `behot_time` INTEGER NOT NULL, `share_url` TEXT, `share_info` TEXT, `open_url` TEXT, `image_list` TEXT, `large_image_json` TEXT, `middle_image_json` TEXT, `comments_json` TEXT, `video_cover_aspect_ratio` REAL NOT NULL, `video_detail_cover_aspect_ratio` REAL NOT NULL, `stick_style` INTEGER NOT NULL, `impression` INTEGER NOT NULL, `in_offline_pool` INTEGER NOT NULL, `key` TEXT NOT NULL, `cell_order_id` INTEGER NOT NULL, `data_type` INTEGER NOT NULL, `cell_data_pb` BLOB, `share_info_pb` BLOB, `image_list_pb` BLOB, `large_image_pb` BLOB, `middle_image_pb` BLOB, PRIMARY KEY(`category`, `key`, `cell_type`));
CREATE TABLE `city` (`name` TEXT NOT NULL, `pinyin` TEXT NOT NULL, `code` TEXT NOT NULL, `province` TEXT NOT NULL, `districts` TEXT NOT NULL, PRIMARY KEY(`name`));
CREATE TABLE `impression` (`key_name` TEXT NOT NULL, `list_type` INTEGER NOT NULL, `session_id` INTEGER NOT NULL, `impression` TEXT, `extra` TEXT, PRIMARY KEY(`key_name`, `list_type`, `session_id`));
CREATE TABLE `item_action_v2` (`group_id` INTEGER NOT NULL, `item_id` INTEGER NOT NULL, `aggr_type` INTEGER NOT NULL, `action` INTEGER NOT NULL, `timestamp` INTEGER NOT NULL, PRIMARY KEY(`group_id`, `item_id`, `action`));
CREATE TABLE `item_action_v3` (`group_id` INTEGER NOT NULL, `item_id` INTEGER NOT NULL, `aggr_type` INTEGER NOT NULL, `action` TEXT NOT NULL, `type` INTEGER NOT NULL, `timestamp` INTEGER NOT NULL, `extra_data` TEXT, PRIMARY KEY(`group_id`, `item_id`, `action`));
CREATE TABLE `post` (`title` TEXT, `content` TEXT, `schema` TEXT, `comment_schema` TEXT, `article_url` TEXT, `inner_ui_flag` INTEGER NOT NULL, `post_large_image_json` TEXT, `thumb_image_json` TEXT, `forum_json` TEXT, `user_json` TEXT, `friend_digg_list_json` TEXT, `comments_json` TEXT, `group_json` TEXT, `position_json` TEXT, `action_bar_json` TEXT, `score` REAL NOT NULL, `create_time` INTEGER NOT NULL, `comment_time` INTEGER NOT NULL, `product_list` TEXT NOT NULL, `attach_card_info` TEXT NOT NULL, `post_origin_image_json` TEXT NOT NULL, `display_attach_card` INTEGER NOT NULL, `vote_info` TEXT NOT NULL, `video_link_card` TEXT NOT NULL, `key` TEXT NOT NULL, `tag` TEXT, `behot_time` INTEGER NOT NULL, `share_url` TEXT, `comment_count` INTEGER NOT NULL, `digg_count` INTEGER NOT NULL, `bury_count` INTEGER NOT NULL, `repin_count` INTEGER NOT NULL, `like_count` INTEGER NOT NULL, `is_user_digg` INTEGER NOT NULL, `is_user_bury` INTEGER NOT NULL, `is_user_repin` INTEGER NOT NULL, `is_user_like` INTEGER NOT NULL, `user_repin_time` INTEGER NOT NULL, `stats_timestamp` INTEGER NOT NULL, `read_timestamp` INTEGER NOT NULL, `is_user_dislike` INTEGER NOT NULL, `is_ban_comment` INTEGER NOT NULL, `share_count` INTEGER NOT NULL, `group_id` INTEGER NOT NULL, `item_id` INTEGER NOT NULL, `aggr_type` INTEGER NOT NULL, PRIMARY KEY(`group_id`, `item_id`));
CREATE TABLE `relation_schedule` (`user_id` INTEGER NOT NULL, `device_id` TEXT NOT NULL, `self_user_id` INTEGER NOT NULL, `id_type` INTEGER NOT NULL, `relationship` INTEGER NOT NULL, `time` INTEGER NOT NULL, PRIMARY KEY(`user_id`, `device_id`, `self_user_id`));
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
CREATE TABLE `search_hint` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `word` TEXT NOT NULL, `group_id` TEXT NOT NULL, `recommend_reason` TEXT, `type` INTEGER NOT NULL);
CREATE TABLE `search_word` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `type` INTEGER NOT NULL, `search_word` TEXT NOT NULL, `timestamp` INTEGER NOT NULL, `search_ad_extra` TEXT, `uid` INTEGER NOT NULL);
CREATE TABLE `tiktok_video_cache` (`item_id` INTEGER NOT NULL, `local_path` TEXT, `width` INTEGER NOT NULL, `height` INTEGER NOT NULL, PRIMARY KEY(`item_id`));
CREATE TABLE `video_history` (`user_id` INTEGER NOT NULL, `content_id` INTEGER NOT NULL, `item_id` INTEGER NOT NULL, `percent` INTEGER NOT NULL, `date` INTEGER NOT NULL, `position` INTEGER NOT NULL, `offset` INTEGER NOT NULL, `type` INTEGER NOT NULL, PRIMARY KEY(`content_id`, `user_id`, `item_id`));
CREATE INDEX `index_article_behot_time` ON `article` (`behot_time`);
CREATE INDEX `index_article_in_offline_pool` ON `article` (`in_offline_pool`);
CREATE INDEX `index_article_key_is_user_dislike_in_offline_pool` ON `article` (`key`, `is_user_dislike`, `in_offline_pool`);
CREATE INDEX `index_article_max_behot_time` ON `article` (`max_behot_time`);
CREATE INDEX `index_cell_ref_category_behot_time_cursor` ON `cell_ref` (`category`, `behot_time`, `cursor`);
CREATE INDEX `index_cell_ref_category_cell_type_behot_time_cursor` ON `cell_ref` (`category`, `cell_type`, `behot_time`, `cursor`);
CREATE INDEX `index_cell_ref_category_cell_type_cell_order_id_key` ON `cell_ref` (`category`, `cell_type`, `cell_order_id`, `key`);
CREATE INDEX `index_post_key_is_user_dislike` ON `post` (`key`, `is_user_dislike`);
CREATE UNIQUE INDEX `index_relation_schedule_user_id_device_id_id_type` ON `relation_schedule` (`user_id`, `device_id`, `id_type`);
CREATE UNIQUE INDEX `index_relation_schedule_user_id_self_user_id_id_type` ON `relation_schedule` (`user_id`, `self_user_id`, `id_type`);
CREATE UNIQUE INDEX `index_search_word_type_search_word` ON `search_word` (`type`, `search_word`);
CREATE UNIQUE INDEX `index_video_history_content_id_user_id_item_id` ON `video_history` (`content_id`, `user_id`, `item_id`);

-- ===== news_kmp.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE cell_entity(order_id INTEGER, group_id TEXT, raw_data TEXT, stick_style INTEGER, channel TEXT, read_time INTEGER, user_id INTEGER, PRIMARY KEY(channel, order_id));
CREATE TABLE refresh_record(channel_id TEXT PRIMARY KEY,recent_refresh_time INTEGER,recent_load_more_time INTEGER,top_time INTEGER,bottom_time INTEGER,recent_refresh_count INTEGER,top_order_id INTEGER,bottom_order_id INTEGER);

-- ===== push_message.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE message ( message_id BIGINT PRIMARY KEY, arrive_time BIGINT, client_intelligence_expire_time BIGINT, sender INT,handle_by_sdk INT,has_been_shown INT,push_body TEXT );

-- ===== sm_event.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE event ( _id INTEGER PRIMARY KEY AUTOINCREMENT, event TEXT, params TEXT );

-- ===== ss_push_monitor.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE event ( _id INTEGER PRIMARY KEY AUTOINCREMENT, service_name VARCHAR, category VARCHAR, metric VARCHAR, extra VARCHAR );

-- ===== verifystorage.db =====
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE h5_storage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    primary_key TEXT,
    time_stamp LONG, 
    content TEXT
    );

