#!/usr/bin/env node
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { assertProtocolCompatible } from "../src/compatibility.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(root, "..", "..");
const schemaPath = resolve(root, "schema", "cc-agent-protocol.schema.json");
const baselinePath = resolve(root, "schema", "baselines", "v1.json");
const schemaText = readFileSync(schemaPath, "utf8");
const schema = JSON.parse(schemaText);
const digest = `sha256:${createHash("sha256").update(schemaText).digest("hex")}`;
const protocol = schema["x-cc-protocol"];
const checkOnly = process.argv.includes("--check");
const freezeBaseline = process.argv.includes("--freeze-baseline");

if (freezeBaseline) {
  mkdirSync(dirname(baselinePath), { recursive: true });
  writeFileSync(baselinePath, `${JSON.stringify(schema, null, 2)}\n`, "utf8");
  console.error(`Wrote ${baselinePath}`);
}
if (existsSync(baselinePath)) {
  assertProtocolCompatible(
    JSON.parse(readFileSync(baselinePath, "utf8")),
    schema,
  );
}

function refName(value) {
  return value.replace("#/$defs/", "");
}

function tsType(node = {}) {
  if (node.$ref) return refName(node.$ref);
  if (Object.hasOwn(node, "const")) return JSON.stringify(node.const);
  if (node.enum)
    return node.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (node.oneOf) return node.oneOf.map(tsType).join(" | ");
  if (node.anyOf) return node.anyOf.map(tsType).join(" | ");
  if (node.allOf)
    return node.allOf.map((part) => `(${tsType(part)})`).join(" & ");
  if (Array.isArray(node.type))
    return node.type.map((type) => tsType({ ...node, type })).join(" | ");
  if (node.type === "null") return "null";
  if (node.type === "boolean") return "boolean";
  if (node.type === "number" || node.type === "integer") return "number";
  if (node.type === "string") return "string";
  if (node.type === "array") return `Array<${tsType(node.items || {})}>`;
  if (node.type === "object" || node.properties || node.additionalProperties) {
    const required = new Set(node.required || []);
    const properties = Object.entries(node.properties || {}).map(
      ([name, value]) =>
        `${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${tsType(value)};`,
    );
    if (node.additionalProperties && node.additionalProperties !== false) {
      properties.push(`[key: string]: ${tsType(node.additionalProperties)};`);
    }
    return `{ ${properties.join(" ")} }`;
  }
  return "unknown";
}

function renderTypeScript() {
  const types = Object.entries(schema.$defs)
    .map(([name, definition]) => `export type ${name} = ${tsType(definition)};`)
    .join("\n\n");
  return `/* AUTO-GENERATED by @chainlesschain/agent-protocol. DO NOT EDIT. */
export const CC_AGENT_PROTOCOL_VERSION = ${protocol.version} as const;
export const CC_AGENT_PROTOCOL_MIN_VERSION = ${protocol.minimumCompatibleVersion} as const;
export const CC_AGENT_PROTOCOL_SCHEMA_DIGEST = ${JSON.stringify(digest)} as const;
export const CC_AGENT_PROTOCOL_FEATURES = ${JSON.stringify(protocol.features)} as const;
export const CC_AGENT_PROTOCOL_SCHEMA = ${JSON.stringify(schema, null, 2)} as const;

export interface ProtocolValidationError { path: string; message: string }
export interface ProtocolValidationResult { ok: boolean; errors: ProtocolValidationError[] }

function matchesType(value: unknown, type: string): boolean {
  if (type === "null") return value === null;
  if (type === "array") return Array.isArray(value);
  if (type === "integer") return typeof value === "number" && Number.isSafeInteger(value);
  if (type === "number") return typeof value === "number" && Number.isFinite(value);
  if (type === "object") return value !== null && typeof value === "object" && !Array.isArray(value);
  return typeof value === type;
}

function validateNode(value: unknown, node: any, path: string, errors: ProtocolValidationError[], root: any): boolean {
  const start = errors.length;
  if (node.$ref) {
    const target = node.$ref.split("/").slice(1).reduce((current: any, part: string) => current?.[part.replaceAll("~1", "/").replaceAll("~0", "~")], root);
    if (!target) errors.push({ path, message: \`unresolved schema reference \${node.$ref}\` });
    else validateNode(value, target, path, errors, root);
    return errors.length === start;
  }
  if (Object.prototype.hasOwnProperty.call(node, "const") && JSON.stringify(value) !== JSON.stringify(node.const)) {
    errors.push({ path, message: \`must equal \${JSON.stringify(node.const)}\` });
  }
  if (node.enum && !node.enum.some((candidate: unknown) => JSON.stringify(candidate) === JSON.stringify(value))) {
    errors.push({ path, message: "must be an allowed enum value" });
  }
  for (const keyword of ["allOf"] as const) for (const child of node[keyword] || []) validateNode(value, child, path, errors, root);
  for (const keyword of ["oneOf", "anyOf"] as const) {
    if (!node[keyword]) continue;
    const matches = node[keyword].filter((child: any) => {
      const branchErrors: ProtocolValidationError[] = [];
      validateNode(value, child, path, branchErrors, root);
      return branchErrors.length === 0;
    }).length;
    if ((keyword === "oneOf" && matches !== 1) || (keyword === "anyOf" && matches < 1)) errors.push({ path, message: \`must match \${keyword}\` });
  }
  const types = Array.isArray(node.type) ? node.type : node.type ? [node.type] : [];
  if (types.length && !types.some((type: string) => matchesType(value, type))) {
    errors.push({ path, message: \`must be \${types.join(" or ")}\` });
    return false;
  }
  if (typeof value === "string") {
    if (node.minLength != null && value.length < node.minLength) errors.push({ path, message: \`must have length >= \${node.minLength}\` });
    if (node.maxLength != null && value.length > node.maxLength) errors.push({ path, message: \`must have length <= \${node.maxLength}\` });
    if (node.pattern && !new RegExp(node.pattern, "u").test(value)) errors.push({ path, message: "must match pattern" });
    if (node.format === "date-time" && Number.isNaN(Date.parse(value))) errors.push({ path, message: "must be an ISO date-time" });
  }
  if (typeof value === "number") {
    if (node.minimum != null && value < node.minimum) errors.push({ path, message: \`must be >= \${node.minimum}\` });
    if (node.maximum != null && value > node.maximum) errors.push({ path, message: \`must be <= \${node.maximum}\` });
  }
  if (Array.isArray(value)) {
    if (node.minItems != null && value.length < node.minItems) errors.push({ path, message: \`must contain >= \${node.minItems} items\` });
    if (node.maxItems != null && value.length > node.maxItems) errors.push({ path, message: \`must contain <= \${node.maxItems} items\` });
    if (node.uniqueItems && new Set(value.map((item) => JSON.stringify(item))).size !== value.length) errors.push({ path, message: "must contain unique items" });
    value.forEach((item, index) => validateNode(item, node.items || {}, \`\${path}/\${index}\`, errors, root));
  }
  if (value && typeof value === "object" && !Array.isArray(value)) {
    const record = value as Record<string, unknown>;
    for (const name of node.required || []) if (!Object.prototype.hasOwnProperty.call(record, name)) errors.push({ path: \`\${path}/\${name}\`, message: "is required" });
    for (const [name, child] of Object.entries(node.properties || {})) if (Object.prototype.hasOwnProperty.call(record, name)) validateNode(record[name], child, \`\${path}/\${name}\`, errors, root);
    const known = new Set(Object.keys(node.properties || {}));
    for (const [name, childValue] of Object.entries(record)) {
      if (known.has(name)) continue;
      if (node.additionalProperties === false) errors.push({ path: \`\${path}/\${name}\`, message: "additional property is not allowed" });
      else if (node.additionalProperties && typeof node.additionalProperties === "object") validateNode(childValue, node.additionalProperties, \`\${path}/\${name}\`, errors, root);
    }
  }
  return errors.length === start;
}

export function validateProtocolMessage(value: unknown): ProtocolValidationResult {
  const errors: ProtocolValidationError[] = [];
  validateNode(value, CC_AGENT_PROTOCOL_SCHEMA, "#", errors, CC_AGENT_PROTOCOL_SCHEMA);
  return { ok: errors.length === 0, errors };
}

export function validateProtocolDefinition(name: keyof typeof CC_AGENT_PROTOCOL_SCHEMA.$defs, value: unknown): ProtocolValidationResult {
  const errors: ProtocolValidationError[] = [];
  const definition = CC_AGENT_PROTOCOL_SCHEMA.$defs[name];
  if (!definition) return { ok: false, errors: [{ path: "#", message: \`unknown protocol definition \${String(name)}\` }] };
  validateNode(value, definition, "#", errors, CC_AGENT_PROTOCOL_SCHEMA);
  return { ok: errors.length === 0, errors };
}

export function validateApprovalDecision(value: unknown): ProtocolValidationResult {
  return validateProtocolDefinition("ApprovalDecision", value);
}

export function isApprovalDecision(value: unknown): value is ApprovalDecision {
  return validateApprovalDecision(value).ok;
}

export function assertApprovalDecision(value: unknown): asserts value is ApprovalDecision {
  const result = validateApprovalDecision(value);
  if (!result.ok) throw new TypeError(\`Invalid ApprovalDecision: \${result.errors.map((error) => \`\${error.path} \${error.message}\`).join("; ")}\`);
}

export function assertProtocolMessage(value: unknown): asserts value is ClientRequest | ClientResponse | ServerRequest | ServerNotification {
  const result = validateProtocolMessage(value);
  if (!result.ok) throw new TypeError(\`Invalid CC Agent protocol message: \${result.errors.map((error) => \`\${error.path} \${error.message}\`).join("; ")}\`);
}

${types}
`;
}

function pyType(node = {}, { quoteRefs = false } = {}) {
  if (node.$ref) {
    const name = refName(node.$ref);
    return quoteRefs ? JSON.stringify(name) : name;
  }
  if (Object.hasOwn(node, "const"))
    return `Literal[${JSON.stringify(node.const)}]`;
  if (node.enum)
    return `Literal[${node.enum.map((value) => JSON.stringify(value)).join(", ")}]`;
  if (node.oneOf || node.anyOf)
    return `Union[${(node.oneOf || node.anyOf)
      .map((child) => pyType(child, { quoteRefs }))
      .join(", ")}]`;
  if (node.allOf) return "Mapping[str, Any]";
  if (Array.isArray(node.type))
    return `Union[${node.type
      .map((type) => pyType({ ...node, type }, { quoteRefs }))
      .join(", ")}]`;
  if (node.type === "null") return "None";
  if (node.type === "boolean") return "bool";
  if (node.type === "integer") return "int";
  if (node.type === "number") return "float";
  if (node.type === "string") return "str";
  if (node.type === "array")
    return `Sequence[${pyType(node.items || {}, { quoteRefs })}]`;
  if (node.type === "object" || node.properties) return "Mapping[str, Any]";
  return "Any";
}

function renderPython() {
  const aliases = Object.entries(schema.$defs)
    .filter(
      ([, definition]) =>
        definition.type !== "object" && !definition.properties,
    )
    .map(
      ([name, definition]) =>
        `${name}: TypeAlias = ${pyType(definition, { quoteRefs: true })}`,
    )
    .join("\n");
  const typedDicts = Object.entries(schema.$defs)
    .filter(
      ([, definition]) => definition.type === "object" || definition.properties,
    )
    .map(([name, definition]) => {
      const required = new Set(definition.required || []);
      const fields = Object.entries(definition.properties || {});
      const renderFields = (entries) =>
        entries
          .map(
            ([field, child]) =>
              `        ${JSON.stringify(field)}: ${JSON.stringify(pyType(child))},`,
          )
          .join("\n");
      const requiredFields = renderFields(
        fields.filter(([field]) => required.has(field)),
      );
      const optionalFields = renderFields(
        fields.filter(([field]) => !required.has(field)),
      );
      return `_${name}Required = TypedDict(\n    ${JSON.stringify(`_${name}Required`)},\n    {\n${requiredFields}\n    },\n    total=True,\n)\n_${name}Optional = TypedDict(\n    ${JSON.stringify(`_${name}Optional`)},\n    {\n${optionalFields}\n    },\n    total=False,\n)\n\nclass ${name}(_${name}Required, _${name}Optional):\n    pass`;
    })
    .join("\n\n");
  return `# AUTO-GENERATED by @chainlesschain/agent-protocol. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime
import json
import re
from typing import Any, Literal, Mapping, Sequence, TypeAlias, TypedDict, Union

CC_AGENT_PROTOCOL_VERSION = ${protocol.version}
CC_AGENT_PROTOCOL_MIN_VERSION = ${protocol.minimumCompatibleVersion}
CC_AGENT_PROTOCOL_SCHEMA_DIGEST = ${JSON.stringify(digest)}
CC_AGENT_PROTOCOL_FEATURES = ${JSON.stringify(protocol.features)}
CC_AGENT_PROTOCOL_SCHEMA: Mapping[str, Any] = json.loads(${JSON.stringify(JSON.stringify(schema))})

def _matches_type(value: Any, expected: str) -> bool:
    if expected == "null":
        return value is None
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if expected == "string":
        return isinstance(value, str)
    if expected == "array":
        return isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray))
    if expected == "object":
        return isinstance(value, Mapping)
    return False

def _resolve_ref(root: Mapping[str, Any], reference: str) -> Any:
    if not reference.startswith("#/"):
        return None
    current: Any = root
    for raw_part in reference[2:].split("/"):
        part = raw_part.replace("~1", "/").replace("~0", "~")
        if not isinstance(current, Mapping) or part not in current:
            return None
        current = current[part]
    return current

def _validate_node(value: Any, node: Mapping[str, Any], path: str, errors: list[str], root: Mapping[str, Any]) -> None:
    reference = node.get("$ref")
    if isinstance(reference, str):
        target = _resolve_ref(root, reference)
        if not isinstance(target, Mapping):
            errors.append(f"{path} unresolved schema reference {reference}")
        else:
            _validate_node(value, target, path, errors, root)
        return
    if "const" in node and value != node["const"]:
        errors.append(f"{path} must equal {node['const']!r}")
    if "enum" in node and value not in node["enum"]:
        errors.append(f"{path} must be an allowed enum value")
    for child in node.get("allOf", ()):
        _validate_node(value, child, path, errors, root)
    for keyword in ("oneOf", "anyOf"):
        branches = node.get(keyword)
        if not branches:
            continue
        matches = 0
        for child in branches:
            branch_errors: list[str] = []
            _validate_node(value, child, path, branch_errors, root)
            if not branch_errors:
                matches += 1
        if (keyword == "oneOf" and matches != 1) or (keyword == "anyOf" and matches < 1):
            errors.append(f"{path} must match {keyword}")
    raw_types = node.get("type")
    expected_types = raw_types if isinstance(raw_types, list) else [raw_types] if raw_types else []
    if expected_types and not any(_matches_type(value, expected) for expected in expected_types):
        errors.append(f"{path} must be {' or '.join(expected_types)}")
        return
    if isinstance(value, str):
        if "minLength" in node and len(value) < node["minLength"]:
            errors.append(f"{path} must have length >= {node['minLength']}")
        if "maxLength" in node and len(value) > node["maxLength"]:
            errors.append(f"{path} must have length <= {node['maxLength']}")
        if "pattern" in node and re.search(node["pattern"], value) is None:
            errors.append(f"{path} must match pattern")
        if node.get("format") == "date-time":
            try:
                datetime.fromisoformat(value.replace("Z", "+00:00"))
            except ValueError:
                errors.append(f"{path} must be an ISO date-time")
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if "minimum" in node and value < node["minimum"]:
            errors.append(f"{path} must be >= {node['minimum']}")
        if "maximum" in node and value > node["maximum"]:
            errors.append(f"{path} must be <= {node['maximum']}")
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        if "minItems" in node and len(value) < node["minItems"]:
            errors.append(f"{path} must contain >= {node['minItems']} items")
        if "maxItems" in node and len(value) > node["maxItems"]:
            errors.append(f"{path} must contain <= {node['maxItems']} items")
        if node.get("uniqueItems") and len({json.dumps(item, sort_keys=True) for item in value}) != len(value):
            errors.append(f"{path} must contain unique items")
        item_schema = node.get("items", {})
        for index, item in enumerate(value):
            _validate_node(item, item_schema, f"{path}/{index}", errors, root)
    if isinstance(value, Mapping):
        properties = node.get("properties", {})
        for name in node.get("required", ()):
            if name not in value:
                errors.append(f"{path}/{name} is required")
        for name, child in properties.items():
            if name in value:
                _validate_node(value[name], child, f"{path}/{name}", errors, root)
        for name, child_value in value.items():
            if name in properties:
                continue
            additional = node.get("additionalProperties")
            if additional is False:
                errors.append(f"{path}/{name} additional property is not allowed")
            elif isinstance(additional, Mapping):
                _validate_node(child_value, additional, f"{path}/{name}", errors, root)

def validate_protocol_message(value: object) -> tuple[bool, tuple[str, ...]]:
    errors: list[str] = []
    _validate_node(value, CC_AGENT_PROTOCOL_SCHEMA, "#", errors, CC_AGENT_PROTOCOL_SCHEMA)
    return not errors, tuple(errors)

def validate_protocol_definition(name: str, value: object) -> tuple[bool, tuple[str, ...]]:
    definitions = CC_AGENT_PROTOCOL_SCHEMA.get("$defs", {})
    definition = definitions.get(name) if isinstance(definitions, Mapping) else None
    if not isinstance(definition, Mapping):
        return False, (f"# unknown protocol definition {name}",)
    errors: list[str] = []
    _validate_node(value, definition, "#", errors, CC_AGENT_PROTOCOL_SCHEMA)
    return not errors, tuple(errors)

def validate_approval_decision(value: object) -> tuple[bool, tuple[str, ...]]:
    return validate_protocol_definition("ApprovalDecision", value)

${aliases}

${typedDicts}
`;
}

function modelType(node, language) {
  if (node.$ref) {
    const name = refName(node.$ref);
    const target = schema.$defs[name];
    if (name === "JsonValue") return "JSONValue";
    if (
      target &&
      !(
        target.type === "object" &&
        target.properties &&
        !target.oneOf &&
        !target.allOf
      )
    ) {
      return modelType(target, language);
    }
    return name;
  }
  const scalarValue = Object.hasOwn(node, "const")
    ? node.const
    : Array.isArray(node.enum) && node.enum.length > 0
      ? node.enum[0]
      : undefined;
  if (scalarValue !== undefined) {
    if (typeof scalarValue === "string") return "String";
    if (typeof scalarValue === "boolean")
      return language === "swift" ? "Bool" : "Boolean";
    if (typeof scalarValue === "number") {
      return Number.isInteger(scalarValue)
        ? language === "swift"
          ? "Int"
          : "Long"
        : "Double";
    }
  }
  const type = Array.isArray(node.type)
    ? node.type.find((item) => item !== "null")
    : node.type;
  const nullable = Array.isArray(node.type) && node.type.includes("null");
  const base =
    type === "string"
      ? "String"
      : type === "integer"
        ? language === "swift"
          ? "Int"
          : "Long"
        : type === "number"
          ? "Double"
          : type === "boolean"
            ? language === "swift"
              ? "Bool"
              : "Boolean"
            : type === "array"
              ? language === "swift"
                ? `[${modelType(node.items || {}, language)}]`
                : `List<${modelType(node.items || {}, language)}>`
              : "JSONValue";
  return nullable ? `${base}?` : base;
}

const kotlinKeywords = new Set([
  "as",
  "break",
  "class",
  "continue",
  "do",
  "else",
  "false",
  "for",
  "fun",
  "if",
  "in",
  "interface",
  "is",
  "null",
  "object",
  "package",
  "return",
  "super",
  "this",
  "throw",
  "true",
  "try",
  "typealias",
  "typeof",
  "val",
  "var",
  "when",
  "while",
]);
const swiftKeywords = new Set([
  "associatedtype",
  "class",
  "deinit",
  "enum",
  "extension",
  "fileprivate",
  "func",
  "import",
  "init",
  "inout",
  "internal",
  "let",
  "operator",
  "private",
  "protocol",
  "public",
  "rethrows",
  "static",
  "struct",
  "subscript",
  "typealias",
  "var",
]);

function modelFieldName(field, language) {
  const keywords = language === "swift" ? swiftKeywords : kotlinKeywords;
  return keywords.has(field) ? `\`${field}\`` : field;
}

function approvalDecisionVariants() {
  const definition = schema.$defs.ApprovalDecision;
  if (!definition || !Array.isArray(definition.oneOf)) {
    throw new Error("ApprovalDecision must remain a oneOf discriminated union");
  }
  const variants = definition.oneOf.flatMap((branch) => {
    const kind = branch.properties?.kind;
    const kindValues = Object.hasOwn(kind || {}, "const")
      ? [kind.const]
      : kind?.enum || [];
    if (kindValues.length === 0) {
      throw new Error("every ApprovalDecision branch must declare kind");
    }
    const required = new Set(branch.required || []);
    const fields = Object.entries(branch.properties || {})
      .filter(([field]) => field !== "kind")
      .map(([field, node]) => ({ field, node, required: required.has(field) }));
    return kindValues.map((kindValue) => ({
      kind: kindValue,
      name: `${kindValue[0].toUpperCase()}${kindValue.slice(1)}`,
      fields,
    }));
  });
  const supported = variants.map(({ kind, fields }) => [
    kind,
    fields.map(({ field }) => field),
  ]);
  const expected = [
    ["acceptOnce", []],
    ["acceptForTurn", ["permissions"]],
    ["acceptForSession", ["permissions"]],
    ["decline", ["reason"]],
    ["cancel", ["reason"]],
  ];
  if (JSON.stringify(supported) !== JSON.stringify(expected)) {
    throw new Error(
      "ApprovalDecision changed; update the strict Kotlin/Swift union renderer",
    );
  }
  return variants;
}

function renderKotlinApprovalDecision() {
  approvalDecisionVariants();
  return `sealed interface ApprovalDecision {
    data object AcceptOnce : ApprovalDecision
    data class AcceptForTurn(val permissions: List<PermissionGrant>? = null) : ApprovalDecision
    data class AcceptForSession(val permissions: List<PermissionGrant>? = null) : ApprovalDecision
    data class Decline(val reason: String? = null) : ApprovalDecision
    data class Cancel(val reason: String? = null) : ApprovalDecision
}

private fun invalidApprovalDecision(message: String): Nothing =
    throw IllegalArgumentException("Invalid ApprovalDecision: $message")

private fun parseApprovalPermissions(value: Any?): List<PermissionGrant> {
    val entries = value as? List<*>
        ?: invalidApprovalDecision("permissions must be an array")
    if (entries.size > 64) invalidApprovalDecision("permissions must contain at most 64 entries")
    return entries.mapIndexed { index, entry ->
        val grant = entry as? Map<*, *>
            ?: invalidApprovalDecision("permissions[$index] must be an object")
        val unexpected = grant.keys.filter {
            it !is String || it !in setOf("capability", "scope", "expiresAt")
        }
        if (unexpected.isNotEmpty()) {
            invalidApprovalDecision("permissions[$index] has unexpected properties: $unexpected")
        }
        val capability = grant["capability"] as? String
            ?: invalidApprovalDecision("permissions[$index].capability must be a string")
        if (capability.length !in 1..128) {
            invalidApprovalDecision("permissions[$index].capability length must be 1...128")
        }
        val scope = grant["scope"] as? String
            ?: invalidApprovalDecision("permissions[$index].scope must be a string")
        if (scope.length !in 1..1024) {
            invalidApprovalDecision("permissions[$index].scope length must be 1...1024")
        }
        val expiresAt = grant["expiresAt"]
        if (grant.containsKey("expiresAt") && expiresAt != null && expiresAt !is String) {
            invalidApprovalDecision("permissions[$index].expiresAt must be a string or null")
        }
        PermissionGrant(capability = capability, scope = scope, expiresAt = expiresAt)
    }
}

fun parseApprovalDecision(value: Any?): ApprovalDecision {
    val decision = value as? Map<*, *>
        ?: invalidApprovalDecision("value must be an object")
    val kind = decision["kind"] as? String
        ?: invalidApprovalDecision("kind must be a string")
    val allowed = when (kind) {
        "acceptOnce" -> setOf("kind")
        "acceptForTurn", "acceptForSession" -> setOf("kind", "permissions")
        "decline", "cancel" -> setOf("kind", "reason")
        else -> invalidApprovalDecision("unknown kind: $kind")
    }
    val unexpected = decision.keys.filter { it !is String || it !in allowed }
    if (unexpected.isNotEmpty()) {
        invalidApprovalDecision("unexpected ApprovalDecision properties: $unexpected")
    }
    val permissions = when {
        !decision.containsKey("permissions") -> null
        decision["permissions"] == null -> invalidApprovalDecision("permissions must not be null")
        else -> parseApprovalPermissions(decision["permissions"])
    }
    val reason = when {
        !decision.containsKey("reason") -> null
        decision["reason"] !is String -> invalidApprovalDecision("reason must be a string")
        else -> decision["reason"] as String
    }
    if (reason != null && reason.length > 2048) {
        invalidApprovalDecision("reason length must be <= 2048")
    }
    return when (kind) {
        "acceptOnce" -> ApprovalDecision.AcceptOnce
        "acceptForTurn" -> ApprovalDecision.AcceptForTurn(permissions)
        "acceptForSession" -> ApprovalDecision.AcceptForSession(permissions)
        "decline" -> ApprovalDecision.Decline(reason)
        "cancel" -> ApprovalDecision.Cancel(reason)
        else -> invalidApprovalDecision("unknown kind: $kind")
    }
}

private fun approvalPermissionsWireValue(permissions: List<PermissionGrant>): List<Map<String, Any?>> {
    if (permissions.size > 64) {
        invalidApprovalDecision("permissions must contain at most 64 entries")
    }
    return permissions.mapIndexed { index, grant ->
        if (grant.capability.length !in 1..128) {
            invalidApprovalDecision("permissions[$index].capability length must be 1...128")
        }
        if (grant.scope.length !in 1..1024) {
            invalidApprovalDecision("permissions[$index].scope length must be 1...1024")
        }
        if (grant.expiresAt != null && grant.expiresAt !is String) {
            invalidApprovalDecision("permissions[$index].expiresAt must be a string or null")
        }
        linkedMapOf<String, Any?>(
            "capability" to grant.capability,
            "scope" to grant.scope,
        ).also { value -> if (grant.expiresAt != null) value["expiresAt"] = grant.expiresAt }
    }
}

private fun approvalReasonWireValue(reason: String): String {
    if (reason.length > 2048) invalidApprovalDecision("reason length must be <= 2048")
    return reason
}

fun ApprovalDecision.toWireValue(): Map<String, Any?> = when (this) {
    ApprovalDecision.AcceptOnce -> linkedMapOf("kind" to "acceptOnce")
    is ApprovalDecision.AcceptForTurn -> linkedMapOf<String, Any?>("kind" to "acceptForTurn")
        .also { value -> if (permissions != null) value["permissions"] = approvalPermissionsWireValue(permissions) }
    is ApprovalDecision.AcceptForSession -> linkedMapOf<String, Any?>("kind" to "acceptForSession")
        .also { value -> if (permissions != null) value["permissions"] = approvalPermissionsWireValue(permissions) }
    is ApprovalDecision.Decline -> linkedMapOf<String, Any?>("kind" to "decline")
        .also { value -> if (reason != null) value["reason"] = approvalReasonWireValue(reason) }
    is ApprovalDecision.Cancel -> linkedMapOf<String, Any?>("kind" to "cancel")
        .also { value -> if (reason != null) value["reason"] = approvalReasonWireValue(reason) }
}`;
}

function renderSwiftApprovalDecision() {
  approvalDecisionVariants();
  return `public enum ApprovalDecision: Codable, Sendable {
    case acceptOnce
    case acceptForTurn(permissions: [PermissionGrant]?)
    case acceptForSession(permissions: [PermissionGrant]?)
    case decline(reason: String?)
    case cancel(reason: String?)

    private struct DynamicCodingKey: CodingKey, Hashable {
        let stringValue: String
        let intValue: Int?

        init(_ stringValue: String) {
            self.stringValue = stringValue
            self.intValue = nil
        }

        init?(stringValue: String) {
            self.init(stringValue)
        }

        init?(intValue: Int) {
            self.stringValue = String(intValue)
            self.intValue = intValue
        }
    }

    private static func decodingError(
        _ codingPath: [CodingKey],
        _ message: String
    ) -> DecodingError {
        .dataCorrupted(.init(
            codingPath: codingPath,
            debugDescription: "Invalid ApprovalDecision: \\(message)"
        ))
    }

    private static func encodingError(
        _ value: ApprovalDecision,
        _ codingPath: [CodingKey],
        _ message: String
    ) -> EncodingError {
        .invalidValue(value, .init(
            codingPath: codingPath,
            debugDescription: "Invalid ApprovalDecision: \\(message)"
        ))
    }

    private static func validate(
        permissions: [PermissionGrant],
        decision: ApprovalDecision,
        codingPath: [CodingKey]
    ) throws {
        guard permissions.count <= 64 else {
            throw encodingError(decision, codingPath, "permissions must contain at most 64 entries")
        }
        for (index, grant) in permissions.enumerated() {
            guard (1...128).contains(grant.capability.count) else {
                throw encodingError(decision, codingPath, "permissions[\\(index)].capability length must be 1...128")
            }
            guard (1...1024).contains(grant.scope.count) else {
                throw encodingError(decision, codingPath, "permissions[\\(index)].scope length must be 1...1024")
            }
            if let expiresAt = grant.expiresAt {
                switch expiresAt {
                case .null:
                    break
                case .string:
                    break
                default:
                    throw encodingError(decision, codingPath, "permissions[\\(index)].expiresAt must be a string or null")
                }
            }
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: DynamicCodingKey.self)
        let kindKey = DynamicCodingKey("kind")
        guard container.contains(kindKey), !(try container.decodeNil(forKey: kindKey)) else {
            throw Self.decodingError(container.codingPath, "kind must be a string")
        }
        let kind = try container.decode(String.self, forKey: kindKey)
        let allowed: Set<String>
        switch kind {
        case "acceptOnce":
            allowed = ["kind"]
        case "acceptForTurn", "acceptForSession":
            allowed = ["kind", "permissions"]
        case "decline", "cancel":
            allowed = ["kind", "reason"]
        default:
            throw Self.decodingError(container.codingPath, "unknown kind: \\(kind)")
        }
        let unexpected = Set(container.allKeys.map(\\.stringValue)).subtracting(allowed)
        guard unexpected.isEmpty else {
            throw Self.decodingError(
                container.codingPath,
                "unexpected ApprovalDecision properties: \\(unexpected.sorted())"
            )
        }

        func decodePermissions() throws -> [PermissionGrant]? {
            let key = DynamicCodingKey("permissions")
            guard container.contains(key) else { return nil }
            guard !(try container.decodeNil(forKey: key)) else {
                throw Self.decodingError(container.codingPath, "permissions must not be null")
            }
            var entries = try container.nestedUnkeyedContainer(forKey: key)
            var grants: [PermissionGrant] = []
            while !entries.isAtEnd {
                guard grants.count < 64 else {
                    throw Self.decodingError(entries.codingPath, "permissions must contain at most 64 entries")
                }
                let index = grants.count
                let grant = try entries.nestedContainer(keyedBy: DynamicCodingKey.self)
                let grantAllowed: Set<String> = ["capability", "scope", "expiresAt"]
                let grantUnexpected = Set(grant.allKeys.map(\\.stringValue)).subtracting(grantAllowed)
                guard grantUnexpected.isEmpty else {
                    throw Self.decodingError(
                        grant.codingPath,
                        "permissions[\\(index)] has unexpected properties: \\(grantUnexpected.sorted())"
                    )
                }
                let capability = try grant.decode(String.self, forKey: DynamicCodingKey("capability"))
                guard (1...128).contains(capability.count) else {
                    throw Self.decodingError(grant.codingPath, "permissions[\\(index)].capability length must be 1...128")
                }
                let scope = try grant.decode(String.self, forKey: DynamicCodingKey("scope"))
                guard (1...1024).contains(scope.count) else {
                    throw Self.decodingError(grant.codingPath, "permissions[\\(index)].scope length must be 1...1024")
                }
                let expiresAtKey = DynamicCodingKey("expiresAt")
                let expiresAt: JSONValue?
                if grant.contains(expiresAtKey) {
                    expiresAt = try grant.decode(JSONValue.self, forKey: expiresAtKey)
                } else {
                    expiresAt = nil
                }
                if let expiresAt {
                    switch expiresAt {
                    case .null:
                        break
                    case .string:
                        break
                    default:
                        throw Self.decodingError(grant.codingPath, "permissions[\\(index)].expiresAt must be a string or null")
                    }
                }
                grants.append(PermissionGrant(
                    capability: capability,
                    scope: scope,
                    expiresAt: expiresAt
                ))
            }
            return grants
        }

        func decodeReason() throws -> String? {
            let key = DynamicCodingKey("reason")
            guard container.contains(key) else { return nil }
            guard !(try container.decodeNil(forKey: key)) else {
                throw Self.decodingError(container.codingPath, "reason must not be null")
            }
            let reason = try container.decode(String.self, forKey: key)
            guard reason.count <= 2048 else {
                throw Self.decodingError(container.codingPath, "reason length must be <= 2048")
            }
            return reason
        }

        switch kind {
        case "acceptOnce":
            self = .acceptOnce
        case "acceptForTurn":
            self = .acceptForTurn(permissions: try decodePermissions())
        case "acceptForSession":
            self = .acceptForSession(permissions: try decodePermissions())
        case "decline":
            self = .decline(reason: try decodeReason())
        case "cancel":
            self = .cancel(reason: try decodeReason())
        default:
            throw Self.decodingError(container.codingPath, "unknown kind: \\(kind)")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: DynamicCodingKey.self)
        let kindKey = DynamicCodingKey("kind")
        switch self {
        case .acceptOnce:
            try container.encode("acceptOnce", forKey: kindKey)
        case .acceptForTurn(let permissions):
            if let permissions { try Self.validate(permissions: permissions, decision: self, codingPath: encoder.codingPath) }
            try container.encode("acceptForTurn", forKey: kindKey)
            try container.encodeIfPresent(permissions, forKey: DynamicCodingKey("permissions"))
        case .acceptForSession(let permissions):
            if let permissions { try Self.validate(permissions: permissions, decision: self, codingPath: encoder.codingPath) }
            try container.encode("acceptForSession", forKey: kindKey)
            try container.encodeIfPresent(permissions, forKey: DynamicCodingKey("permissions"))
        case .decline(let reason):
            if let reason, reason.count > 2048 {
                throw Self.encodingError(self, encoder.codingPath, "reason length must be <= 2048")
            }
            try container.encode("decline", forKey: kindKey)
            try container.encodeIfPresent(reason, forKey: DynamicCodingKey("reason"))
        case .cancel(let reason):
            if let reason, reason.count > 2048 {
                throw Self.encodingError(self, encoder.codingPath, "reason length must be <= 2048")
            }
            try container.encode("cancel", forKey: kindKey)
            try container.encodeIfPresent(reason, forKey: DynamicCodingKey("reason"))
        }
    }
}`;
}

function renderKotlin() {
  const models = Object.entries(schema.$defs)
    .filter(
      ([, definition]) =>
        definition.type === "object" &&
        definition.properties &&
        !definition.oneOf &&
        !definition.allOf,
    )
    .map(([name, definition]) => {
      const required = new Set(definition.required || []);
      const fields = Object.entries(definition.properties).map(
        ([field, child]) => {
          const optional = !required.has(field);
          const type = modelType(child, "kotlin");
          return `    val ${modelFieldName(field, "kotlin")}: ${optional && !type.endsWith("?") ? `${type}?` : type}${optional ? " = null" : ""}`;
        },
      );
      return `data class ${name}(\n${fields.join(",\n")}\n)`;
    })
    .join("\n\n");
  const approvalDecision = renderKotlinApprovalDecision();
  return `// AUTO-GENERATED by @chainlesschain/agent-protocol. DO NOT EDIT.
package com.chainlesschain.agent.protocol.generated

const val CC_AGENT_PROTOCOL_VERSION: Int = ${protocol.version}
const val CC_AGENT_PROTOCOL_MIN_VERSION: Int = ${protocol.minimumCompatibleVersion}
const val CC_AGENT_PROTOCOL_SCHEMA_DIGEST: String = "${digest}"
typealias JSONValue = Any?

${models}

${approvalDecision}
`;
}

function renderSwift() {
  const models = Object.entries(schema.$defs)
    .filter(
      ([, definition]) =>
        definition.type === "object" &&
        definition.properties &&
        !definition.oneOf &&
        !definition.allOf,
    )
    .map(([name, definition]) => {
      const required = new Set(definition.required || []);
      const fields = Object.entries(definition.properties).map(
        ([field, child]) => {
          const optional = !required.has(field);
          const rawType = modelType(child, "swift");
          const type =
            optional && !rawType.endsWith("?") ? `${rawType}?` : rawType;
          return { field, optional, type };
        },
      );
      const declarations = fields.map(
        ({ field, type }) =>
          `    public let ${modelFieldName(field, "swift")}: ${type}`,
      );
      const parameters = fields.map(
        ({ field, optional, type }) =>
          `        ${modelFieldName(field, "swift")}: ${type}${optional ? " = nil" : ""}`,
      );
      const assignments = fields.map(
        ({ field }) =>
          `        self.${modelFieldName(field, "swift")} = ${modelFieldName(field, "swift")}`,
      );
      return `public struct ${name}: Codable, Sendable {
${declarations.join("\n")}

    public init(
${parameters.join(",\n")}
    ) {
${assignments.join("\n")}
    }
}`;
    })
    .join("\n\n");
  const approvalDecision = renderSwiftApprovalDecision();
  return `// AUTO-GENERATED by @chainlesschain/agent-protocol. DO NOT EDIT.
import Foundation

public let ccAgentProtocolVersion = ${protocol.version}
public let ccAgentProtocolMinimumVersion = ${protocol.minimumCompatibleVersion}
public let ccAgentProtocolSchemaDigest = "${digest}"
public indirect enum JSONValue: Codable, Sendable {
    case null
    case bool(Bool)
    case number(Double)
    case string(String)
    case array([JSONValue])
    case object([String: JSONValue])

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null }
        else if let value = try? container.decode(Bool.self) { self = .bool(value) }
        else if let value = try? container.decode(Double.self) { self = .number(value) }
        else if let value = try? container.decode(String.self) { self = .string(value) }
        else if let value = try? container.decode([JSONValue].self) { self = .array(value) }
        else { self = .object(try container.decode([String: JSONValue].self)) }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .null: try container.encodeNil()
        case .bool(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .string(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        }
    }
}

${models}

${approvalDecision}
`;
}

const outputs = new Map([
  [
    resolve(
      repositoryRoot,
      "packages",
      "agent-sdk",
      "src",
      "generated",
      "app-protocol.ts",
    ),
    renderTypeScript(),
  ],
  [
    resolve(
      repositoryRoot,
      "packages",
      "agent-sdk-python",
      "src",
      "chainlesschain_agent_sdk",
      "generated_app_protocol.py",
    ),
    renderPython(),
  ],
  [resolve(root, "generated", "kotlin", "CcAgentProtocol.kt"), renderKotlin()],
  [resolve(root, "generated", "swift", "CcAgentProtocol.swift"), renderSwift()],
  [
    resolve(
      repositoryRoot,
      "packages",
      "cli",
      "src",
      "generated",
      "cc-agent-protocol.schema.json",
    ),
    `${JSON.stringify(schema, null, 2)}\n`,
  ],
]);

let stale = false;
for (const [file, content] of outputs) {
  let current = null;
  try {
    current = readFileSync(file, "utf8");
  } catch {
    // A missing generated target is stale and will be reported below.
  }
  if (current === content) continue;
  if (checkOnly) {
    stale = true;
    console.error(`Generated protocol artifact is stale: ${file}`);
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content, "utf8");
    console.error(`Wrote ${file}`);
  }
}
if (stale) process.exitCode = 1;
