#!/usr/bin/env node
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { assertProtocolCompatible } from "../src/compatibility.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(root, "..", "..");
const schemaPath = resolve(root, "schema", "cc-agent-protocol.schema.json");
const baselinePath = resolve(root, "schema", "baselines", "v1.json");
const schemaText = readFileSync(schemaPath, "utf8");
const schema = JSON.parse(schemaText);
const digest = `sha256:${createHash("sha256").update(schemaText).digest("hex")}`;
const protocol = schema["x-cc-protocol"];
const checkOnly = process.argv.includes("--check");
const freezeBaseline = process.argv.includes("--freeze-baseline");

if (freezeBaseline) {
  mkdirSync(dirname(baselinePath), { recursive: true });
  writeFileSync(baselinePath, `${JSON.stringify(schema, null, 2)}\n`, "utf8");
  console.error(`Wrote ${baselinePath}`);
}
if (existsSync(baselinePath)) {
  assertProtocolCompatible(
    JSON.parse(readFileSync(baselinePath, "utf8")),
    schema,
  );
}

function refName(value) {
  return value.replace("#/$defs/", "");
}

function tsType(node = {}) {
  if (node.$ref) return refName(node.$ref);
  if (Object.hasOwn(node, "const")) return JSON.stringify(node.const);
  if (node.enum)
    return node.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (node.oneOf) return node.oneOf.map(tsType).join(" | ");
  if (node.anyOf) return node.anyOf.map(tsType).join(" | ");
  if (node.allOf)
    return node.allOf.map((part) => `(${tsType(part)})`).join(" & ");
  if (Array.isArray(node.type))
    return node.type.map((type) => tsType({ ...node, type })).join(" | ");
  if (node.type === "null") return "null";
  if (node.type === "boolean") return "boolean";
  if (node.type === "number" || node.type === "integer") return "number";
  if (node.type === "string") return "string";
  if (node.type === "array") return `Array<${tsType(node.items || {})}>`;
  if (node.type === "object" || node.properties || node.additionalProperties) {
    const required = new Set(node.required || []);
    const properties = Object.entries(node.properties || {}).map(
      ([name, value]) =>
        `${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${tsType(value)};`,
    );
    if (node.additionalProperties && node.additionalProperties !== false) {
      properties.push(`[key: string]: ${tsType(node.additionalProperties)};`);
    }
    return `{ ${properties.join(" ")} }`;
  }
  return "unknown";
}

function renderTypeScript() {
  const types = Object.entries(schema.$defs)
    .map(([name, definition]) => `export type ${name} = ${tsType(definition)};`)
    .join("\n\n");
  return `/* AUTO-GENERATED by @chainlesschain/agent-protocol. DO NOT EDIT. */
export const CC_AGENT_PROTOCOL_VERSION = ${protocol.version} as const;
export const CC_AGENT_PROTOCOL_MIN_VERSION = ${protocol.minimumCompatibleVersion} as const;
export const CC_AGENT_PROTOCOL_SCHEMA_DIGEST = ${JSON.stringify(digest)} as const;
export const CC_AGENT_PROTOCOL_FEATURES = ${JSON.stringify(protocol.features)} as const;
export const CC_AGENT_PROTOCOL_SCHEMA = ${JSON.stringify(schema, null, 2)} as const;

export interface ProtocolValidationError { path: string; message: string }
export interface ProtocolValidationResult { ok: boolean; errors: ProtocolValidationError[] }

function matchesType(value: unknown, type: string): boolean {
  if (type === "null") return value === null;
  if (type === "array") return Array.isArray(value);
  if (type === "integer") return typeof value === "number" && Number.isSafeInteger(value);
  if (type === "number") return typeof value === "number" && Number.isFinite(value);
  if (type === "object") return value !== null && typeof value === "object" && !Array.isArray(value);
  return typeof value === type;
}

function validateNode(value: unknown, node: any, path: string, errors: ProtocolValidationError[], root: any): boolean {
  const start = errors.length;
  if (node.$ref) {
    const target = node.$ref.split("/").slice(1).reduce((current: any, part: string) => current?.[part.replaceAll("~1", "/").replaceAll("~0", "~")], root);
    if (!target) errors.push({ path, message: \`unresolved schema reference \${node.$ref}\` });
    else validateNode(value, target, path, errors, root);
    return errors.length === start;
  }
  if (Object.prototype.hasOwnProperty.call(node, "const") && JSON.stringify(value) !== JSON.stringify(node.const)) {
    errors.push({ path, message: \`must equal \${JSON.stringify(node.const)}\` });
  }
  if (node.enum && !node.enum.some((candidate: unknown) => JSON.stringify(candidate) === JSON.stringify(value))) {
    errors.push({ path, message: "must be an allowed enum value" });
  }
  for (const keyword of ["allOf"] as const) for (const child of node[keyword] || []) validateNode(value, child, path, errors, root);
  for (const keyword of ["oneOf", "anyOf"] as const) {
    if (!node[keyword]) continue;
    const matches = node[keyword].filter((child: any) => {
      const branchErrors: ProtocolValidationError[] = [];
      validateNode(value, child, path, branchErrors, root);
      return branchErrors.length === 0;
    }).length;
    if ((keyword === "oneOf" && matches !== 1) || (keyword === "anyOf" && matches < 1)) errors.push({ path, message: \`must match \${keyword}\` });
  }
  const types = Array.isArray(node.type) ? node.type : node.type ? [node.type] : [];
  if (types.length && !types.some((type: string) => matchesType(value, type))) {
    errors.push({ path, message: \`must be \${types.join(" or ")}\` });
    return false;
  }
  if (typeof value === "string") {
    if (node.minLength != null && value.length < node.minLength) errors.push({ path, message: \`must have length >= \${node.minLength}\` });
    if (node.maxLength != null && value.length > node.maxLength) errors.push({ path, message: \`must have length <= \${node.maxLength}\` });
    if (node.pattern && !new RegExp(node.pattern, "u").test(value)) errors.push({ path, message: "must match pattern" });
    if (node.format === "date-time" && Number.isNaN(Date.parse(value))) errors.push({ path, message: "must be an ISO date-time" });
  }
  if (typeof value === "number") {
    if (node.minimum != null && value < node.minimum) errors.push({ path, message: \`must be >= \${node.minimum}\` });
    if (node.maximum != null && value > node.maximum) errors.push({ path, message: \`must be <= \${node.maximum}\` });
  }
  if (Array.isArray(value)) {
    if (node.minItems != null && value.length < node.minItems) errors.push({ path, message: \`must contain >= \${node.minItems} items\` });
    if (node.maxItems != null && value.length > node.maxItems) errors.push({ path, message: \`must contain <= \${node.maxItems} items\` });
    if (node.uniqueItems && new Set(value.map((item) => JSON.stringify(item))).size !== value.length) errors.push({ path, message: "must contain unique items" });
    value.forEach((item, index) => validateNode(item, node.items || {}, \`\${path}/\${index}\`, errors, root));
  }
  if (value && typeof value === "object" && !Array.isArray(value)) {
    const record = value as Record<string, unknown>;
    for (const name of node.required || []) if (!Object.prototype.hasOwnProperty.call(record, name)) errors.push({ path: \`\${path}/\${name}\`, message: "is required" });
    for (const [name, child] of Object.entries(node.properties || {})) if (Object.prototype.hasOwnProperty.call(record, name)) validateNode(record[name], child, \`\${path}/\${name}\`, errors, root);
    const known = new Set(Object.keys(node.properties || {}));
    for (const [name, childValue] of Object.entries(record)) {
      if (known.has(name)) continue;
      if (node.additionalProperties === false) errors.push({ path: \`\${path}/\${name}\`, message: "additional property is not allowed" });
      else if (node.additionalProperties && typeof node.additionalProperties === "object") validateNode(childValue, node.additionalProperties, \`\${path}/\${name}\`, errors, root);
    }
  }
  return errors.length === start;
}

export function validateProtocolMessage(value: unknown): ProtocolValidationResult {
  const errors: ProtocolValidationError[] = [];
  validateNode(value, CC_AGENT_PROTOCOL_SCHEMA, "#", errors, CC_AGENT_PROTOCOL_SCHEMA);
  return { ok: errors.length === 0, errors };
}

export function validateProtocolDefinition(name: keyof typeof CC_AGENT_PROTOCOL_SCHEMA.$defs, value: unknown): ProtocolValidationResult {
  const errors: ProtocolValidationError[] = [];
  const definition = CC_AGENT_PROTOCOL_SCHEMA.$defs[name];
  if (!definition) return { ok: false, errors: [{ path: "#", message: \`unknown protocol definition \${String(name)}\` }] };
  validateNode(value, definition, "#", errors, CC_AGENT_PROTOCOL_SCHEMA);
  return { ok: errors.length === 0, errors };
}

export function validateApprovalDecision(value: unknown): ProtocolValidationResult {
  return validateProtocolDefinition("ApprovalDecision", value);
}

export function isApprovalDecision(value: unknown): value is ApprovalDecision {
  return validateApprovalDecision(value).ok;
}

export function assertApprovalDecision(value: unknown): asserts value is ApprovalDecision {
  const result = validateApprovalDecision(value);
  if (!result.ok) throw new TypeError(\`Invalid ApprovalDecision: \${result.errors.map((error) => \`\${error.path} \${error.message}\`).join("; ")}\`);
}

export function assertProtocolMessage(value: unknown): asserts value is ClientRequest | ClientResponse | ServerRequest | ServerNotification {
  const result = validateProtocolMessage(value);
  if (!result.ok) throw new TypeError(\`Invalid CC Agent protocol message: \${result.errors.map((error) => \`\${error.path} \${error.message}\`).join("; ")}\`);
}

${types}
`;
}

function pyType(node = {}, { quoteRefs = false } = {}) {
  if (node.$ref) {
    const name = refName(node.$ref);
    return quoteRefs ? JSON.stringify(name) : name;
  }
  if (Object.hasOwn(node, "const"))
    return `Literal[${JSON.stringify(node.const)}]`;
  if (node.enum)
    return `Literal[${node.enum.map((value) => JSON.stringify(value)).join(", ")}]`;
  if (node.oneOf || node.anyOf)
    return `Union[${(node.oneOf || node.anyOf)
      .map((child) => pyType(child, { quoteRefs }))
      .join(", ")}]`;
  if (node.allOf) return "Mapping[str, Any]";
  if (Array.isArray(node.type))
    return `Union[${node.type
      .map((type) => pyType({ ...node, type }, { quoteRefs }))
      .join(", ")}]`;
  if (node.type === "null") return "None";
  if (node.type === "boolean") return "bool";
  if (node.type === "integer") return "int";
  if (node.type === "number") return "float";
  if (node.type === "string") return "str";
  if (node.type === "array")
    return `Sequence[${pyType(node.items || {}, { quoteRefs })}]`;
  if (node.type === "object" || node.properties) return "Mapping[str, Any]";
  return "Any";
}

function renderPython() {
  const aliases = Object.entries(schema.$defs)
    .filter(
      ([, definition]) =>
        definition.type !== "object" && !definition.properties,
    )
    .map(
      ([name, definition]) =>
        `${name}: TypeAlias = ${pyType(definition, { quoteRefs: true })}`,
    )
    .join("\n");
  const typedDicts = Object.entries(schema.$defs)
    .filter(
      ([, definition]) => definition.type === "object" || definition.properties,
    )
    .map(([name, definition]) => {
      const required = new Set(definition.required || []);
      const fields = Object.entries(definition.properties || {});
      const renderFields = (entries) =>
        entries
          .map(
            ([field, child]) =>
              `        ${JSON.stringify(field)}: ${JSON.stringify(pyType(child))},`,
          )
          .join("\n");
      const requiredFields = renderFields(
        fields.filter(([field]) => required.has(field)),
      );
      const optionalFields = renderFields(
        fields.filter(([field]) => !required.has(field)),
      );
      return `_${name}Required = TypedDict(\n    ${JSON.stringify(`_${name}Required`)},\n    {\n${requiredFields}\n    },\n    total=True,\n)\n_${name}Optional = TypedDict(\n    ${JSON.stringify(`_${name}Optional`)},\n    {\n${optionalFields}\n    },\n    total=False,\n)\n\nclass ${name}(_${name}Required, _${name}Optional):\n    pass`;
    })
    .join("\n\n");
  return `# AUTO-GENERATED by @chainlesschain/agent-protocol. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime
import json
import re
from typing import Any, Literal, Mapping, Sequence, TypeAlias, TypedDict, Union

CC_AGENT_PROTOCOL_VERSION = ${protocol.version}
CC_AGENT_PROTOCOL_MIN_VERSION = ${protocol.minimumCompatibleVersion}
CC_AGENT_PROTOCOL_SCHEMA_DIGEST = ${JSON.stringify(digest)}
CC_AGENT_PROTOCOL_FEATURES = ${JSON.stringify(protocol.features)}
CC_AGENT_PROTOCOL_SCHEMA: Mapping[str, Any] = json.loads(${JSON.stringify(JSON.stringify(schema))})

def _matches_type(value: Any, expected: str) -> bool:
    if expected == "null":
        return value is None
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if expected == "string":
        return isinstance(value, str)
    if expected == "array":
        return isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray))
    if expected == "object":
        return isinstance(value, Mapping)
    return False

def _resolve_ref(root: Mapping[str, Any], reference: str) -> Any:
    if not reference.startswith("#/"):
        return None
    current: Any = root
    for raw_part in reference[2:].split("/"):
        part = raw_part.replace("~1", "/").replace("~0", "~")
        if not isinstance(current, Mapping) or part not in current:
            return None
        current = current[part]
    return current

def _validate_node(value: Any, node: Mapping[str, Any], path: str, errors: list[str], root: Mapping[str, Any]) -> None:
    reference = node.get("$ref")
    if isinstance(reference, str):
        target = _resolve_ref(root, reference)
        if not isinstance(target, Mapping):
            errors.append(f"{path} unresolved schema reference {reference}")
        else:
            _validate_node(value, target, path, errors, root)
        return
    if "const" in node and value != node["const"]:
        errors.append(f"{path} must equal {node['const']!r}")
    if "enum" in node and value not in node["enum"]:
        errors.append(f"{path} must be an allowed enum value")
    for child in node.get("allOf", ()):
        _validate_node(value, child, path, errors, root)
    for keyword in ("oneOf", "anyOf"):
        branches = node.get(keyword)
        if not branches:
            continue
        matches = 0
        for child in branches:
            branch_errors: list[str] = []
            _validate_node(value, child, path, branch_errors, root)
            if not branch_errors:
                matches += 1
        if (keyword == "oneOf" and matches != 1) or (keyword == "anyOf" and matches < 1):
            errors.append(f"{path} must match {keyword}")
    raw_types = node.get("type")
    expected_types = raw_types if isinstance(raw_types, list) else [raw_types] if raw_types else []
    if expected_types and not any(_matches_type(value, expected) for expected in expected_types):
        errors.append(f"{path} must be {' or '.join(expected_types)}")
        return
    if isinstance(value, str):
        if "minLength" in node and len(value) < node["minLength"]:
            errors.append(f"{path} must have length >= {node['minLength']}")
        if "maxLength" in node and len(value) > node["maxLength"]:
            errors.append(f"{path} must have length <= {node['maxLength']}")
        if "pattern" in node and re.search(node["pattern"], value) is None:
            errors.append(f"{path} must match pattern")
        if node.get("format") == "date-time":
            try:
                datetime.fromisoformat(value.replace("Z", "+00:00"))
            except ValueError:
                errors.append(f"{path} must be an ISO date-time")
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if "minimum" in node and value < node["minimum"]:
            errors.append(f"{path} must be >= {node['minimum']}")
        if "maximum" in node and value > node["maximum"]:
            errors.append(f"{path} must be <= {node['maximum']}")
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        if "minItems" in node and len(value) < node["minItems"]:
            errors.append(f"{path} must contain >= {node['minItems']} items")
        if "maxItems" in node and len(value) > node["maxItems"]:
            errors.append(f"{path} must contain <= {node['maxItems']} items")
        if node.get("uniqueItems") and len({json.dumps(item, sort_keys=True) for item in value}) != len(value):
            errors.append(f"{path} must contain unique items")
        item_schema = node.get("items", {})
        for index, item in enumerate(value):
            _validate_node(item, item_schema, f"{path}/{index}", errors, root)
    if isinstance(value, Mapping):
        properties = node.get("properties", {})
        for name in node.get("required", ()):
            if name not in value:
                errors.append(f"{path}/{name} is required")
        for name, child in properties.items():
            if name in value:
                _validate_node(value[name], child, f"{path}/{name}", errors, root)
        for name, child_value in value.items():
            if name in properties:
                continue
            additional = node.get("additionalProperties")
            if additional is False:
                errors.append(f"{path}/{name} additional property is not allowed")
            elif isinstance(additional, Mapping):
                _validate_node(child_value, additional, f"{path}/{name}", errors, root)

def validate_protocol_message(value: object) -> tuple[bool, tuple[str, ...]]:
    errors: list[str] = []
    _validate_node(value, CC_AGENT_PROTOCOL_SCHEMA, "#", errors, CC_AGENT_PROTOCOL_SCHEMA)
    return not errors, tuple(errors)

def validate_protocol_definition(name: str, value: object) -> tuple[bool, tuple[str, ...]]:
    definitions = CC_AGENT_PROTOCOL_SCHEMA.get("$defs", {})
    definition = definitions.get(name) if isinstance(definitions, Mapping) else None
    if not isinstance(definition, Mapping):
        return False, (f"# unknown protocol definition {name}",)
    errors: list[str] = []
    _validate_node(value, definition, "#", errors, CC_AGENT_PROTOCOL_SCHEMA)
    return not errors, tuple(errors)

def validate_approval_decision(value: object) -> tuple[bool, tuple[str, ...]]:
    return validate_protocol_definition("ApprovalDecision", value)

${aliases}

${typedDicts}
`;
}

function modelType(node, language) {
  if (node.$ref) {
    const name = refName(node.$ref);
    const target = schema.$defs[name];
    if (name === "JsonValue") return "JSONValue";
    if (
      target &&
      !(
        target.type === "object" &&
        target.properties &&
        !target.oneOf &&
        !target.allOf
      )
    ) {
      return modelType(target, language);
    }
    return name;
  }
  const scalarValue = Object.hasOwn(node, "const")
    ? node.const
    : Array.isArray(node.enum) && node.enum.length > 0
      ? node.enum[0]
      : undefined;
  if (scalarValue !== undefined) {
    if (typeof scalarValue === "string") return "String";
    if (typeof scalarValue === "boolean")
      return language === "swift" ? "Bool" : "Boolean";
    if (typeof scalarValue === "number") {
      return Number.isInteger(scalarValue)
        ? language === "swift"
          ? "Int"
          : "Long"
        : "Double";
    }
  }
  const type = Array.isArray(node.type)
    ? node.type.find((item) => item !== "null")
    : node.type;
  const nullable = Array.isArray(node.type) && node.type.includes("null");
  const base =
    type === "string"
      ? "String"
      : type === "integer"
        ? language === "swift"
          ? "Int"
          : "Long"
        : type === "number"
          ? "Double"
          : type === "boolean"
            ? language === "swift"
              ? "Bool"
              : "Boolean"
            : type === "array"
              ? language === "swift"
                ? `[${modelType(node.items || {}, language)}]`
                : `List<${modelType(node.items || {}, language)}>`
              : "JSONValue";
  return nullable ? `${base}?` : base;
}

const kotlinKeywords = new Set([
  "as",
  "break",
  "class",
  "continue",
  "do",
  "else",
  "false",
  "for",
  "fun",
  "if",
  "in",
  "interface",
  "is",
  "null",
  "object",
  "package",
  "return",
  "super",
  "this",
  "throw",
  "true",
  "try",
  "typealias",
  "typeof",
  "val",
  "var",
  "when",
  "while",
]);
const swiftKeywords = new Set([
  "associatedtype",
  "class",
  "deinit",
  "enum",
  "extension",
  "fileprivate",
  "func",
  "import",
  "init",
  "inout",
  "internal",
  "let",
  "operator",
  "private",
  "protocol",
  "public",
  "rethrows",
  "static",
  "struct",
  "subscript",
  "typealias",
  "var",
]);

function modelFieldName(field, language) {
  const keywords = language === "swift" ? swiftKeywords : kotlinKeywords;
  return keywords.has(field) ? `\`${field}\`` : field;
}

function renderKotlin() {
  const models = Object.entries(schema.$defs)
    .filter(
      ([, definition]) =>
        definition.type === "object" &&
        definition.properties &&
        !definition.oneOf &&
        !definition.allOf,
    )
    .map(([name, definition]) => {
      const required = new Set(definition.required || []);
      const fields = Object.entries(definition.properties).map(
        ([field, child]) => {
          const optional = !required.has(field);
          const type = modelType(child, "kotlin");
          return `    val ${modelFieldName(field, "kotlin")}: ${optional && !type.endsWith("?") ? `${type}?` : type}${optional ? " = null" : ""}`;
        },
      );
      return `data class ${name}(\n${fields.join(",\n")}\n)`;
    })
    .join("\n\n");
  return `// AUTO-GENERATED by @chainlesschain/agent-protocol. DO NOT EDIT.
package com.chainlesschain.agent.protocol.generated

const val CC_AGENT_PROTOCOL_VERSION: Int = ${protocol.version}
const val CC_AGENT_PROTOCOL_MIN_VERSION: Int = ${protocol.minimumCompatibleVersion}
const val CC_AGENT_PROTOCOL_SCHEMA_DIGEST: String = "${digest}"
typealias JSONValue = Any?

${models}
`;
}

function renderSwift() {
  const models = Object.entries(schema.$defs)
    .filter(
      ([, definition]) =>
        definition.type === "object" &&
        definition.properties &&
        !definition.oneOf &&
        !definition.allOf,
    )
    .map(([name, definition]) => {
      const required = new Set(definition.required || []);
      const fields = Object.entries(definition.properties).map(
        ([field, child]) => {
          const optional = !required.has(field);
          const type = modelType(child, "swift");
          return `    public let ${modelFieldName(field, "swift")}: ${optional && !type.endsWith("?") ? `${type}?` : type}`;
        },
      );
      return `public struct ${name}: Codable, Sendable {\n${fields.join("\n")}\n}`;
    })
    .join("\n\n");
  return `// AUTO-GENERATED by @chainlesschain/agent-protocol. DO NOT EDIT.
import Foundation

public let ccAgentProtocolVersion = ${protocol.version}
public let ccAgentProtocolMinimumVersion = ${protocol.minimumCompatibleVersion}
public let ccAgentProtocolSchemaDigest = "${digest}"
public indirect enum JSONValue: Codable, Sendable {
    case null
    case bool(Bool)
    case number(Double)
    case string(String)
    case array([JSONValue])
    case object([String: JSONValue])

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null }
        else if let value = try? container.decode(Bool.self) { self = .bool(value) }
        else if let value = try? container.decode(Double.self) { self = .number(value) }
        else if let value = try? container.decode(String.self) { self = .string(value) }
        else if let value = try? container.decode([JSONValue].self) { self = .array(value) }
        else { self = .object(try container.decode([String: JSONValue].self)) }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .null: try container.encodeNil()
        case .bool(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .string(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        }
    }
}

${models}
`;
}

const outputs = new Map([
  [
    resolve(
      repositoryRoot,
      "packages",
      "agent-sdk",
      "src",
      "generated",
      "app-protocol.ts",
    ),
    renderTypeScript(),
  ],
  [
    resolve(
      repositoryRoot,
      "packages",
      "agent-sdk-python",
      "src",
      "chainlesschain_agent_sdk",
      "generated_app_protocol.py",
    ),
    renderPython(),
  ],
  [resolve(root, "generated", "kotlin", "CcAgentProtocol.kt"), renderKotlin()],
  [resolve(root, "generated", "swift", "CcAgentProtocol.swift"), renderSwift()],
  [
    resolve(
      repositoryRoot,
      "packages",
      "cli",
      "src",
      "generated",
      "cc-agent-protocol.schema.json",
    ),
    `${JSON.stringify(schema, null, 2)}\n`,
  ],
]);

let stale = false;
for (const [file, content] of outputs) {
  let current = null;
  try {
    current = readFileSync(file, "utf8");
  } catch {
    // A missing generated target is stale and will be reported below.
  }
  if (current === content) continue;
  if (checkOnly) {
    stale = true;
    console.error(`Generated protocol artifact is stale: ${file}`);
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content, "utf8");
    console.error(`Wrote ${file}`);
  }
}
if (stale) process.exitCode = 1;
