import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { ArtifactStore } from "../../src/lib/artifact-store.js";
import {
  runArtifactsDeliveryEvidence,
  runArtifactsDeliveryInit,
  runArtifactsDeliveryProject,
  runArtifactsDeliveryStep,
  runArtifactsSelectGates,
} from "../../src/commands/artifacts.js";
import {
  IMPACTED_GATE_SELECTION_SCHEMA,
  IMPACTED_GATE_SELECTION_VERSION,
} from "../../src/lib/impacted-gate-selector.js";
import {
  createDeliveryFlow,
  requestDeliveryAction,
} from "../../src/lib/delivery-coordinator.js";

const HEAD = "a".repeat(40);
const BASE = "b".repeat(40);
const DIGEST = `sha256:${"c".repeat(64)}`;

function validEvidence() {
  return {
    commit: { sha: HEAD },
    diff: {
      baseCommitSha: BASE,
      headCommitSha: HEAD,
      digest: DIGEST,
      changedFiles: ["src/a.js"],
    },
    environment: {
      os: "linux",
      arch: "x64",
      runtime: "node",
      runtimeVersion: "22.12.0",
      dependencyDigest: DIGEST,
    },
    gates: {
      selection: {
        schema: IMPACTED_GATE_SELECTION_SCHEMA,
        version: IMPACTED_GATE_SELECTION_VERSION,
        decision: "selected",
        mode: "full",
        requiredGateIds: ["ci"],
        selectedGateIds: ["ci"],
      },
      required: [{ id: "ci", matrix: ["linux"] }],
      results: [
        {
          id: "ci",
          status: "passed",
          commitSha: HEAD,
          matrix: [{ id: "linux", status: "passed", commitSha: HEAD }],
        },
      ],
    },
    review: {
      status: "approved",
      commitSha: HEAD,
      evidenceDigest: DIGEST,
    },
    unverified: [],
    sideEffects: [],
    pr: {
      number: 1,
      autoMergeEnabled: true,
      hasOpenPr: true,
      branchProtectionSatisfied: true,
      reviewApproved: true,
      pendingApprovals: 0,
      headCommitSha: HEAD,
      ciCommitSha: HEAD,
      requiredMatrixComplete: true,
      requiredChecks: ["ci/linux"],
      checks: [{ name: "ci/linux", state: "success", commitSha: HEAD }],
    },
  };
}

function flowConfig() {
  return {
    flowId: "cli-flow",
    commitSha: HEAD,
    diff: {
      baseCommitSha: BASE,
      headCommitSha: HEAD,
      digest: DIGEST,
      changedFiles: ["src/a.js"],
    },
    environment: {
      os: "linux",
      arch: "x64",
      runtime: "node",
      runtimeVersion: "22.12.0",
      dependencyDigest: DIGEST,
    },
    requiredGates: [{ id: "ci", always: true, matrix: ["linux"] }],
    analysis: {
      confidence: 0.99,
      dependencyGraphComplete: true,
      languageServicesComplete: true,
      testHistoryComplete: true,
      classifications: [
        {
          path: "src/a.js",
          language: "javascript",
          ecosystem: "npm",
          confidence: 0.99,
        },
      ],
    },
    unverified: [],
    sideEffects: [],
    policy: { autoMergeEnabled: true },
  };
}

describe("delivery evidence artifact/CLI", () => {
  let dir;
  let store;
  let logs;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "cc-delivery-evidence-"));
    store = new ArtifactStore({ dir, now: () => Date.UTC(2026, 7, 1) });
    logs = [];
    vi.spyOn(console, "log").mockImplementation((...args) =>
      logs.push(args.join(" ")),
    );
    vi.spyOn(console, "error").mockImplementation((...args) =>
      logs.push(args.join(" ")),
    );
  });

  afterEach(() => {
    vi.restoreAllMocks();
    fs.rmSync(dir, { recursive: true, force: true });
  });

  function writeJson(name, value) {
    const file = path.join(dir, name);
    fs.writeFileSync(file, JSON.stringify(value), "utf-8");
    return file;
  }

  it("stores generated bytes as immutable metadata and detects tampering", () => {
    const entry = store.publishData({
      data: '{"ok":true}\n',
      fileName: "evidence.json",
      kind: "data",
      immutable: true,
      recordDigest: DIGEST,
    });
    expect(entry).toMatchObject({
      immutable: true,
      recordDigest: DIGEST,
      mime: "application/json",
    });
    expect(store.verifyIntegrity(entry)).toMatchObject({
      ok: true,
      reason: "ok",
    });

    const storedPath = store.storedPath(entry);
    fs.chmodSync(storedPath, 0o666);
    fs.writeFileSync(storedPath, "tampered", "utf-8");
    expect(store.verifyIntegrity(entry)).toMatchObject({
      ok: false,
      reason: "artifact-digest-mismatch",
    });
  });

  it("emits a machine-readable full-suite fallback", () => {
    const input = writeJson("selector.json", {
      changedFiles: ["src/a.js"],
      requiredGates: ["lint", "test"],
      analysis: { confidence: 0.2 },
    });
    expect(runArtifactsSelectGates(input, { json: true })).toBe(0);
    const payload = JSON.parse(logs.at(-1));
    expect(payload).toMatchObject({
      schema: IMPACTED_GATE_SELECTION_SCHEMA,
      mode: "full",
      fallback: true,
      selectedGateIds: ["lint", "test"],
    });
  });

  it("archives a ready record and reports readiness/integrity as JSON", () => {
    const input = writeJson("delivery.json", validEvidence());
    expect(
      runArtifactsDeliveryEvidence(
        input,
        { json: true, session: "sess-1" },
        { store, now: "2026-08-01T00:00:00.000Z" },
      ),
    ).toBe(0);
    const payload = JSON.parse(logs.at(-1));
    expect(payload).toMatchObject({
      schema: "chainlesschain.delivery-evidence-command-result",
      version: 1,
      archived: true,
      artifact: {
        immutable: true,
        recordDigest: expect.stringMatching(/^sha256:[0-9a-f]{64}$/),
        sessionId: "sess-1",
      },
      artifactIntegrity: { ok: true, reason: "ok" },
      verification: { valid: true },
      readiness: { ready: true, reason: "ok" },
    });
    expect(store.list()).toHaveLength(1);
  });

  it("archives but exits non-zero when CI points at an older commit", () => {
    const evidence = validEvidence();
    evidence.pr.ciCommitSha = BASE;
    const input = writeJson("stale.json", evidence);
    expect(
      runArtifactsDeliveryEvidence(
        input,
        { json: true },
        { store, now: "2026-08-01T00:00:00.000Z" },
      ),
    ).toBe(1);
    const payload = JSON.parse(logs.at(-1));
    expect(payload.archived).toBe(true);
    expect(payload.readiness.unmet).toContain("pr:ci-head-mismatch");
  });

  it("initializes, requests and explicitly settles a resumable flow as JSON", () => {
    const input = writeJson("flow-config.json", flowConfig());
    expect(
      runArtifactsDeliveryInit(
        input,
        { json: true },
        { now: "2026-08-01T00:00:00.000Z" },
      ),
    ).toBe(0);
    let payload = JSON.parse(logs.at(-1));
    expect(payload).toMatchObject({
      schema: "chainlesschain.delivery-flow-command-result",
      projection: {
        flowId: "cli-flow",
        phase: "gates",
        availableActions: ["run_gates"],
      },
    });

    let stateFile = writeJson("flow-state.json", payload.state);
    logs = [];
    expect(
      runArtifactsDeliveryStep(
        stateFile,
        { action: "run_gates", json: true },
        { now: "2026-08-01T00:00:01.000Z" },
      ),
    ).toBe(0);
    payload = JSON.parse(logs.at(-1));
    expect(payload.projection).toMatchObject({
      pendingEffect: { action: "run_gates" },
      availableActions: [],
    });

    stateFile = writeJson("flow-pending.json", payload.state);
    const resultFile = writeJson("gate-result.json", {
      schema: "chainlesschain.delivery-action-result",
      version: 1,
      effectId: payload.state.pendingEffect.id,
      result: {
        commitSha: HEAD,
        results: [
          {
            id: "ci",
            status: "passed",
            commitSha: HEAD,
            matrix: [{ id: "linux", status: "passed", commitSha: HEAD }],
          },
        ],
        sideEffects: [],
      },
    });
    logs = [];
    expect(
      runArtifactsDeliveryStep(
        stateFile,
        { resultFile, json: true },
        { now: "2026-08-01T00:00:02.000Z" },
      ),
    ).toBe(0);
    payload = JSON.parse(logs.at(-1));
    expect(payload.projection).toMatchObject({
      phase: "preview",
      pendingEffect: null,
      availableActions: ["run_preview"],
    });
  });

  it("persists IDE steps under revision, digest and effect CAS bindings", () => {
    const input = writeJson("flow-cas-config.json", flowConfig());
    runArtifactsDeliveryInit(
      input,
      { json: true },
      { now: "2026-08-01T00:00:00.000Z" },
    );
    let payload = JSON.parse(logs.at(-1));
    const initial = payload.projection;
    const stateFile = writeJson("flow-cas-state.json", payload.state);

    logs = [];
    expect(
      runArtifactsDeliveryStep(
        stateFile,
        {
          action: "run_gates",
          expectedRevision: String(initial.revision),
          expectedStateDigest: initial.stateDigest,
          writeState: true,
          json: true,
        },
        { now: "2026-08-01T00:00:01.000Z" },
      ),
    ).toBe(0);
    payload = JSON.parse(logs.at(-1));
    const pending = payload.projection;
    expect(JSON.parse(fs.readFileSync(stateFile, "utf8"))).toMatchObject({
      revision: pending.revision,
      stateDigest: pending.stateDigest,
      pendingEffect: { id: pending.pendingEffect.id, action: "run_gates" },
    });

    logs = [];
    expect(
      runArtifactsDeliveryStep(stateFile, {
        action: "run_gates",
        expectedRevision: String(initial.revision),
        expectedStateDigest: initial.stateDigest,
        writeState: true,
        json: true,
      }),
    ).toBe(1);
    expect(JSON.parse(logs.at(-1)).error).toMatch(/stale delivery revision/);
    expect(JSON.parse(fs.readFileSync(stateFile, "utf8")).stateDigest).toBe(
      pending.stateDigest,
    );

    const resultFile = writeJson("flow-cas-result.json", {
      schema: "chainlesschain.delivery-action-result",
      version: 1,
      effectId: pending.pendingEffect.id,
      result: {
        commitSha: HEAD,
        results: [
          {
            id: "ci",
            status: "passed",
            commitSha: HEAD,
            matrix: [{ id: "linux", status: "passed", commitSha: HEAD }],
          },
        ],
        sideEffects: [],
      },
    });
    logs = [];
    expect(
      runArtifactsDeliveryStep(
        stateFile,
        {
          resultFile,
          expectedRevision: String(pending.revision),
          expectedStateDigest: pending.stateDigest,
          expectedEffectId: pending.pendingEffect.id,
          writeState: true,
          json: true,
        },
        { now: "2026-08-01T00:00:02.000Z" },
      ),
    ).toBe(0);
    payload = JSON.parse(logs.at(-1));
    expect(payload.projection).toMatchObject({
      phase: "preview",
      pendingEffect: null,
      availableActions: ["run_preview"],
    });
    expect(JSON.parse(fs.readFileSync(stateFile, "utf8")).stateDigest).toBe(
      payload.projection.stateDigest,
    );
  });

  it("projects a valid snapshot and rejects a mutated one", () => {
    const input = writeJson("flow-config-2.json", flowConfig());
    runArtifactsDeliveryInit(
      input,
      { json: true },
      { now: "2026-08-01T00:00:00.000Z" },
    );
    const state = JSON.parse(logs.at(-1)).state;
    const valid = writeJson("valid-state.json", state);
    logs = [];
    expect(runArtifactsDeliveryProject(valid, { json: true })).toBe(0);
    expect(JSON.parse(logs.at(-1)).projection.valid).toBe(true);

    state.phase = "merge";
    const tampered = writeJson("tampered-state.json", state);
    logs = [];
    expect(runArtifactsDeliveryProject(tampered, { json: true })).toBe(1);
    expect(JSON.parse(logs.at(-1)).error).toMatch(/state-digest-mismatch/);
  });

  it("rejects a result envelope bound to another pending effect", () => {
    const pending = requestDeliveryAction(
      createDeliveryFlow(flowConfig(), {
        now: "2026-08-01T00:00:00.000Z",
      }),
      "run_gates",
      {},
      { now: "2026-08-01T00:00:01.000Z" },
    );
    const stateFile = writeJson("bound-state.json", pending);
    const resultFile = writeJson("wrong-effect.json", {
      schema: "chainlesschain.delivery-action-result",
      version: 1,
      effectId: `sha256:${"f".repeat(64)}`,
      result: { commitSha: HEAD, results: [], sideEffects: [] },
    });
    expect(
      runArtifactsDeliveryStep(stateFile, { resultFile, json: true }),
    ).toBe(1);
    expect(JSON.parse(logs.at(-1)).error).toMatch(
      /does not match pending effect/,
    );
  });
});
