// Held-handle physical/logical proof. Physical C: strings are host-bound names;
// opening the physical side uses inherited readonly file handles, never C: ACLs.
HANDLE logicalRootHandle=INVALID_HANDLE_VALUE,physicalRuntimeHandle=INVALID_HANDLE_VALUE,logicalRuntimeHandle=INVALID_HANDLE_VALUE,logicalControlHandle=INVALID_HANDLE_VALUE;
FILE_ID_INFO runtimeIdentity={};
WCHAR privateSession[40]={},privateGeneration[40]={},runtimePhysicalPath[kPathChars]={},runtimeCanonicalNt[kPathChars]={};
std::string runtimeHash;
ULONGLONG runtimeBytes=0;
bool envText(const WCHAR* key,WCHAR* value,DWORD capacity){DWORD size=GetEnvironmentVariableW(key,value,capacity);return size>0&&size<capacity;}
bool captureInherited(const WCHAR* key,HANDLE& retained){WCHAR text[32]={};HANDLE original=nullptr;if(!envText(key,text,32)||!parseHandle(text,original)||!DuplicateHandle(GetCurrentProcess(),original,GetCurrentProcess(),&retained,0,FALSE,DUPLICATE_SAME_ACCESS))return false;if(!CloseHandle(original))return false;return SetEnvironmentVariableW(key,nullptr)!=FALSE;}
std::string privateHash(HANDLE file){BCRYPT_ALG_HANDLE algorithm=nullptr;BCRYPT_HASH_HANDLE hash=nullptr;DWORD objectSize=0,used=0;bool ok=BCryptOpenAlgorithmProvider(&algorithm,BCRYPT_SHA256_ALGORITHM,nullptr,0)==0&&BCryptGetProperty(algorithm,BCRYPT_OBJECT_LENGTH,reinterpret_cast<PUCHAR>(&objectSize),4,&used,0)==0;std::vector<BYTE> object(objectSize),buffer(65536);BYTE digest[32]={};DWORD bytes=0;LARGE_INTEGER zero={};if(ok)ok=BCryptCreateHash(algorithm,&hash,object.data(),objectSize,nullptr,0,0)==0&&SetFilePointerEx(file,zero,nullptr,FILE_BEGIN);while(ok){if(!ReadFile(file,buffer.data(),static_cast<DWORD>(buffer.size()),&bytes,nullptr)){ok=false;break;}if(!bytes)break;ok=BCryptHashData(hash,buffer.data(),bytes,0)==0;}if(ok)ok=BCryptFinishHash(hash,digest,32,0)==0;if(hash)BCryptDestroyHash(hash);if(algorithm)BCryptCloseAlgorithmProvider(algorithm,0);if(!ok)return "";char hex[65]={};for(unsigned i=0;i<32;i++)snprintf(hex+i*2,3,"%02x",digest[i]);return hex;}
bool initializePrivatePair(){
 installStage="paired-inherited-handles";WCHAR expectedNt[kPathChars]={};
 if(!captureInherited(L"CC_PRIVATE_V4_ROOT_HANDLE",rootHandle)||!captureInherited(L"CC_PRIVATE_V4_RUNTIME_HANDLE",physicalRuntimeHandle)||!envText(L"CC_PRIVATE_V4_ROOT_DOS",rootDos,kPathChars)||!envText(L"CC_PRIVATE_V4_ROOT_NT",expectedNt,kPathChars)||!envText(L"CC_PRIVATE_V4_SESSION",privateSession,40)||!envText(L"CC_PRIVATE_V4_GENERATION",privateGeneration,40))return false;
 const WCHAR* plain=nullptr;if(!moduleDrivePath(rootDos,plain)||plain!=rootDos||!plainObject(rootHandle,true)||!normalizedNt(rootHandle,rootNt)||wcscmp(rootNt,expectedNt)||!GetFileInformationByHandleEx(rootHandle,FileIdInfo,&rootId,sizeof(rootId)))return false;
 installStage="paired-logical-root";logicalRootHandle=CreateFileW(L"X:\\",GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_FLAG_BACKUP_SEMANTICS|FILE_FLAG_OPEN_REPARSE_POINT,nullptr);WCHAR logicalNt[kPathChars]={};
 if(logicalRootHandle==INVALID_HANDLE_VALUE||!plainObject(logicalRootHandle,true)||!sameId(logicalRootHandle,rootId)||!normalizedNt(logicalRootHandle,logicalNt)||wcscmp(rootNt,logicalNt))return false;
 installStage="paired-runtime";swprintf(runtimePhysicalPath,kPathChars,L"%ls\\control\\node.exe",rootDos);WCHAR image[kPathChars]={};DWORD imageChars=kPathChars;if(!QueryFullProcessImageNameW(GetCurrentProcess(),0,image,&imageChars)||wcscmp(image,runtimePhysicalPath))return false;
 logicalControlHandle=CreateFileW(L"X:\\control",GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_FLAG_BACKUP_SEMANTICS|FILE_FLAG_OPEN_REPARSE_POINT,nullptr);logicalRuntimeHandle=CreateFileW(L"X:\\control\\node.exe",GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT,nullptr);
 if(logicalControlHandle==INVALID_HANDLE_VALUE||!plainObject(logicalControlHandle,true)||logicalRuntimeHandle==INVALID_HANDLE_VALUE||!plainObject(physicalRuntimeHandle,false)||!plainObject(logicalRuntimeHandle,false)||!GetFileInformationByHandleEx(physicalRuntimeHandle,FileIdInfo,&runtimeIdentity,sizeof(runtimeIdentity))||!sameId(logicalRuntimeHandle,runtimeIdentity)||!normalizedNt(physicalRuntimeHandle,runtimeCanonicalNt)||!normalizedNt(logicalRuntimeHandle,logicalNt)||wcscmp(runtimeCanonicalNt,logicalNt))return false;
 std::wstring expectedRuntime=rootNt;expectedRuntime+=L"\\control\\node.exe";if(expectedRuntime!=runtimeCanonicalNt)return false;
 LARGE_INTEGER size={};if(!GetFileSizeEx(physicalRuntimeHandle,&size)||size.QuadPart!=87074816)return false;runtimeBytes=size.QuadPart;runtimeHash=privateHash(physicalRuntimeHandle);return runtimeHash=="ae1a50511be58e987483fdbc12125407443926d2d394669ade2352776e920dd3"&&privateHash(logicalRuntimeHandle)==runtimeHash;
}
std::string privateJson(const WCHAR* value){std::string result;char utf8[16384]={};if(!WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,value,-1,utf8,sizeof(utf8),nullptr,nullptr))return "";for(const char* c=utf8;*c;c++){if(*c=='\\'||*c=='"')result+='\\';if(static_cast<unsigned char>(*c)<32)return "";result+=*c;}return result;}
std::string privateRecord(HANDLE handle,const WCHAR* path,const char* access,bool directory){FILE_ID_INFO id={};BY_HANDLE_FILE_INFORMATION info={};WCHAR nt[kPathChars]={};if(!GetFileInformationByHandleEx(handle,FileIdInfo,&id,sizeof(id))||!GetFileInformationByHandle(handle,&info)||!normalizedNt(handle,nt)||(info.dwFileAttributes&FILE_ATTRIBUTE_REPARSE_POINT)||bool(info.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)!=directory)return "";char hex[33]={};for(unsigned i=0;i<16;i++)snprintf(hex+2*i,3,"%02x",id.FileId.Identifier[i]);return "{\"path\":\""+privateJson(path)+"\",\"accessMode\":\""+access+"\",\"ntPath\":\""+privateJson(nt)+"\",\"volumeSerial\":\""+std::to_string(id.VolumeSerialNumber)+"\",\"fileId\":\""+hex+"\",\"directory\":"+(directory?"true":"false")+",\"reparse\":false,\"links\":"+std::to_string(info.nNumberOfLinks)+"}";}
std::string privateIdentityJson(){
 if(state!=2||!sameId(rootHandle,rootId)||!sameId(logicalRootHandle,rootId)||!sameId(physicalRuntimeHandle,runtimeIdentity)||!sameId(logicalRuntimeHandle,runtimeIdentity))return "";
 auto physicalRoot=privateRecord(rootHandle,rootDos,"host-inherited-handle",true),logicalRoot=privateRecord(logicalRootHandle,L"X:\\","logical-dos",true),physicalRuntime=privateRecord(physicalRuntimeHandle,runtimePhysicalPath,"host-inherited-handle",false),logicalRuntime=privateRecord(logicalRuntimeHandle,L"X:\\control\\node.exe","logical-dos",false);
 if(physicalRoot.empty()||logicalRoot.empty()||physicalRuntime.empty()||logicalRuntime.empty())return "";
 return "{\"schema\":\"chainlesschain.windows-private-identity/v4\",\"status\":\"NOT_ADMITTED\",\"sessionId\":\""+privateJson(privateSession)+"\",\"generation\":\""+privateJson(privateGeneration)+"\",\"role\":\"root\",\"nodeVersion\":\"22.22.2\",\"modulesAbi\":\"127\",\"token\":{\"appContainerSid\":\""+targetSid+"\",\"capabilityCount\":0,\"inJob\":true},\"root\":{\"physical\":"+physicalRoot+",\"logical\":"+logicalRoot+",\"handlesHeldTogether\":true,\"componentsGuarded\":true},\"runtime\":{\"physical\":"+physicalRuntime+",\"logical\":"+logicalRuntime+",\"handlesHeldTogether\":true,\"componentsGuarded\":true,\"sha256\":\""+runtimeHash+"\",\"bytes\":"+std::to_string(runtimeBytes)+"}}";
}
