"use strict";

const {
  HBuilderXAdapter,
  HBUILDERX_NAME,
  HBUILDERX_VERSION,
  HBUILDERX_WATERMARK_LOOKBACK_MS,
  scopeForRoots,
} = require("./adapter");
const {
  WINDOWS_DATA_DIRECTORY,
  DEFAULT_MAX_ROOTS,
  HARD_MAX_ROOTS,
  DEFAULT_MAX_FILES,
  HARD_MAX_FILES,
  DEFAULT_MAX_FILE_BYTES,
  HARD_MAX_FILE_BYTES,
  DEFAULT_MAX_TOTAL_BYTES,
  HARD_MAX_TOTAL_BYTES,
  DEFAULT_MAX_SECTIONS,
  HARD_MAX_SECTIONS,
  DEFAULT_MAX_LINE_CHARS,
  HARD_MAX_LINE_CHARS,
  DEFAULT_MAX_RECORDS,
  HARD_MAX_RECORDS,
  defaultHBuilderXHomes,
  canonicalHBuilderXRoot,
  canonicalizeRoots,
  discoverHBuilderXIniFiles,
  inspectHBuilderXLocalData,
  resolveSourceTimezone,
  parseHBuilderXDateTime,
  parseActivityIni,
  readHBuilderXFileActivity,
} = require("./hbuilderx-reader");

module.exports = {
  HBuilderXAdapter,
  HBUILDERX_NAME,
  HBUILDERX_VERSION,
  HBUILDERX_WATERMARK_LOOKBACK_MS,
  WINDOWS_DATA_DIRECTORY,
  DEFAULT_MAX_ROOTS,
  HARD_MAX_ROOTS,
  DEFAULT_MAX_FILES,
  HARD_MAX_FILES,
  DEFAULT_MAX_FILE_BYTES,
  HARD_MAX_FILE_BYTES,
  DEFAULT_MAX_TOTAL_BYTES,
  HARD_MAX_TOTAL_BYTES,
  DEFAULT_MAX_SECTIONS,
  HARD_MAX_SECTIONS,
  DEFAULT_MAX_LINE_CHARS,
  HARD_MAX_LINE_CHARS,
  DEFAULT_MAX_RECORDS,
  HARD_MAX_RECORDS,
  scopeForRoots,
  defaultHBuilderXHomes,
  canonicalHBuilderXRoot,
  canonicalizeRoots,
  discoverHBuilderXIniFiles,
  inspectHBuilderXLocalData,
  resolveSourceTimezone,
  parseHBuilderXDateTime,
  parseActivityIni,
  readHBuilderXFileActivity,
};
