/**
 * Integration tests for the ai-doc-creator template generated by `cc init`.
 *
 * Runs `chainlesschain init --template ai-doc-creator --yes` in a temp dir,
 * then imports the generated handler.js files via createRequire and exercises
 * their parameter validation + tool-detection branches without any real
 * filesystem conversion tools present.
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { execSync } from "node:child_process";
import { createRequire } from "node:module";
import { mkdtempSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const cliRoot = join(__dirname, "..", "..");
const bin = join(cliRoot, "bin", "chainlesschain.js");

// ─── Setup: run cc init once ────────────────────────────────────────────────

let tmpDir;
let docGenerateHandler;
let libreConvertHandler;

beforeAll(() => {
  tmpDir = mkdtempSync(join(tmpdir(), "cc-ai-doc-creator-test-"));

  execSync(`node "${bin}" init --template ai-doc-creator --yes`, {
    cwd: tmpDir,
    encoding: "utf-8",
    timeout: 30000,
  });

  const req = createRequire(pathToFileURL(join(tmpDir, "index.js")).href);
  docGenerateHandler = req(
    join(tmpDir, ".chainlesschain", "skills", "doc-generate", "handler.js"),
  );
  libreConvertHandler = req(
    join(tmpDir, ".chainlesschain", "skills", "libre-convert", "handler.js"),
  );
}, 45000);

afterAll(() => {
  if (tmpDir) {
    rmSync(tmpDir, { recursive: true, force: true });
  }
});

// ─── Filesystem structure ────────────────────────────────────────────────────

describe("ai-doc-creator init: filesystem structure", () => {
  it("creates .chainlesschain directory", () => {
    expect(existsSync(join(tmpDir, ".chainlesschain"))).toBe(true);
  });

  it("creates config.json with ai-doc-creator template", () => {
    const config = JSON.parse(
      require("node:fs").readFileSync(
        join(tmpDir, ".chainlesschain", "config.json"),
        "utf-8",
      ),
    );
    expect(config.template).toBe("ai-doc-creator");
  });

  it("creates doc-generate skill directory", () => {
    expect(
      existsSync(join(tmpDir, ".chainlesschain", "skills", "doc-generate")),
    ).toBe(true);
  });

  it("creates libre-convert skill directory", () => {
    expect(
      existsSync(join(tmpDir, ".chainlesschain", "skills", "libre-convert")),
    ).toBe(true);
  });

  it("creates templates/ companion directory", () => {
    expect(existsSync(join(tmpDir, "templates"))).toBe(true);
  });

  it("creates templates/README.md", () => {
    expect(existsSync(join(tmpDir, "templates", "README.md"))).toBe(true);
  });

  it("README.md contains doc-generate usage", () => {
    const content = require("node:fs").readFileSync(
      join(tmpDir, "templates", "README.md"),
      "utf-8",
    );
    expect(content).toContain("doc-generate");
    expect(content).toContain("libre-convert");
  });

  it("creates doc-generate SKILL.md", () => {
    expect(
      existsSync(
        join(tmpDir, ".chainlesschain", "skills", "doc-generate", "SKILL.md"),
      ),
    ).toBe(true);
  });

  it("creates doc-generate handler.js", () => {
    expect(
      existsSync(
        join(tmpDir, ".chainlesschain", "skills", "doc-generate", "handler.js"),
      ),
    ).toBe(true);
  });

  it("creates libre-convert SKILL.md", () => {
    expect(
      existsSync(
        join(tmpDir, ".chainlesschain", "skills", "libre-convert", "SKILL.md"),
      ),
    ).toBe(true);
  });

  it("creates libre-convert handler.js", () => {
    expect(
      existsSync(
        join(
          tmpDir,
          ".chainlesschain",
          "skills",
          "libre-convert",
          "handler.js",
        ),
      ),
    ).toBe(true);
  });

  it("creates ai-doc-creator-persona skill directory", () => {
    expect(
      existsSync(
        join(tmpDir, ".chainlesschain", "skills", "ai-doc-creator-persona"),
      ),
    ).toBe(true);
  });

  it("does NOT create workflows/ directory (uses templates/ instead)", () => {
    expect(existsSync(join(tmpDir, "workflows"))).toBe(false);
  });
});

// ─── doc-generate handler: parameter validation ───────────────────────────

describe("doc-generate handler: parameter validation", () => {
  it("returns error when topic is missing", async () => {
    const result = await docGenerateHandler({});
    expect(result).toHaveProperty("error");
    expect(result.error).toContain("topic");
  });

  it("returns error when topic is empty string", async () => {
    const result = await docGenerateHandler({ topic: "" });
    expect(result).toHaveProperty("error");
    expect(result.error).toContain("topic");
  });

  it("returns structured error for unsupported format", async () => {
    // Use a valid topic; if LLM not available it still writes md then tries conversion
    // We intercept via unsupported format
    const result = await docGenerateHandler({
      topic: "Test",
      format: "xyz_unsupported",
    });
    expect(result).toHaveProperty("error");
    expect(result.error).toMatch(/Unsupported format/i);
    expect(result).toHaveProperty("hint");
    expect(result.hint).toContain("Supported formats");
  });
});

// ─── doc-generate handler: md format (no conversion tools needed) ────────

describe("doc-generate handler: md format output", () => {
  it("generates a markdown file when format=md", async () => {
    const result = await docGenerateHandler({
      topic: "Integration Test Report",
      format: "md",
    });
    // Either success (LLM available) or fallback template; both should succeed
    expect(result).toHaveProperty("success", true);
    expect(result.format).toBe("md");
    expect(result.output).toMatch(/\.md$/);
    expect(existsSync(result.output)).toBe(true);
  }, 15000);

  it("returns wordCount in result for md format", async () => {
    const result = await docGenerateHandler({
      topic: "Word Count Check",
      format: "md",
    });
    expect(result.success).toBe(true);
    expect(typeof result.wordCount).toBe("number");
    expect(result.wordCount).toBeGreaterThan(0);
  }, 15000);

  it("sanitizes special characters in output filename", async () => {
    const result = await docGenerateHandler({
      topic: "Test: Report with / special chars!",
      format: "md",
    });
    expect(result.success).toBe(true);
    // Check only the basename (not full path which may include drive letter on Windows)
    const basename = require("node:path").basename(result.output);
    expect(basename).not.toContain(":");
    expect(basename).not.toContain("!");
  }, 15000);

  it("uses custom output name when provided", async () => {
    const result = await docGenerateHandler({
      topic: "A Long Topic Name That Should Be Overridden",
      format: "md",
      output: "my_custom_doc",
    });
    expect(result.success).toBe(true);
    expect(result.output).toContain("my_custom_doc");
  }, 15000);
});

// ─── doc-generate handler: html format ──────────────────────────────────

describe("doc-generate handler: html format output", () => {
  it("generates an html file when format=html", async () => {
    const result = await docGenerateHandler({
      topic: "HTML Integration Test",
      format: "html",
    });
    expect(result.success).toBe(true);
    expect(result.format).toBe("html");
    expect(result.output).toMatch(/\.html$/);
    expect(existsSync(result.output)).toBe(true);
  }, 15000);

  it("also writes .md companion for html output", async () => {
    const result = await docGenerateHandler({
      topic: "HTML With MD Companion",
      format: "html",
    });
    expect(result.success).toBe(true);
    expect(result).toHaveProperty("mdOutput");
    expect(existsSync(result.mdOutput)).toBe(true);
  }, 15000);
});

// ─── doc-generate handler: docx/pdf fallback when no tools ──────────────

describe("doc-generate handler: docx/pdf fallback (no pandoc/soffice)", () => {
  it("falls back to md when docx requested but no tools available", async () => {
    // In CI/test environment, pandoc and soffice are typically not installed
    const result = await docGenerateHandler({
      topic: "Docx Fallback Test",
      format: "docx",
    });
    // Either converts successfully or falls back gracefully
    expect(result.success).toBe(true);
    if (result.format === "md") {
      expect(result.message).toContain("pandoc");
    } else {
      expect(["docx", "md"]).toContain(result.format);
    }
  }, 20000);

  it("falls back to md when pdf requested but no tools available", async () => {
    const result = await docGenerateHandler({
      topic: "PDF Fallback Test",
      format: "pdf",
    });
    expect(result.success).toBe(true);
    if (result.format === "md") {
      expect(result.message).toContain("LibreOffice");
    } else {
      expect(["pdf", "md"]).toContain(result.format);
    }
  }, 20000);
});

// ─── libre-convert handler: parameter validation ─────────────────────────

describe("libre-convert handler: parameter validation", () => {
  it("returns error when input_file is missing", async () => {
    const result = await libreConvertHandler({});
    expect(result).toHaveProperty("error");
    expect(result.error).toContain("input_file");
  });

  it("returns error when input_file is empty string", async () => {
    const result = await libreConvertHandler({ input_file: "" });
    expect(result).toHaveProperty("error");
    expect(result.error).toContain("input_file");
  });

  it("returns structured error for unsupported format", async () => {
    const result = await libreConvertHandler({
      input_file: "test.docx",
      format: "xyz_unsupported",
    });
    expect(result).toHaveProperty("error");
    expect(result.error).toMatch(/Unsupported format/i);
    expect(result).toHaveProperty("hint");
  });

  it("returns error when input file does not exist", async () => {
    const result = await libreConvertHandler({
      input_file: "/nonexistent/path/file.docx",
      format: "pdf",
    });
    expect(result).toHaveProperty("error");
    expect(result.error).toContain("Input file not found");
  });
});

// ─── libre-convert handler: LibreOffice not found ────────────────────────

describe("libre-convert handler: LibreOffice not-found path", () => {
  it("returns error with install hint when LibreOffice not available", async () => {
    // Create a real file so we pass the file-exists check
    const fs = require("node:fs");
    const testFile = join(tmpDir, "dummy_input.txt");
    fs.writeFileSync(testFile, "test content", "utf-8");

    const result = await libreConvertHandler({
      input_file: testFile,
      format: "pdf",
    });

    // If soffice IS in PATH (unlikely in CI), this would succeed; otherwise error
    if (!result.success) {
      expect(result.error).toMatch(/LibreOffice not found|Failed to launch/i);
      expect(result.hint).toBeTruthy();
    }
  });

  it("error hint contains cli-anything register soffice tip", async () => {
    const fs = require("node:fs");
    const testFile = join(tmpDir, "dummy_input2.txt");
    fs.writeFileSync(testFile, "test content", "utf-8");

    const result = await libreConvertHandler({
      input_file: testFile,
      format: "pdf",
    });

    if (!result.success && result.error?.includes("LibreOffice not found")) {
      expect(result.hint).toContain("cli-anything register soffice");
    }
  });
});

// ─── UTF-8 integrity ────────────────────────────────────────────────────────

describe("generated handler files: UTF-8 integrity", () => {
  it("doc-generate handler.js has no UTF-8 replacement characters", () => {
    const fs = require("node:fs");
    const content = fs.readFileSync(
      join(tmpDir, ".chainlesschain", "skills", "doc-generate", "handler.js"),
      "utf-8",
    );
    expect(content).not.toContain("\uFFFD");
  });

  it("libre-convert handler.js has no UTF-8 replacement characters", () => {
    const fs = require("node:fs");
    const content = fs.readFileSync(
      join(tmpDir, ".chainlesschain", "skills", "libre-convert", "handler.js"),
      "utf-8",
    );
    expect(content).not.toContain("\uFFFD");
  });

  it("templates/README.md has no UTF-8 replacement characters", () => {
    const fs = require("node:fs");
    const content = fs.readFileSync(
      join(tmpDir, "templates", "README.md"),
      "utf-8",
    );
    expect(content).not.toContain("\uFFFD");
  });
});

// ─── doc-edit skill: filesystem structure ───────────────────────────────────

describe("ai-doc-creator init: doc-edit skill structure", () => {
  it("creates doc-edit skill directory", () => {
    expect(
      existsSync(join(tmpDir, ".chainlesschain", "skills", "doc-edit")),
    ).toBe(true);
  });

  it("creates doc-edit SKILL.md", () => {
    expect(
      existsSync(
        join(tmpDir, ".chainlesschain", "skills", "doc-edit", "SKILL.md"),
      ),
    ).toBe(true);
  });

  it("creates doc-edit handler.js", () => {
    expect(
      existsSync(
        join(tmpDir, ".chainlesschain", "skills", "doc-edit", "handler.js"),
      ),
    ).toBe(true);
  });

  it("doc-edit handler.js has no UTF-8 replacement characters", () => {
    const fs = require("node:fs");
    const content = fs.readFileSync(
      join(tmpDir, ".chainlesschain", "skills", "doc-edit", "handler.js"),
      "utf-8",
    );
    expect(content).not.toContain("\uFFFD");
  });
});

// ─── doc-edit handler: parameter validation ──────────────────────────────────

describe("doc-edit handler: parameter validation", () => {
  let docEditHandler;

  beforeAll(() => {
    const req = createRequire(pathToFileURL(join(tmpDir, "index.js")).href);
    docEditHandler = req(
      join(tmpDir, ".chainlesschain", "skills", "doc-edit", "handler.js"),
    );
  });

  it("returns error when input_file is missing", async () => {
    const result = await docEditHandler({});
    expect(result).toHaveProperty("success", false);
    expect(result.error).toContain("input_file");
  });

  it("returns error when instruction is missing", async () => {
    const result = await docEditHandler({ input_file: "test.md" });
    expect(result).toHaveProperty("success", false);
    expect(result.error).toContain("instruction");
  });

  it("returns error when input file does not exist", async () => {
    const result = await docEditHandler({
      input_file: "/nonexistent/path/test.md",
      instruction: "Make it better",
    });
    expect(result).toHaveProperty("success", false);
    expect(result.error).toContain("Input file not found");
  });

  it("returns structured error for unsupported format", async () => {
    const fs = require("node:fs");
    const testFile = join(tmpDir, "test_unsupported.xyz");
    fs.writeFileSync(testFile, "test content", "utf-8");

    const result = await docEditHandler({
      input_file: testFile,
      instruction: "Improve this",
    });
    expect(result).toHaveProperty("success", false);
    expect(result.error).toContain(".xyz");
    expect(result).toHaveProperty("hint");
    expect(result.hint).toContain("md");
    expect(result.hint).toContain("xlsx");
  });

  it("returns error for invalid action", async () => {
    const fs = require("node:fs");
    const testFile = join(tmpDir, "test_action.md");
    fs.writeFileSync(testFile, "# Hello\n\nContent.", "utf-8");

    const result = await docEditHandler({
      input_file: testFile,
      instruction: "Fix it",
      action: "invalid-action",
    });
    expect(result).toHaveProperty("success", false);
    expect(result.error).toContain("action");
    expect(result).toHaveProperty("hint");
  });
});

// ─── doc-edit handler: md format ─────────────────────────────────────────────

describe("doc-edit handler: md format editing", () => {
  let docEditHandler;

  beforeAll(() => {
    const req = createRequire(pathToFileURL(join(tmpDir, "index.js")).href);
    docEditHandler = req(
      join(tmpDir, ".chainlesschain", "skills", "doc-edit", "handler.js"),
    );
  });

  it("produces _edited.md output file (LLM available or error)", async () => {
    const fs = require("node:fs");
    const testFile = join(tmpDir, "source_doc.md");
    fs.writeFileSync(
      testFile,
      "# Source Document\n\nOriginal content here.",
      "utf-8",
    );

    const result = await docEditHandler({
      input_file: testFile,
      instruction: "Make the tone more formal",
    });

    // LLM may or may not be available in test env, but structure must be valid
    if (result.success) {
      expect(result.output).toMatch(/_edited\.md$/);
      expect(existsSync(result.output)).toBe(true);
    } else {
      expect(result.error).toBeTruthy();
    }
  }, 20000);

  it("does not overwrite original file", async () => {
    const fs = require("node:fs");
    const testFile = join(tmpDir, "original_preserved.md");
    const originalContent = "# Original\n\nThis must not be overwritten.";
    fs.writeFileSync(testFile, originalContent, "utf-8");

    await docEditHandler({
      input_file: testFile,
      instruction: "Change everything",
    });

    // Original must be intact regardless of success/failure
    const afterContent = fs.readFileSync(testFile, "utf-8");
    expect(afterContent).toBe(originalContent);
  }, 20000);
});

// ─── doc-edit handler: xlsx/pptx Python dependency checks ────────────────────

describe("doc-edit handler: xlsx/pptx Python dependency detection", () => {
  let docEditHandler;

  beforeAll(() => {
    const req = createRequire(pathToFileURL(join(tmpDir, "index.js")).href);
    docEditHandler = req(
      join(tmpDir, ".chainlesschain", "skills", "doc-edit", "handler.js"),
    );
  });

  it("xlsx: returns error when xlsx cannot be processed (no Python, no openpyxl, or invalid file)", async () => {
    const fs = require("node:fs");
    // Create a minimal fake xlsx (not valid, just needs to exist)
    const testXlsx = join(tmpDir, "fake.xlsx");
    fs.writeFileSync(testXlsx, "PK fake xlsx content", "utf-8");

    const result = await docEditHandler({
      input_file: testXlsx,
      instruction: "Capitalize all names",
    });

    // Three possible outcomes:
    // 1. No Python → error mentions Python + hint with python.org
    // 2. No openpyxl → error mentions openpyxl + hint with pip install
    // 3. Python+openpyxl available but file is invalid → XLSX 修改失败 error (no hint required)
    if (!result.success) {
      expect(result.error).toBeTruthy();
      if (result.hint !== undefined) {
        // When hint is provided, it should relate to Python or pip
        expect(result.hint).toMatch(/python\.org|pip install/i);
      }
    }
  }, 15000);

  it("pptx: returns error with python-pptx pip hint when python-pptx not installed", async () => {
    const fs = require("node:fs");
    const testPptx = join(tmpDir, "fake.pptx");
    fs.writeFileSync(testPptx, "PK fake pptx content", "utf-8");

    const result = await docEditHandler({
      input_file: testPptx,
      instruction: "Make text more formal",
    });

    if (!result.success) {
      expect(result.error.toLowerCase()).toMatch(/python-pptx|python|pptx/);
      if (result.hint) {
        expect(result.hint).toMatch(/python\.org|pip install/);
      }
    }
  }, 15000);

  it("docx: returns structured fallback error when no pandoc/soffice available", async () => {
    const fs = require("node:fs");
    const testDocx = join(tmpDir, "fake.docx");
    fs.writeFileSync(testDocx, "PK fake docx content", "utf-8");

    const result = await docEditHandler({
      input_file: testDocx,
      instruction: "Improve grammar",
    });

    // Either succeeds (if pandoc/soffice present) or returns structured error
    if (!result.success) {
      expect(result.error).toBeTruthy();
      expect(result).toHaveProperty("hint");
      expect(result.hint.toLowerCase()).toMatch(/pandoc|libreoffice/);
    }
  }, 20000);
});
