/**
 * Memory Bank Store — V6 thin store for the Memory Bank dashboard
 * (AI learning patterns / preferences / sessions / behavior insights /
 *  storage stats / auto-summary).
 *
 * Distinct from `stores/memory.ts` which manages daily-notes & search.
 * This store wraps `memory:*` IPC for the V5→V6 dashboard port.
 */

import { defineStore } from "pinia";
import { logger } from "@/utils/logger";

// ===== IPC accessor (window.electronAPI.invoke) =====

interface ElectronInvokeAPI {
  invoke: (channel: string, ...args: unknown[]) => Promise<unknown>;
}

function getInvoke(): ElectronInvokeAPI["invoke"] | null {
  const api = (window as unknown as { electronAPI?: ElectronInvokeAPI })
    .electronAPI;
  return typeof api?.invoke === "function" ? api.invoke.bind(api) : null;
}

// ===== Types =====

export interface PromptPattern {
  id?: string;
  category?: string;
  template?: string;
  use_count?: number;
  [key: string]: unknown;
}

export interface ErrorFixPattern {
  id?: string;
  error_classification?: string;
  fix_strategy?: string;
  success_count?: number;
  failure_count?: number;
  [key: string]: unknown;
}

export interface CodeSnippet {
  id?: string;
  name?: string;
  language?: string;
  description?: string;
  code?: string;
  [key: string]: unknown;
}

export interface WorkflowPattern {
  id?: string;
  name?: string;
  steps?: unknown[];
  execution_count?: number;
  [key: string]: unknown;
}

export interface UserPreference {
  category?: string;
  key?: string;
  value?: unknown;
  updated_at?: number | string;
  [key: string]: unknown;
}

export interface RecentSession {
  id?: string;
  title?: string;
  messageCount?: number;
  updated_at?: number | string;
  has_summary?: boolean | number;
  [key: string]: unknown;
}

export interface BehaviorRecommendation {
  id?: string;
  type?: string;
  title?: string;
  description?: string;
  [key: string]: unknown;
}

export interface StorageStats {
  totalFiles: number;
  totalSize: number;
  lastBackup: number | string | null;
}

export interface AutoSummaryConfig {
  enabled: boolean;
  threshold: number;
  interval: number;
  backgroundEnabled: boolean;
  isRunning: boolean;
  queueLength: number;
}

export interface AutoSummaryStats {
  totalSessions: number;
  withSummary: number;
  withoutSummary: number;
  autoGenerated: number;
  coverage: number;
}

export interface ExportType {
  type: "all" | "patterns" | "preferences" | "sessions";
}

export interface MemoryBankState {
  // patterns
  promptPatterns: PromptPattern[];
  errorFixPatterns: ErrorFixPattern[];
  codeSnippets: CodeSnippet[];
  workflowPatterns: WorkflowPattern[];

  // preferences / sessions / behavior
  preferences: UserPreference[];
  recentSessions: RecentSession[];
  behaviorInsights: Record<string, unknown>;
  recommendations: BehaviorRecommendation[];

  // storage
  memoryPath: string;
  storageStats: StorageStats;

  // auto-summary
  autoSummaryConfig: AutoSummaryConfig;
  autoSummaryStats: AutoSummaryStats;

  // loading flags
  loading: boolean;
  hasLoaded: boolean;
  exporting: boolean;
  backingUp: boolean;
  cleaningUp: boolean;
  triggeringBulk: boolean;
  loadingAutoSummary: boolean;
}

// ===== Store =====

export const useMemoryBankStore = defineStore("memoryBank", {
  state: (): MemoryBankState => ({
    promptPatterns: [],
    errorFixPatterns: [],
    codeSnippets: [],
    workflowPatterns: [],
    preferences: [],
    recentSessions: [],
    behaviorInsights: {},
    recommendations: [],
    memoryPath: "",
    storageStats: { totalFiles: 0, totalSize: 0, lastBackup: null },
    autoSummaryConfig: {
      enabled: false,
      threshold: 5,
      interval: 60000,
      backgroundEnabled: false,
      isRunning: false,
      queueLength: 0,
    },
    autoSummaryStats: {
      totalSessions: 0,
      withSummary: 0,
      withoutSummary: 0,
      autoGenerated: 0,
      coverage: 0,
    },
    loading: false,
    hasLoaded: false,
    exporting: false,
    backingUp: false,
    cleaningUp: false,
    triggeringBulk: false,
    loadingAutoSummary: false,
  }),

  getters: {
    totalPatterns(): number {
      return (
        this.promptPatterns.length +
        this.errorFixPatterns.length +
        this.codeSnippets.length +
        this.workflowPatterns.length
      );
    },
    totalPreferences(): number {
      return this.preferences.length;
    },
    totalSessions(): number {
      return this.recentSessions.length;
    },
    totalInsights(): number {
      return this.recommendations.length;
    },
  },

  actions: {
    async loadPatterns(): Promise<void> {
      const invoke = getInvoke();
      if (!invoke) {
        return;
      }
      try {
        const result = (await invoke("memory:get-all-patterns")) as {
          promptPatterns?: PromptPattern[];
          errorFixPatterns?: ErrorFixPattern[];
          codeSnippets?: CodeSnippet[];
          workflowPatterns?: WorkflowPattern[];
        } | null;
        this.promptPatterns = result?.promptPatterns ?? [];
        this.errorFixPatterns = result?.errorFixPatterns ?? [];
        this.codeSnippets = result?.codeSnippets ?? [];
        this.workflowPatterns = result?.workflowPatterns ?? [];
      } catch (error) {
        logger.warn("[MemoryBank] loadPatterns 失败:", error as Error);
      }
    },

    async loadPreferences(): Promise<void> {
      const invoke = getInvoke();
      if (!invoke) {
        return;
      }
      try {
        const result = (await invoke("memory:get-all-preferences")) as
          | UserPreference[]
          | null;
        this.preferences = Array.isArray(result) ? result : [];
      } catch (error) {
        logger.warn("[MemoryBank] loadPreferences 失败:", error as Error);
      }
    },

    async loadSessions(limit = 20): Promise<void> {
      const invoke = getInvoke();
      if (!invoke) {
        return;
      }
      try {
        const result = (await invoke("session:get-recent", limit)) as
          | RecentSession[]
          | null;
        this.recentSessions = Array.isArray(result) ? result : [];
      } catch (error) {
        logger.warn("[MemoryBank] loadSessions 失败:", error as Error);
      }
    },

    async loadBehaviorInsights(): Promise<void> {
      const invoke = getInvoke();
      if (!invoke) {
        return;
      }
      try {
        const result = (await invoke("memory:get-behavior-insights")) as {
          insights?: Record<string, unknown>;
          recommendations?: BehaviorRecommendation[];
        } | null;
        this.behaviorInsights = result?.insights ?? {};
        this.recommendations = result?.recommendations ?? [];
      } catch (error) {
        logger.warn("[MemoryBank] loadBehaviorInsights 失败:", error as Error);
      }
    },

    async loadStorageStats(): Promise<void> {
      const invoke = getInvoke();
      if (!invoke) {
        return;
      }
      try {
        const result = (await invoke("memory:get-storage-stats")) as {
          memoryPath?: string;
          totalFiles?: number;
          totalSize?: number;
          lastBackup?: number | string | null;
        } | null;
        this.memoryPath = result?.memoryPath ?? "";
        this.storageStats = {
          totalFiles: result?.totalFiles ?? 0,
          totalSize: result?.totalSize ?? 0,
          lastBackup: result?.lastBackup ?? null,
        };
      } catch (error) {
        logger.warn("[MemoryBank] loadStorageStats 失败:", error as Error);
      }
    },

    async refreshAll(): Promise<void> {
      this.loading = true;
      try {
        await Promise.allSettled([
          this.loadPatterns(),
          this.loadPreferences(),
          this.loadSessions(),
          this.loadBehaviorInsights(),
          this.loadStorageStats(),
          this.loadAutoSummaryInfo(),
        ]);
        this.hasLoaded = true;
      } finally {
        this.loading = false;
      }
    },

    /**
     * Export Memory Bank data. Returns the result envelope so the caller
     * can surface filePath / error to the user. Sets exporting flag.
     */
    async exportData(
      type: "all" | "patterns" | "preferences" | "sessions",
    ): Promise<{ success: boolean; filePath?: string; error?: string }> {
      const invoke = getInvoke();
      if (!invoke) {
        return { success: false, error: "IPC 不可用" };
      }
      this.exporting = true;
      try {
        const result = (await invoke("memory:export-data", { type })) as {
          success?: boolean;
          filePath?: string;
          error?: string;
        } | null;
        if (result && result.success) {
          return { success: true, filePath: result.filePath };
        }
        return {
          success: false,
          error: result?.error ?? "导出失败",
        };
      } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        logger.error("[MemoryBank] exportData 失败:", error as Error);
        return { success: false, error: msg };
      } finally {
        this.exporting = false;
      }
    },

    async createBackup(): Promise<{
      success: boolean;
      backupPath?: string;
      error?: string;
    }> {
      const invoke = getInvoke();
      if (!invoke) {
        return { success: false, error: "IPC 不可用" };
      }
      this.backingUp = true;
      try {
        const result = (await invoke("memory:create-backup")) as {
          success?: boolean;
          backupPath?: string;
          error?: string;
        } | null;
        if (result && result.success) {
          await this.loadStorageStats();
          return { success: true, backupPath: result.backupPath };
        }
        return { success: false, error: result?.error ?? "备份失败" };
      } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        logger.error("[MemoryBank] createBackup 失败:", error as Error);
        return { success: false, error: msg };
      } finally {
        this.backingUp = false;
      }
    },

    async cleanupExpired(): Promise<{
      success: boolean;
      removed?: number;
      error?: string;
    }> {
      const invoke = getInvoke();
      if (!invoke) {
        return { success: false, error: "IPC 不可用" };
      }
      this.cleaningUp = true;
      try {
        const result = (await invoke("memory:cleanup-expired")) as {
          success?: boolean;
          removed?: number;
          error?: string;
        } | null;
        if (result && result.success) {
          await this.loadStorageStats();
          return { success: true, removed: result.removed };
        }
        return { success: false, error: result?.error ?? "清理失败" };
      } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        logger.error("[MemoryBank] cleanupExpired 失败:", error as Error);
        return { success: false, error: msg };
      } finally {
        this.cleaningUp = false;
      }
    },

    async openMemoryFolder(): Promise<void> {
      const invoke = getInvoke();
      if (!invoke || !this.memoryPath) {
        return;
      }
      try {
        await invoke("shell:open-path", this.memoryPath);
      } catch (error) {
        logger.warn("[MemoryBank] openMemoryFolder 失败:", error as Error);
      }
    },

    async loadAutoSummaryInfo(): Promise<void> {
      const invoke = getInvoke();
      if (!invoke) {
        return;
      }
      this.loadingAutoSummary = true;
      try {
        const result = (await invoke("memory:get-auto-summary-info")) as {
          config?: Partial<AutoSummaryConfig>;
          stats?: Partial<AutoSummaryStats>;
        } | null;
        if (result?.config) {
          this.autoSummaryConfig = {
            enabled: !!result.config.enabled,
            threshold: Number(result.config.threshold ?? 5),
            interval: Number(result.config.interval ?? 60000),
            backgroundEnabled: !!result.config.backgroundEnabled,
            isRunning: !!result.config.isRunning,
            queueLength: Number(result.config.queueLength ?? 0),
          };
        }
        if (result?.stats) {
          this.autoSummaryStats = {
            totalSessions: Number(result.stats.totalSessions ?? 0),
            withSummary: Number(result.stats.withSummary ?? 0),
            withoutSummary: Number(result.stats.withoutSummary ?? 0),
            autoGenerated: Number(result.stats.autoGenerated ?? 0),
            coverage: Number(result.stats.coverage ?? 0),
          };
        }
      } catch (error) {
        logger.warn("[MemoryBank] loadAutoSummaryInfo 失败:", error as Error);
      } finally {
        this.loadingAutoSummary = false;
      }
    },

    async triggerBulkSummary(
      options: { limit?: number; overwrite?: boolean } = {},
    ): Promise<{ success: boolean; processed?: number; error?: string }> {
      const invoke = getInvoke();
      if (!invoke) {
        return { success: false, error: "IPC 不可用" };
      }
      this.triggeringBulk = true;
      try {
        const result = (await invoke("memory:trigger-auto-summaries", {
          limit: options.limit ?? 20,
          overwrite: !!options.overwrite,
        })) as {
          success?: boolean;
          processed?: number;
          error?: string;
        } | null;
        await this.loadAutoSummaryInfo();
        if (result && result.success) {
          return { success: true, processed: result.processed };
        }
        return {
          success: false,
          error: result?.error ?? "批量生成摘要失败",
        };
      } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        logger.error("[MemoryBank] triggerBulkSummary 失败:", error as Error);
        return { success: false, error: msg };
      } finally {
        this.triggeringBulk = false;
      }
    },
  },
});
