// Independent v4 experiment. The host creates both processes and retains every
// authoritative process handle. Requests carry only three stdio handle values
// from the registered root process; no PID or borrowed process handle is used.
#define wmain privateMapLeafMain
#include "windows-esbuild-private-map-supervisor.cpp"
#undef wmain
#include "windows-node-private-v4-protocol.h"

static std::string fileDigest(HANDLE file) {
 BCRYPT_ALG_HANDLE algorithm=nullptr;BCRYPT_HASH_HANDLE hash=nullptr;DWORD objectBytes=0,used=0;std::string result;
 bool ok=BCryptOpenAlgorithmProvider(&algorithm,BCRYPT_SHA256_ALGORITHM,nullptr,0)==0&&BCryptGetProperty(algorithm,BCRYPT_OBJECT_LENGTH,reinterpret_cast<PUCHAR>(&objectBytes),sizeof(objectBytes),&used,0)==0;
 std::vector<BYTE> object(objectBytes),buffer(65536);BYTE bytes[32]={};LARGE_INTEGER zero={};DWORD count=0;
 if(ok)ok=BCryptCreateHash(algorithm,&hash,object.data(),objectBytes,nullptr,0,0)==0&&SetFilePointerEx(file,zero,nullptr,FILE_BEGIN);
 while(ok){if(!ReadFile(file,buffer.data(),static_cast<DWORD>(buffer.size()),&count,nullptr)){ok=false;break;}if(!count)break;ok=BCryptHashData(hash,buffer.data(),count,0)==0;}
 if(ok)ok=BCryptFinishHash(hash,bytes,32,0)==0;if(hash)BCryptDestroyHash(hash);if(algorithm)BCryptCloseAlgorithmProvider(algorithm,0);
 if(ok){char hex[65]={};for(unsigned i=0;i<32;i++)std::snprintf(hex+2*i,3,"%02x",bytes[i]);result=hex;}return result;
}
static bool guardPrivateTree(Handles& handles,const std::wstring& directory,const std::wstring& owner,const std::wstring& sid,DWORD& count){
 if(++count>16000||!protect(directory,owner,sid)||pin(handles,directory,true)==INVALID_HANDLE_VALUE)return false;
 WIN32_FIND_DATAW row={};HANDLE search=FindFirstFileW((directory+L"\\*").c_str(),&row);if(search==INVALID_HANDLE_VALUE)return false;bool ok=true;
 do{if(!wcscmp(row.cFileName,L".")||!wcscmp(row.cFileName,L".."))continue;const auto name=directory+L"\\"+row.cFileName;if(row.dwFileAttributes&FILE_ATTRIBUTE_REPARSE_POINT){ok=false;break;}
 if(row.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY){if(!guardPrivateTree(handles,name,owner,sid,count)){ok=false;break;}}
 else if(++count>16000||!protect(name,owner,sid)||pin(handles,name,false)==INVALID_HANDLE_VALUE){ok=false;break;}
 }while(FindNextFileW(search,&row));DWORD error=GetLastError();FindClose(search);return ok&&error==ERROR_NO_MORE_FILES;
}
static std::wstring handleText(HANDLE handle){WCHAR value[32]={};swprintf(value,32,L"%llx",static_cast<unsigned long long>(reinterpret_cast<uintptr_t>(handle)));return value;}
static std::string randomUuid(){BYTE bytes[16];if(BCryptGenRandom(nullptr,bytes,16,BCRYPT_USE_SYSTEM_PREFERRED_RNG)!=0)return "";bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;char text[37]={};std::snprintf(text,37,"%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",bytes[0],bytes[1],bytes[2],bytes[3],bytes[4],bytes[5],bytes[6],bytes[7],bytes[8],bytes[9],bytes[10],bytes[11],bytes[12],bytes[13],bytes[14],bytes[15]);return text;}
static std::wstring widen(const std::string& value){return std::wstring(value.begin(),value.end());}
static bool writeFresh(const std::wstring& path,const std::string& text){HANDLE file=CreateFileW(path.c_str(),GENERIC_WRITE,0,nullptr,CREATE_NEW,FILE_ATTRIBUTE_NORMAL|FILE_FLAG_OPEN_REPARSE_POINT,nullptr);if(file==INVALID_HANDLE_VALUE)return false;DWORD written=0;bool ok=WriteFile(file,text.data(),static_cast<DWORD>(text.size()),&written,nullptr)&&written==text.size()&&FlushFileBuffers(file);CloseHandle(file);return ok;}
static bool stdioObject(HANDLE source,unsigned index,DWORD callerPid,HANDLE expectedDisk,DWORD& wanted){
 using QueryFn=LONG(NTAPI*)(HANDLE,ULONG,PVOID,ULONG,PULONG);auto query=reinterpret_cast<QueryFn>(GetProcAddress(GetModuleHandleW(L"ntdll.dll"),"NtQueryObject"));if(!query)return false;
 struct NativeName{USHORT length,capacity;PWSTR value;};alignas(void*) BYTE nameBytes[4096]={},basic[56]={};ULONG used=0,granted=0;if(query(source,0,basic,sizeof(basic),&used)<0||used<8)return false;memcpy(&granted,basic+4,4);
 wanted=index?0x120116:0x120089; // FILE_GENERIC_WRITE / FILE_GENERIC_READ.
 if((granted&wanted)!=wanted)return false;DWORD type=GetFileType(source);
 if(type==FILE_TYPE_DISK){BY_HANDLE_FILE_INFORMATION actual={},expected={};return index==2&&GetFileInformationByHandle(source,&actual)&&GetFileInformationByHandle(expectedDisk,&expected)&&actual.dwVolumeSerialNumber==expected.dwVolumeSerialNumber&&actual.nFileIndexHigh==expected.nFileIndexHigh&&actual.nFileIndexLow==expected.nFileIndexLow&&actual.nNumberOfLinks==1&&!(actual.dwFileAttributes&FILE_ATTRIBUTE_REPARSE_POINT);}
 if(query(source,1,nameBytes,sizeof(nameBytes),&used)<0||used>sizeof(nameBytes))return false;auto* name=reinterpret_cast<NativeName*>(nameBytes);uintptr_t offset=reinterpret_cast<uintptr_t>(name->value)-reinterpret_cast<uintptr_t>(nameBytes);if(name->length%2||offset<sizeof(NativeName)||offset>sizeof(nameBytes)||name->length>sizeof(nameBytes)-offset)return false;std::wstring value(name->value,name->length/2);
 if(type==FILE_TYPE_CHAR){wanted=index?0x120196:0x120089;return value==L"\\Device\\Null"&&(granted&wanted)==wanted;}
 if(type!=FILE_TYPE_PIPE)return false;
 // libuv's exact per-caller AppContainer LOCAL namespace. Anonymous broker
 // transport pipes cannot satisfy this, even though both are PIPE objects.
 const std::wstring suffix=L"-"+std::to_wstring(callerPid);auto marker=value.rfind(L"\\cc-uv-");if(marker==std::wstring::npos||value.size()<=suffix.size()||value.compare(value.size()-suffix.size(),suffix.size(),suffix))return false;
 const size_t first=marker+7,last=value.size()-suffix.size();if(first==last||last-first>20)return false;for(size_t i=first;i<last;i++)if(value[i]<L'0'||value[i]>L'9')return false;
 return value.rfind(L"\\Device\\NamedPipe\\",0)==0;
}

int wmain(int argc,WCHAR** argv){
 if(argc!=2)return 64;const std::wstring root=argv[1],control=root+L"\\control",workspace=root+L"\\workspace",scratch=root+L"\\scratch",node=control+L"\\node.exe",esbuild=workspace+L"\\tree\\node_modules\\@esbuild\\win32-x64\\esbuild.exe",shim=workspace+L"\\adapter\\esbuild-private-shim.dll";
 Handles held;PSID appSid=nullptr;std::wstring sid,profile;HANDLE job=nullptr,restricted=nullptr,readOnlyMap=nullptr,rootGuard=nullptr,nodeGuard=nullptr,requestRead=nullptr,replyWrite=nullptr;PROCESS_INFORMATION rootProcess={},serviceProcess={};
 const char* stage="host-token";DWORD failure=0,rootExit=STILL_ACTIVE,serviceExit=STILL_ACTIVE,rootWait=WAIT_FAILED,serviceWait=WAIT_FAILED,active=0xffffffff,requests=0;bool complete=false,cleanup=false,profileDeleted=false,loopback=false,rootProven=false,serviceProven=false,mapInstalled=false,serviceMapInstalled=false;LONG serviceMapStatus=0x7fffffff;
 DriveSnapshot before,after;std::string session=randomUuid(),generation=randomUuid();
 std::wstring rootNt,runtimeNt;std::vector<std::wstring> baseEnvironment;
 auto work=[&]()->bool{
  HANDLE token=nullptr;DWORD used=0,container=0;TOKEN_ELEVATION elevation={};alignas(void*) BYTE ownerBytes[1024]={};
  if(!OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY|TOKEN_DUPLICATE|TOKEN_ASSIGN_PRIMARY,&token))return false;held.add(token);
  if(session.empty()||generation.empty()||!GetTokenInformation(token,TokenIsAppContainer,&container,sizeof(container),&used)||container||!GetTokenInformation(token,TokenElevation,&elevation,sizeof(elevation),&used)||elevation.TokenIsElevated||IsTokenRestricted(token)||!GetTokenInformation(token,TokenUser,ownerBytes,sizeof(ownerBytes),&used))return false;
  LPWSTR ownerString=nullptr;if(!ConvertSidToStringSidW(reinterpret_cast<TOKEN_USER*>(ownerBytes)->User.Sid,&ownerString))return false;std::wstring owner=ownerString;LocalFree(ownerString);
  profile=L"cc.private.v4."+widen(session);stage="profile";HRESULT created=CreateAppContainerProfile(profile.c_str(),profile.c_str(),L"Independent same SID host-created service experiment",nullptr,0,&appSid);if(FAILED(created)){failure=created;return false;}
  LPWSTR sidString=nullptr;if(!ConvertSidToStringSidW(appSid,&sidString))return false;sid=sidString;LocalFree(sidString);loopback=noLoopback(appSid);if(!loopback)return false;
  stage="manifest";
  std::string files;for(const auto& item:std::vector<std::pair<std::string,std::wstring>>{{"identity",L"windows-node-private-v4-identity.cjs"},{"preload",L"windows-node-private-v4-preload.cjs"},{"addon",L"windows-node-private-v4.node"}}){
   HANDLE file=pin(held,workspace+L"\\adapter\\"+item.second,false);LARGE_INTEGER size={};auto hash=fileDigest(file);if(file==INVALID_HANDLE_VALUE||hash.size()!=64||!GetFileSizeEx(file,&size))return false;
   if(!files.empty())files+=",";files+="\""+item.first+"\":{\"path\":\"workspace/adapter/"+jsonText(item.second)+"\",\"sha256\":\""+hash+"\",\"bytes\":"+std::to_string(size.QuadPart)+"}";
  }
  std::string manifest="{\"schema\":\"chainlesschain.windows-node-private-manifest/v4\",\"status\":\"NOT_ADMITTED\",\"experimental\":true,\"admissionEligible\":false,\"stage\":\"same-sid-esbuild-service\",\"role\":\"root\",\"sessionId\":\""+session+"\",\"generation\":\""+generation+"\",\"appContainerSid\":\""+jsonText(sid)+"\",\"root\":{\"physical\":\""+jsonText(root)+"\",\"logical\":\"X:\\\\\"},\"runtime\":{\"physical\":\""+jsonText(node)+"\",\"logical\":\"X:\\\\control\\\\node.exe\",\"sha256\":\"ae1a50511be58e987483fdbc12125407443926d2d394669ade2352776e920dd3\",\"bytes\":87074816,\"nodeVersion\":\"22.22.2\",\"modulesAbi\":\"127\"},\"files\":{"+files+"}}\n";
  if(!writeFresh(control+L"\\windows-node-private-v4.manifest.json",manifest))return false;
  stage="private-tree-guards";if(!exactNames(root,{L"control",L"workspace",L"scratch"})||!protect(root,owner,sid)||!protect(scratch,owner,sid,true))return false;
  DWORD count=0;if(!guardPrivateTree(held,control,owner,sid,count)||!guardPrivateTree(held,workspace,owner,sid,count))return false;
  rootGuard=pin(held,root,true);nodeGuard=pin(held,node,false);HANDLE esbuildGuard=pin(held,esbuild,false),shimGuard=pin(held,shim,false);if(rootGuard==INVALID_HANDLE_VALUE||nodeGuard==INVALID_HANDLE_VALUE||esbuildGuard==INVALID_HANDLE_VALUE||shimGuard==INVALID_HANDLE_VALUE||!hashFile(nodeGuard,"ae1a50511be58e987483fdbc12125407443926d2d394669ade2352776e920dd3")||!hashFile(esbuildGuard,"ec02ee9b14ab332416fedd10614dfb80eed5304d94f67745067c011934a8c3c3"))return false;
  WCHAR nt[4096]={};DWORD chars=GetFinalPathNameByHandleW(rootGuard,nt,4096,VOLUME_NAME_NT);if(!chars||chars>=4096)return false;rootNt=nt;chars=GetFinalPathNameByHandleW(nodeGuard,nt,4096,VOLUME_NAME_NT);if(!chars||chars>=4096)return false;runtimeNt=nt;
  stage="device-map";auto native=GetModuleHandleW(L"ntdll.dll");auto createDir=reinterpret_cast<DirFn>(GetProcAddress(native,"NtCreateDirectoryObject"));auto createLink=reinterpret_cast<LinkFn>(GetProcAddress(native,"NtCreateSymbolicLinkObject"));auto setMap=reinterpret_cast<SetFn>(GetProcAddress(native,"NtSetInformationProcess"));if(!createDir||!createLink||!setMap)return false;
  OBJECT_ATTRIBUTES attrs={};attrs.Length=sizeof(attrs);HANDLE map=nullptr;LONG status=createDir(&map,0xF000F,&attrs);if(status<0){failure=status;return false;}held.add(map);WCHAR drive[]=L"X:";UNICODE_STRING name={4,6,drive},target={static_cast<USHORT>(rootNt.size()*2),static_cast<USHORT>((rootNt.size()+1)*2),rootNt.data()};attrs.RootDirectory=map;attrs.ObjectName=&name;attrs.Attributes=0x40;HANDLE link=nullptr;status=createLink(&link,0xF0001,&attrs,&target);if(status<0){failure=status;return false;}held.add(link);
  if(!DuplicateHandle(GetCurrentProcess(),map,GetCurrentProcess(),&readOnlyMap,3,FALSE,0))return false;held.add(readOnlyMap);before=captureDrive();if(!before.known)return false;
  stage="job-and-token";if(!CreateRestrictedToken(token,DISABLE_MAX_PRIVILEGE,0,nullptr,0,nullptr,0,nullptr,&restricted))return false;held.add(restricted);job=held.add(CreateJobObjectW(nullptr,nullptr));JOBOBJECT_EXTENDED_LIMIT_INFORMATION limits={};limits.BasicLimitInformation.LimitFlags=JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE|JOB_OBJECT_LIMIT_ACTIVE_PROCESS|JOB_OBJECT_LIMIT_PROCESS_MEMORY;limits.BasicLimitInformation.ActiveProcessLimit=2;limits.ProcessMemoryLimit=768*1024*1024;if(!job||!SetInformationJobObject(job,JobObjectExtendedLimitInformation,&limits,sizeof(limits)))return false;
  SECURITY_ATTRIBUTES sa={sizeof(sa),nullptr,TRUE};HANDLE nodeRequest=nullptr,nodeReply=nullptr;if(!CreatePipe(&requestRead,&nodeRequest,&sa,4096)||!CreatePipe(&nodeReply,&replyWrite,&sa,4096))return false;held.add(requestRead);held.add(nodeRequest);held.add(nodeReply);held.add(replyWrite);if(!SetHandleInformation(requestRead,HANDLE_FLAG_INHERIT,0)||!SetHandleInformation(replyWrite,HANDLE_FLAG_INHERIT,0))return false;
  HANDLE nullRead=held.add(CreateFileW(L"NUL",0x120089,3,&sa,OPEN_EXISTING,0,nullptr)),nullWrite=held.add(CreateFileW(L"NUL",0x120196,3,&sa,OPEN_EXISTING,0,nullptr));
  HANDLE rootCopy=nullptr,nodeCopy=nullptr;if(!DuplicateHandle(GetCurrentProcess(),rootGuard,GetCurrentProcess(),&rootCopy,GENERIC_READ,TRUE,0))return false;held.add(rootCopy);if(!DuplicateHandle(GetCurrentProcess(),nodeGuard,GetCurrentProcess(),&nodeCopy,GENERIC_READ,TRUE,0))return false;held.add(nodeCopy);
  HANDLE input=held.add(CreateFileW((scratch+L"\\stdin").c_str(),GENERIC_READ,FILE_SHARE_READ,&sa,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr)),output=held.add(CreateFileW((scratch+L"\\stdout").c_str(),GENERIC_WRITE,FILE_SHARE_READ,&sa,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr)),error=held.add(CreateFileW((scratch+L"\\stderr").c_str(),GENERIC_WRITE,FILE_SHARE_READ,&sa,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr));
  WCHAR system[4096]={};DWORD systemChars=GetEnvironmentVariableW(L"SystemRoot",system,4096);if(!systemChars||systemChars>=4096)return false;
  WCHAR localAppData[MAX_PATH]={};if(FAILED(SHGetFolderPathW(nullptr,CSIDL_LOCAL_APPDATA,nullptr,SHGFP_TYPE_CURRENT,localAppData)))return false;
  baseEnvironment={std::wstring(L"SystemRoot=")+system,std::wstring(L"WINDIR=")+system,std::wstring(L"SystemDrive=")+std::wstring(system,2),std::wstring(L"LOCALAPPDATA=")+localAppData,L"TEMP=X:\\scratch",L"TMP=X:\\scratch",L"CC_WINDOWS_APPCONTAINER_SID="+sid,L"CC_PRIVATE_V4_SESSION="+widen(session),L"CC_PRIVATE_V4_GENERATION="+widen(generation),L"CC_PRIVATE_V4_ROOT_DOS="+root,L"CC_PRIVATE_V4_ROOT_NT="+rootNt};
  auto spawn=[&](const std::wstring& application,std::wstring command,const std::vector<HANDLE>& handles,std::vector<std::wstring> entries,bool leaf,PROCESS_INFORMATION& process)->bool{
   for(HANDLE h:handles)if(!h||h==INVALID_HANDLE_VALUE)return false;
   std::sort(entries.begin(),entries.end());std::vector<WCHAR> env;for(const auto& row:entries){env.insert(env.end(),row.begin(),row.end());env.push_back(0);}env.push_back(0);
   SIZE_T bytes=0;InitializeProcThreadAttributeList(nullptr,3,0,&bytes);std::vector<BYTE> store(bytes);auto attributes=reinterpret_cast<LPPROC_THREAD_ATTRIBUTE_LIST>(store.data());if(!InitializeProcThreadAttributeList(attributes,3,0,&bytes))return false;
   stage=leaf?"service-attributes":"root-attributes";SECURITY_CAPABILITIES caps={appSid,nullptr,0,0};DWORD policy=leaf?1:0;bool valid=UpdateProcThreadAttribute(attributes,0,PROC_THREAD_ATTRIBUTE_SECURITY_CAPABILITIES,&caps,sizeof(caps),nullptr,nullptr)&&UpdateProcThreadAttribute(attributes,0,PROC_THREAD_ATTRIBUTE_HANDLE_LIST,const_cast<HANDLE*>(handles.data()),handles.size()*sizeof(HANDLE),nullptr,nullptr)&&UpdateProcThreadAttribute(attributes,0,PROC_THREAD_ATTRIBUTE_CHILD_PROCESS_POLICY,&policy,sizeof(policy),nullptr,nullptr);
   STARTUPINFOEXW start={};start.StartupInfo.cb=sizeof(start);start.StartupInfo.dwFlags=STARTF_USESTDHANDLES;start.StartupInfo.hStdInput=handles[0];start.StartupInfo.hStdOutput=handles[1];start.StartupInfo.hStdError=handles[2];start.lpAttributeList=attributes;
   if(!valid){failure=GetLastError();DeleteProcThreadAttributeList(attributes);return false;}stage=leaf?"service-create-process":"root-create-process";
   BOOL ok=CreateProcessAsUserW(restricted,application.c_str(),command.data(),nullptr,nullptr,TRUE,CREATE_SUSPENDED|CREATE_UNICODE_ENVIRONMENT|EXTENDED_STARTUPINFO_PRESENT|DETACHED_PROCESS,env.data(),workspace.c_str(),&start.StartupInfo,&process);DWORD createError=GetLastError();DeleteProcThreadAttributeList(attributes);if(!ok){failure=createError;return false;}held.add(process.hProcess);held.add(process.hThread);
   if(!AssignProcessToJobObject(job,process.hProcess)||!tokenProof(process.hProcess,appSid,job))return false;LONG mapped=setMap(process.hProcess,23,&readOnlyMap,sizeof(readOnlyMap));if(leaf)serviceMapStatus=mapped;if(mapped<0){failure=mapped;return false;}return true;
  };
  stage="create-root";auto rootEnv=baseEnvironment;rootEnv.insert(rootEnv.end(),{L"CC_WINDOWS_NULL_READ_V3="+handleText(nullRead),L"CC_WINDOWS_NULL_WRITE_V3="+handleText(nullWrite),L"CC_PRIVATE_V4_REQUEST="+handleText(nodeRequest),L"CC_PRIVATE_V4_REPLY="+handleText(nodeReply),L"CC_PRIVATE_V4_ROOT_HANDLE="+handleText(rootCopy),L"CC_PRIVATE_V4_RUNTIME_HANDLE="+handleText(nodeCopy)});
  if(!spawn(node,L"\""+node+L"\" --preserve-symlinks --preserve-symlinks-main X:\\control\\check.cjs",{input,output,error,nullRead,nullWrite,nodeRequest,nodeReply,rootCopy,nodeCopy},rootEnv,false,rootProcess))return false;rootProven=true;mapInstalled=true;if(ResumeThread(rootProcess.hThread)!=1)return false;
  stage="broker-loop";ULONGLONG deadline=GetTickCount64()+45000;
  while(GetTickCount64()<deadline){
   if(WaitForSingleObject(rootProcess.hProcess,0)==WAIT_OBJECT_0)break;DWORD available=0;if(!PeekNamedPipe(requestRead,nullptr,0,nullptr,&available,nullptr))return false;
   if(!available){Sleep(5);continue;}if(available<sizeof(PrivateV4Request)){Sleep(1);continue;}
   PrivateV4Request request={};DWORD read=0;if(!ReadFile(requestRead,&request,sizeof(request),&read,nullptr)||read!=sizeof(request))return false;
   if(request.magic!=kPrivateV4Magic||request.version!=1||request.bytes!=sizeof(request)||request.operation!=1||request.sequence!=1||requests||request.reserved[0]||request.reserved[1]){failure=ERROR_INVALID_DATA;return false;}requests++;
   stage="broker-stdio-identity";Handles childHandles;HANDLE standards[3]={};for(unsigned i=0;i<3;i++){HANDLE observed=nullptr;if(!request.standardHandles[i]||!DuplicateHandle(rootProcess.hProcess,reinterpret_cast<HANDLE>(request.standardHandles[i]),GetCurrentProcess(),&observed,0,FALSE,DUPLICATE_SAME_ACCESS))return false;childHandles.add(observed);DWORD wanted=0;if(!stdioObject(observed,i,rootProcess.dwProcessId,error,wanted)){failure=ERROR_NOT_SUPPORTED;return false;}if(!DuplicateHandle(GetCurrentProcess(),observed,GetCurrentProcess(),&standards[i],wanted,TRUE,0))return false;childHandles.add(standards[i]);}
   HANDLE trace=childHandles.add(CreateFileW((scratch+L"\\esbuild-trace.jsonl").c_str(),GENERIC_WRITE,FILE_SHARE_READ,&sa,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr)),mapCopy=nullptr;if(!DuplicateHandle(GetCurrentProcess(),readOnlyMap,GetCurrentProcess(),&mapCopy,3,TRUE,0))return false;childHandles.add(mapCopy);
   BY_HANDLE_FILE_INFORMATION rootInfo={};if(!GetFileInformationByHandle(rootGuard,&rootInfo))return false;WCHAR rootId[96]={};swprintf(rootId,96,L"%08lx:%08lx:%08lx",rootInfo.dwVolumeSerialNumber,rootInfo.nFileIndexHigh,rootInfo.nFileIndexLow);
   auto serviceEnv=baseEnvironment;serviceEnv.insert(serviceEnv.end(),{L"CC_ESBUILD_TRACE_HANDLE="+handleText(trace),L"CC_ESBUILD_TRACE_MAP_HANDLE="+handleText(mapCopy),L"CC_ESBUILD_TRACE_SID="+sid,L"CC_ESBUILD_TRACE_ROOT_NT="+rootNt,std::wstring(L"CC_ESBUILD_TRACE_ROOT_ID=")+rootId});
   stage="create-service";if(!spawn(esbuild,L"\""+esbuild+L"\" --service=0.28.1 --ping",{standards[0],standards[1],standards[2],trace,mapCopy},serviceEnv,true,serviceProcess))return false;serviceProven=true;serviceMapInstalled=true;
   stage="service-shim";std::wstring loaderPath=L"\\\\?\\GLOBALROOT"+rootNt+L"\\workspace\\adapter\\esbuild-private-shim.dll";SIZE_T bytes=(loaderPath.size()+1)*2,written=0;void* remote=VirtualAllocEx(serviceProcess.hProcess,nullptr,bytes,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE);if(!remote||!WriteProcessMemory(serviceProcess.hProcess,remote,loaderPath.c_str(),bytes,&written)||written!=bytes||!QueueUserAPC(reinterpret_cast<PAPCFUNC>(GetProcAddress(GetModuleHandleW(L"kernel32.dll"),"LoadLibraryW")),serviceProcess.hThread,reinterpret_cast<ULONG_PTR>(remote)))return false;
   PrivateV4Response response={kPrivateV4Magic,1,sizeof(PrivateV4Response),0,1,0,0,serviceProcess.dwProcessId,serviceProcess.dwThreadId,{0,0}};HANDLE processCopy=nullptr,threadCopy=nullptr;
   if(!DuplicateHandle(GetCurrentProcess(),serviceProcess.hProcess,rootProcess.hProcess,&processCopy,SYNCHRONIZE|PROCESS_QUERY_LIMITED_INFORMATION|PROCESS_TERMINATE,FALSE,0)||!DuplicateHandle(GetCurrentProcess(),serviceProcess.hThread,rootProcess.hProcess,&threadCopy,SYNCHRONIZE,FALSE,0))return false;
   response.processHandle=reinterpret_cast<uintptr_t>(processCopy);response.threadHandle=reinterpret_cast<uintptr_t>(threadCopy);if(ResumeThread(serviceProcess.hThread)!=1)return false;DWORD replied=0;if(!WriteFile(replyWrite,&response,sizeof(response),&replied,nullptr)||replied!=sizeof(response))return false;stage="broker-loop";
  }
  stage="root-settlement";rootWait=WaitForSingleObject(rootProcess.hProcess,0);if(rootWait!=WAIT_OBJECT_0){failure=rootWait==WAIT_TIMEOUT?ERROR_TIMEOUT:GetLastError();return false;}if(!GetExitCodeProcess(rootProcess.hProcess,&rootExit)||rootExit){failure=rootExit;return false;}
  stage="service-settlement";if(!serviceProcess.hProcess||requests!=1)return false;serviceWait=WaitForSingleObject(serviceProcess.hProcess,3000);if(serviceWait!=WAIT_OBJECT_0||!GetExitCodeProcess(serviceProcess.hProcess,&serviceExit)||serviceExit){failure=serviceWait==WAIT_TIMEOUT?ERROR_TIMEOUT:serviceExit;return false;}
  stage="completed";return true;
 };
 complete=work();if(!complete&&!failure)failure=GetLastError();if(job)TerminateJobObject(job,125);
 bool stopped=true;for(auto* process:{&rootProcess,&serviceProcess})if(process->hProcess){if(WaitForSingleObject(process->hProcess,0)!=WAIT_OBJECT_0)TerminateProcess(process->hProcess,125);DWORD exit=STILL_ACTIVE;stopped=WaitForSingleObject(process->hProcess,3000)==WAIT_OBJECT_0&&GetExitCodeProcess(process->hProcess,&exit)&&exit!=STILL_ACTIVE&&stopped;}
 if(job){JOBOBJECT_BASIC_ACCOUNTING_INFORMATION accounting={};if(QueryInformationJobObject(job,JobObjectBasicAccountingInformation,&accounting,sizeof(accounting),nullptr))active=accounting.ActiveProcesses;}cleanup=stopped&&(!job||active==0);after=captureDrive();
 if(appSid){loopback=loopback&&noLoopback(appSid);profileDeleted=cleanup&&SUCCEEDED(DeleteAppContainerProfile(profile.c_str()));FreeSid(appSid);}
 std::printf("{\"schema\":\"chainlesschain.windows-private-broker/v4\",\"status\":\"NOT_ADMITTED\",\"completed\":%s,\"stage\":\"%s\",\"error\":%lu,\"hostPid\":%lu,\"rootPid\":%lu,\"servicePid\":%lu,\"rootTokenAndSameJobProven\":%s,\"serviceTokenAndSameJobProven\":%s,\"rootMapInstalled\":%s,\"serviceMapInstalled\":%s,\"serviceMapStatus\":%lu,\"rootWait\":%lu,\"serviceWait\":%lu,\"rootExit\":%lu,\"serviceExit\":%lu,\"requests\":%lu,\"serviceParent\":\"host-custodian\",\"cleanupConfirmed\":%s,\"jobActiveProcesses\":%lu,\"profileDeleted\":%s,\"loopbackExemptionAbsent\":%s,\"hostMapUnchanged\":%s,\"sessionId\":\"%s\",\"generation\":\"%s\",\"appContainerSid\":\"%s\"}\n",complete?"true":"false",stage,failure,GetCurrentProcessId(),rootProcess.dwProcessId,serviceProcess.dwProcessId,rootProven?"true":"false",serviceProven?"true":"false",mapInstalled?"true":"false",serviceMapInstalled?"true":"false",static_cast<DWORD>(serviceMapStatus),rootWait,serviceWait,rootExit,serviceExit,requests,cleanup?"true":"false",active,profileDeleted?"true":"false",loopback?"true":"false",sameDrive(before,after)?"true":"false",session.c_str(),generation.c_str(),jsonText(sid).c_str());
 return complete&&cleanup&&profileDeleted&&loopback&&sameDrive(before,after)?0:2;
}
