/**
 * 内置技能定义
 * 定义系统内置的技能
 *
 * 注意：config 和 tags 必须是 JSON 字符串格式（符合数据库 schema）
 */


// 导入额外的技能定义
const additionalSkills = require('./additional-skills');
const additionalSkillsV3 = require('./additional-skills-v3');

const builtinSkills = [
  {
    "id": "skill_code_development",
    "name": "代码开发",
    "display_name": "Code Development",
    "description": "提供完整的代码开发能力，包括文件读写、代码生成和版本控制",
    "category": "code",
    "icon": "code",
    "tags": `["代码","开发","Git"]`,
    "config": `{"defaultLanguage":"javascript","autoFormat":true,"enableLinting":false}`,
    "doc_path": "docs/skills/code-development.md",
    "tools": [
      "file_reader",
      "file_writer",
      "file_editor",
      "create_project_structure",
      "git_init",
      "git_commit",
      "datetime_handler",
      "regex_tester",
      "zip_handler",
      "color_converter",
      "random_generator",
      "file_searcher",
      "diff_comparator",
      "cron_parser",
      "code_formatter",
      "encoding_detector",
      "version_comparator",
      "slug_generator",
      "gitdiff_parser",
      "language_detector",
      "translator",
      "locale_formatter",
      "file_watcher",
      "directory_monitor",
      "code_linter",
      "ast_parser",
      "complexity_calculator",
      "file_compressor",
      "file_decompressor",
      "qrcode_generator_advanced",
      "qrcode_scanner"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_web_development",
    "name": "Web开发",
    "display_name": "Web Development",
    "description": "创建网页、博客、单页应用等Web项目",
    "category": "web",
    "icon": "global",
    "tags": `["Web","HTML","CSS","JavaScript"]`,
    "config": `{"defaultTemplate":"blog","responsive":true}`,
    "doc_path": "docs/skills/web-development.md",
    "tools": [
      "html_generator",
      "css_generator",
      "js_generator",
      "file_writer",
      "url_parser",
      "ip_utility",
      "useragent_parser",
      "html_parser",
      "dns_lookup",
      "port_checker",
      "api_requester",
      "oauth_helper",
      "web_crawler",
      "html_extractor",
      "websocket_server",
      "contract_caller",
      "device_manager",
      "mqtt_client",
      "photonic_router",
      "network_speed_tester",
      "network_diagnostic_tool"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_data_analysis",
    "name": "数据分析",
    "display_name": "Data Analysis",
    "description": "读取CSV/Excel、数据清洗和可视化",
    "category": "data",
    "icon": "bar-chart",
    "tags": `["数据","分析","可视化"]`,
    "config": `{"chartType":"auto","exportFormat":"png"}`,
    "doc_path": "docs/skills/data-analysis.md",
    "tools": [
      "file_reader",
      "json_parser",
      "yaml_parser",
      "markdown_converter",
      "xml_parser",
      "data_aggregator",
      "statistical_calculator",
      "chart_data_generator",
      "data_validator",
      "schema_validator",
      "time_series_analyzer",
      "trend_detector",
      "migration_runner",
      "schema_differ",
      "graph_plotter",
      "protobuf_encoder",
      "protobuf_decoder",
      "search_indexer",
      "search_query",
      "spatial_analyzer",
      "route_planner",
      "financial_modeler",
      "risk_analyzer",
      "recommendation_engine",
      "inventory_manager",
      "content_publisher",
      "media_manager",
      "sentiment_monitor",
      "influencer_analyzer",
      "logistics_optimizer",
      "demand_forecaster",
      "production_scheduler",
      "orbit_calculator",
      "flight_planner",
      "navigation_planner",
      "underwater_navigator",
      "deep_sea_mapper"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_content_creation",
    "name": "内容创作",
    "display_name": "Content Creation",
    "description": "写文章、文档编辑、Markdown处理",
    "category": "content",
    "icon": "edit",
    "tags": `["写作","Markdown","文档"]`,
    "config": `{"defaultFormat":"markdown"}`,
    "doc_path": "docs/skills/content-creation.md",
    "tools": [
      "file_reader",
      "file_writer",
      "format_output",
      "regex_tester",
      "markdown_converter",
      "diff_comparator",
      "encoding_detector",
      "slug_generator",
      "language_detector",
      "translator",
      "locale_formatter",
      "pdf_text_extractor",
      "pdf_merger",
      "note_editor",
      "note_searcher"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_document_processing",
    "name": "文档处理",
    "display_name": "Document Processing",
    "description": "Word/PDF/Excel/PPT生成和编辑",
    "category": "document",
    "icon": "file-text",
    "tags": `["文档","Office","PDF"]`,
    "config": `{"defaultFormat":"docx"}`,
    "doc_path": "docs/skills/document-processing.md",
    "tools": [
      "file_reader",
      "file_writer",
      "markdown_converter",
      "pdf_text_extractor",
      "pdf_merger",
      "note_editor",
      "note_searcher"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_image_processing",
    "name": "图像处理",
    "display_name": "Image Processing",
    "description": "图片压缩、格式转换、OCR等",
    "category": "media",
    "icon": "picture",
    "tags": `["图片","图像","OCR"]`,
    "config": `{"quality":80,"maxWidth":1920}`,
    "doc_path": "docs/skills/image-processing.md",
    "tools": [
      "image_editor",
      "image_filter",
      "image_metadata",
      "qrcode_generator",
      "video_metadata_reader",
      "audio_duration_calculator",
      "subtitle_parser",
      "speech_recognizer",
      "text_to_speech",
      "barcode_generator",
      "code_recognizer",
      "video_transcoder",
      "video_screenshot",
      "model_generator",
      "model_converter",
      "audio_fingerprint",
      "physics_engine",
      "collision_detector",
      "bim_modeler",
      "structure_analyzer",
      "ar_content_creator",
      "vr_scene_builder",
      "voice_cloner",
      "screenshot_tool",
      "screen_recorder"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_video_processing",
    "name": "视频处理",
    "display_name": "Video Processing",
    "description": "视频剪辑、合并、格式转换",
    "category": "media",
    "icon": "video-camera",
    "tags": `["视频","剪辑"]`,
    "config": `{"format":"mp4","quality":"high"}`,
    "doc_path": "docs/skills/video-processing.md",
    "tools": [
      "video_cutter",
      "video_merger",
      "video_editor",
      "image_metadata",
      "qrcode_generator",
      "video_metadata_reader",
      "audio_duration_calculator",
      "subtitle_parser",
      "speech_recognizer",
      "text_to_speech",
      "barcode_generator",
      "code_recognizer",
      "video_transcoder",
      "video_screenshot",
      "model_generator",
      "model_converter",
      "audio_fingerprint",
      "physics_engine",
      "collision_detector",
      "bim_modeler",
      "structure_analyzer",
      "ar_content_creator",
      "vr_scene_builder",
      "voice_cloner",
      "screenshot_tool",
      "screen_recorder"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_code_execution",
    "name": "代码执行",
    "display_name": "Code Execution",
    "description": "Python、Bash等代码执行和调试",
    "category": "code",
    "icon": "thunderbolt",
    "tags": `["执行","Python","Bash"]`,
    "config": `{"timeout":30000,"sandbox":true}`,
    "doc_path": "docs/skills/code-execution.md",
    "tools": [
      "file_reader",
      "file_writer",
      "test_runner",
      "datetime_handler",
      "regex_tester",
      "zip_handler",
      "color_converter",
      "random_generator",
      "file_searcher",
      "diff_comparator",
      "cron_parser",
      "code_formatter",
      "encoding_detector",
      "version_comparator",
      "slug_generator",
      "gitdiff_parser",
      "language_detector",
      "translator",
      "locale_formatter",
      "file_watcher",
      "directory_monitor",
      "code_linter",
      "ast_parser",
      "complexity_calculator",
      "file_compressor",
      "file_decompressor",
      "qrcode_generator_advanced",
      "qrcode_scanner"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_project_management",
    "name": "项目管理",
    "display_name": "Project Management",
    "description": "创建项目结构、Git版本控制",
    "category": "project",
    "icon": "project",
    "tags": `["项目","Git","管理"]`,
    "config": `{"autoGit":true}`,
    "doc_path": "docs/skills/project-management.md",
    "tools": [
      "create_project_structure",
      "git_init",
      "git_commit",
      "info_searcher",
      "datetime_handler",
      "zip_handler",
      "color_converter",
      "random_generator",
      "file_searcher",
      "cron_parser",
      "version_comparator",
      "gitdiff_parser",
      "file_watcher",
      "directory_monitor",
      "file_compressor",
      "file_decompressor",
      "qrcode_generator_advanced",
      "qrcode_scanner",
      "npm_project_setup",
      "package_json_builder",
      "python_project_setup",
      "requirements_generator",
      "setup_py_generator",
      "gitignore_generator",
      "eslint_config_generator"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_knowledge_search",
    "name": "知识库搜索",
    "display_name": "Knowledge Search",
    "description": "知识库查询和RAG语义搜索",
    "category": "ai",
    "icon": "search",
    "tags": `["知识库","RAG","搜索"]`,
    "config": `{"topK":5,"threshold":0.7}`,
    "doc_path": "docs/skills/knowledge-search.md",
    "tools": [
      "info_searcher",
      "file_reader",
      "text_analyzer",
      "regex_tester",
      "diff_comparator",
      "encoding_detector",
      "slug_generator",
      "language_detector",
      "model_predictor",
      "translator",
      "locale_formatter",
      "model_trainer",
      "text_classifier",
      "entity_recognizer",
      "sequence_aligner",
      "protein_predictor",
      "exercise_generator",
      "auto_grader",
      "medical_image_analyzer",
      "health_monitor",
      "legal_document_generator",
      "case_searcher",
      "quantum_circuit_builder",
      "quantum_simulator",
      "object_detector",
      "image_segmenter",
      "weather_analyzer",
      "pollution_predictor",
      "edge_inferencer",
      "twin_model_builder",
      "twin_simulator",
      "crop_monitor",
      "public_safety_monitor",
      "ocean_monitor",
      "renewable_forecaster",
      "quantum_teleporter",
      "eeg_processor",
      "bci_decoder",
      "gene_editor",
      "protein_designer",
      "nano_simulator",
      "reactor_simulator",
      "asteroid_analyzer",
      "weather_modeler",
      "material_designer",
      "property_predictor",
      "snn_builder",
      "optical_nn_designer"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_template_application",
    "name": "模板应用",
    "display_name": "Template Application",
    "description": "使用模板创建项目和内容",
    "category": "template",
    "icon": "layout",
    "tags": `["模板","快速创建"]`,
    "config": `{"defaultCategory":"writing"}`,
    "doc_path": "docs/skills/template-application.md",
    "tools": [
      "template_renderer",
      "file_writer",
      "format_output",
      "html_generator",
      "markdown_converter",
      "zip_handler",
      "file_searcher",
      "file_watcher",
      "directory_monitor",
      "file_compressor",
      "file_decompressor"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_system_operations",
    "name": "系统操作",
    "display_name": "System Operations",
    "description": "文件系统操作和通用处理",
    "category": "system",
    "icon": "setting",
    "tags": `["系统","文件"]`,
    "config": "{}",
    "doc_path": "docs/skills/system-operations.md",
    "tools": [
      "file_reader",
      "file_writer",
      "generic_handler",
      "datetime_handler",
      "zip_handler",
      "color_converter",
      "random_generator",
      "file_searcher",
      "cron_parser",
      "version_comparator",
      "file_watcher",
      "directory_monitor",
      "resource_monitor",
      "container_orchestrator",
      "cicd_pipeline",
      "iot_device_manager",
      "mqtt_broker",
      "edge_node_manager",
      "plc_controller",
      "scene_automator",
      "device_linker",
      "irrigation_controller",
      "traffic_controller",
      "power_dispatcher",
      "nano_fabricator",
      "radiation_monitor",
      "lunar_miner",
      "cloud_seeder",
      "neuromorphic_accelerator",
      "file_compressor",
      "file_decompressor",
      "qrcode_generator_advanced",
      "qrcode_scanner"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_network_requests",
    "name": "网络请求",
    "display_name": "Network Requests",
    "description": "HTTP请求、API调用、网页抓取",
    "category": "network",
    "icon": "api",
    "tags": `["网络","HTTP","API"]`,
    "config": `{"timeout":10000,"retry":3}`,
    "doc_path": "docs/skills/network-requests.md",
    "tools": [
      "http_client",
      "websocket_client",
      "url_parser",
      "ip_utility",
      "useragent_parser",
      "dns_lookup",
      "port_checker",
      "api_requester",
      "oauth_helper",
      "web_crawler",
      "html_extractor",
      "websocket_server",
      "contract_caller",
      "device_manager",
      "mqtt_client",
      "photonic_router",
      "network_speed_tester",
      "network_diagnostic_tool"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_ai_conversation",
    "name": "AI对话",
    "display_name": "AI Conversation",
    "description": "LLM查询、Prompt模板填充",
    "category": "ai",
    "icon": "robot",
    "tags": `["AI","LLM","对话"]`,
    "config": `{"temperature":0.7,"maxTokens":2000}`,
    "doc_path": "docs/skills/ai-conversation.md",
    "tools": [
      "text_analyzer",
      "sentiment_analyzer",
      "regex_tester",
      "diff_comparator",
      "encoding_detector",
      "slug_generator",
      "language_detector",
      "model_predictor",
      "translator",
      "locale_formatter",
      "model_trainer",
      "text_classifier",
      "entity_recognizer",
      "sequence_aligner",
      "protein_predictor",
      "exercise_generator",
      "auto_grader",
      "medical_image_analyzer",
      "health_monitor",
      "legal_document_generator",
      "case_searcher",
      "quantum_circuit_builder",
      "quantum_simulator",
      "object_detector",
      "image_segmenter",
      "weather_analyzer",
      "pollution_predictor",
      "edge_inferencer",
      "twin_model_builder",
      "twin_simulator",
      "crop_monitor",
      "public_safety_monitor",
      "ocean_monitor",
      "renewable_forecaster",
      "quantum_teleporter",
      "eeg_processor",
      "bci_decoder",
      "gene_editor",
      "protein_designer",
      "nano_simulator",
      "reactor_simulator",
      "asteroid_analyzer",
      "weather_modeler",
      "material_designer",
      "property_predictor",
      "snn_builder",
      "optical_nn_designer"
    ],
    "enabled": 1,
    "is_builtin": 1
  },
  {
    "id": "skill_automation_workflow",
    "name": "自动化工作流",
    "display_name": "Automation Workflow",
    "description": "任务链执行和条件判断",
    "category": "automation",
    "icon": "branches",
    "tags": `["自动化","工作流"]`,
    "config": `{"maxSteps":50,"errorHandling":"continue"}`,
    "doc_path": "docs/skills/automation-workflow.md",
    "tools": [
      "file_reader",
      "file_writer",
      "http_client",
      "datetime_handler",
      "zip_handler",
      "color_converter",
      "random_generator",
      "file_searcher",
      "cron_parser",
      "version_comparator",
      "workflow_executor",
      "event_emitter",
      "pipeline_builder",
      "file_watcher",
      "directory_monitor",
      "cron_scheduler",
      "task_timer",
      "resource_monitor",
      "container_orchestrator",
      "cicd_pipeline",
      "iot_device_manager",
      "mqtt_broker",
      "edge_node_manager",
      "plc_controller",
      "scene_automator",
      "device_linker",
      "irrigation_controller",
      "traffic_controller",
      "power_dispatcher",
      "nano_fabricator",
      "radiation_monitor",
      "lunar_miner",
      "cloud_seeder",
      "neuromorphic_accelerator",
      "file_compressor",
      "file_decompressor",
      "qrcode_generator_advanced",
      "qrcode_scanner"
    ],
    "enabled": 1,
    "is_builtin": 1
  }
];

// 导入额外的技能定义 V4
const additionalSkillsV4 = require('./additional-skills-v4');

// 合并所有技能
const allSkills = [...builtinSkills, ...additionalSkills, ...additionalSkillsV3, ...additionalSkillsV4];

module.exports = allSkills;